### ISSUE TITLE
Doc: Update Documentation with plainToInstance and instanceToPlain instead of plainToClass and classToPlain

### ISSUE THREAD

**Issue by meunierfrederic** [typestack/class-transformer#1010]
### Description
From 0.4.0 to 0.4.1 suddenly plainToClass and classToPlain methods were renamed to plainToInstance and instanceToPlain.
This is semantically consistent. 

### Proposed solution
- update the CHANGELOG.md file of release 0.4.1
- update the README.md file

Thanks

**Comment by p-prins** [comment]
Good catch! To the maintainers of this package; first, thank you 🏆; second, is it an idea to apply semver? This was a breaking change and it would have been nice to upgrade the version number of the package accordingly.
