### ISSUE TITLE
question: Module '"class-transformer"' has no exported member 'classToClass'

### ISSUE THREAD

**Issue by alfiadoconstantino** [typestack/class-transformer#1015]
**I was trying to...**
 
 
other methods it exports less this one.

import { classToClass } from 'class-transformer'

i'm using:
class-transformer 0.5.1
NODEJS 16
TYPSCRIPT
**The problem:**

**Comment by lucasraziel** [comment]
I think that this function has changed of name

https://github.com/typestack/class-transformer/commit/01db22254fd3c2ae03279c567d27312afa2ad14f#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

I believe that documentation should change too.

**Comment by lu0dan** [comment]
> I think that this function has changed of name
> 
> [01db222#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80](https://github.com/typestack/class-transformer/commit/01db22254fd3c2ae03279c567d27312afa2ad14f#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80)
> 
> I believe that documentation should change too.

This should be a permanent change. Thanks for the info.

**Comment by gildoneto** [comment]
> I think that this function has changed of name
> 
> [01db222#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80](https://github.com/typestack/class-transformer/commit/01db22254fd3c2ae03279c567d27312afa2ad14f#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80)
> 
> I believe that documentation should change too.

Thank you!!

**Comment by hauzlife** [comment]
> I think that this function has changed of name
> 
> [01db222#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80](https://github.com/typestack/class-transformer/commit/01db22254fd3c2ae03279c567d27312afa2ad14f#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80)
> 
> I believe that documentation should change too.

Thank you!
