### ISSUE TITLE
generic plainToClass

### ISSUE THREAD

**Issue by 91milena** [typestack/class-transformer#102]
How can I create a generic function for deserialization? Is it possible without passing parameters to function (only to pass type of object I want deserialize to, like get<T>())?

**Comment by silberistgold** [comment]
I think I am having the same question:

I have a `Deserializer` class that has different functions for obtaining objects from a db table. It looks something like this:

```
class Deserializer<T> {
  async get(id: string, type: ClassType<T>): Promise<T> {
    const rawDataFromDb = getDataFromDB(id);
    return plainToClass(type, rawDataFromDb);
  }
}
```

This works, but passing the extra `type` to the function is ugly. Any idea how to get rid of it?

**Comment by NoNameProvided** [comment]
> This works, but passing the extra type to the function is ugly. Any idea how to get rid of it?

You cannot get rid of it. The library needs to know what is your target class to transform the received value.
