### ISSUE TITLE
question: how can I expose my custom getter?

### ISSUE THREAD

**Issue by simplenotezy** [typestack/class-transformer#1060]
I've tried to define a custom getter like this:

    import { Expose } from 'class-transformer';
    
    export class MyDTOResponse {
      @Expose()
      id: string;
    
      @Expose()
      name: string;
    
      @Expose()
      get thisIsATest(): string {
        return 'yolo';
      }
    }

This is how I transform it:

    plainToClass(MyDTOResponse, MyRawDataObject, {
      excludeExtraneousValues: true,
    });

As described in the documentation here: https://github.com/typestack/class-transformer#exposing-getters-and-method-return-values

However, the response is only:

    {
      "id": "f8c213c7-5853-4d01-b424-cb0349a6c580",
      "name": "Clean the kitchen!"
    }

I am not sure what I am doing wrong exactly, but I am missing the "thisIsATest" property.

**Comment by DmytroMysak** [comment]
Also having the same issue. As workaround moved getter to Transform like:
```
export class MyDTOResponse {
  @Expose()
  id: string;

  @Expose()
  name: string;

  @Expose()
  @Transform(() => 'yolo')
  thisIsATest: string;
}
```

**Comment by groch2** [comment]
It is not an issue with class-transformer. Getter inside javascript class are not exposed at serialization. You must customize the serialization process by creating a [custom toJSON method](https://thecodebarbarian.com/what-is-the-tojson-function-in-javascript.html) inside your class.

**Comment by q815101630** [comment]
> Also having the same issue. As workaround moved getter to Transform like:
> 
> ```
> export class MyDTOResponse {
>   @Expose()
>   id: string;
> 
>   @Expose()
>   name: string;
> 
>   @Expose()
>   @Transform(() => 'yolo')
>   thisIsATest: string;
> }
> ```

Thanks, I met the same problem.
Here's my workaround for exposing a new field based on existing field:

```typescript
@Expose()
@Transform(({ obj }) => `${obj.id}+${obj.name}`)
idName: string;
```
where obj refers to the source object. https://github.com/typestack/class-transformer#advanced-usage

**Comment by edkhrian** [comment]
@simplenotezy I guess it's late, but anyway. Main purpose of plainToClass (plainToInstance) is to bind your plain object fields to class properties, so It doesn't really need to call your class getters. To make your getters called you need to transfer instance of your class back to plain object like so:
```javascript
classToPlain(plainToClass(MyDTOResponse, MyRawDataObject));
```

**Comment by vasilev-alex** [comment]
This actually looks like a bug according to the docs

**Comment by t-ega** [comment]
This is absolutely right. Solved the issue. Thanks @edkhrian!

**Comment by diffy0712** [comment]
Closing as answered! Thank you @edkhrian for your answer.
