### ISSUE TITLE
question: why breaking change is always not reflected in the version number

### ISSUE THREAD

**Issue by GeekEast** [typestack/class-transformer#1069]
The version number <major.minor.patch> should always reflect the change types.

However, even it's a breaking change, the number only increase in minor.

Which will make the client hard to update dependency using some command lines, e.g. `yarn upgrade-interactive`

**Comment by diffy0712** [comment]
Hello @GeekEast,

please check https://github.com/typestack/class-transformer/issues/1405#issuecomment-1460025372 answer on the same question in a newer issue.
