### ISSUE TITLE
What decorator should I use for transforming the value when plainToInstance method is used?

### ISSUE THREAD

**Issue by PavelTurk** [typestack/class-transformer#1089]
I have a class with enumeration. I want to transform the value of string to enum when `plainToInstance` method is used. I found Transform decorator, but, it works only when `instanceToPlain` is called. Could anyone say what decorator I should use? 

The question was also asked on [StackOverflow](https://stackoverflow.com/questions/70868416/what-decorator-is-used-for-transforming-the-value-within-plaintoinstance-method)

**Comment by aboqasem** [comment]
Please provide a code snippet of what you are trying to do. This works fine:

```ts
import { plainToInstance, Transform } from "class-transformer";

enum Env {
  Development = "development",
  Production = "production"
}

class Config {
  @Transform(({ value }) =>
    value === "dev" ? Env.Development : Env.Production
  )
  env!: Env;
}

console.log(plainToInstance(Config, { env: "dev" }));
```
