### ISSUE TITLE
question: how transform and validate object with file

### ISSUE THREAD

**Issue by MistyKuu** [typestack/class-transformer#113]
How can I transform object with files? Basically what I'm trying to achieve is transform my json object into a class and then validate it using class-validator library. The issue is that, if I exclude property with type 'File' then it will not validate it correctly because it will always be invalid. The workaround I took is to do some preprocessing on the object to convert File property into a string property, let it validate and then assign properties back. Is there a way I can transform it and validate it if property is not empty? By saying file I mean javascript File class. The issue here is the constructor in File class so the object cannot be constructed.

**Comment by NoNameProvided** [comment]
If I understand you correctly, you don't really want to convert the file property just copy it over to the class right?

**Comment by sufrimenda** [comment]
@MistyKuu I've come up with something like this:

```typescript
export class FileWithoutStream {
    @Exclude()
    _writeStream;
}

export class AvatarInputDto {
    @IsNumber()
    left: number;

    @IsNumber()
    length: number;

    @IsNumber()
    top: number;

    @Allow()
    @Type(() => FileWithoutStream)
    @Transform((_, { file }) => file)
    file;
}
```
This way you don't have to exclude the file. Now class-transformer is able to process it.

It works like that:
* firstly class-transformer puts rubbish into `file`
* after that I immediately replace that rubbish in `transform` decorator with the original file

This way later on class-validator has access to that file.

**Comment by NoNameProvided** [comment]
The issue you have been facing has been fixed. We had an issue where we tried to always construct a class when found one. We are not doing that anymore.

> The issue here is the constructor in File class so the object cannot be constructed.

However, I am closing this question as out-of-date. If you are still experiencing this issue please open a new question.
