### ISSUE TITLE
Feature request: @Type for different types inside array

### ISSUE THREAD

**Issue by janis91** [typestack/class-transformer#115]
I want to propose a feature regarding the ```@Type()``` decorator:
If I have an Array of different objects (not completely different, but with some additional properties for example) that should be transformed, I'd like to be able to determine the correct type for each of the objects. At the moment I can only give a function that determines the Type for all objects.

This could be done by calling the given function for each object and give another TypeOption or overwriting the options.object for that behaviour (would cause a breaking change of course).

**Comment by loki2302** [comment]
Looks like a sub-case of #51

**Comment by janis91** [comment]
@agibalov you're right. I close this in favor of #51
