### ISSUE TITLE
0.5.1 classToClass not defined - breaking changes - update readme

### ISSUE THREAD

**Issue by arthabus** [typestack/class-transformer#1152]
### Description
After updateding to 0.5.1 from 0.4.0 my app started to throw exceptions in the places where I was using classToClass.

After a few hours of trying to figure out the problem and after finally checking the source code, it appeared that `classToClass` was renamed to `instanceToInstance`, but there is no indication of that in the readme.

### Expected behavior
Indicate breaking changes in the readme

### Actual behavior
Breaking changes not reflected anywhere

As a side note, it seems like the "develop" branch is the default one. Not sure if that was intended, but just wanted to mention it.

**Comment by sergiohdljr** [comment]
Same problem here, thank you for share this issue. crazy that the doc don't mention the change

**Comment by diffy0712** [comment]
Hello @arthabus,

The [Changelog](https://github.com/typestack/class-transformer/blob/develop/CHANGELOG.md) is the place to look for the changes between releases. As I see it mentions the changes correctly.

I close this issue as it contains no problem.

**Comment by arthabus** [comment]
@diffy0712 I can see that it was in fact fixed by [this commit](https://github.com/typestack/class-transformer/commit/1f95dcbbf61bf7d140c3020c714bb17a09774f4f) about a week ago which updated the readme accordingly.

Thanks for pointing to the changelog though
