### ISSUE TITLE
class-transformer with google firestore

### ISSUE THREAD

**Issue by joeldatabox** [typestack/class-transformer#116]
I'm trying to use the class-transformer to parse the data before saving in google firestore, but I'm comproblemas. Does anyone have any examples of how I can use it?

**Comment by NoNameProvided** [comment]
Hi, can you please provide more context? What have you tried and what is not working?

**Comment by BrandiATMuhkuh** [comment]
Hi @joeldatabox ,
I do exactly the same. And it works very well. 
Here is a code snippet: 
`collectionRef.doc("documentKey").set(JSON.parse(transformer.serialize(myLocalObject)))`

when loading the object use
`let myFirebaseObject:SomeClass =  transformer.plainToClass(SomeClass, doc.data()));`

**Comment by joeldatabox** [comment]
Hi @BrandiATMuhkuh ,
In this approach does the real-time functionality still work?

**Comment by joeldatabox** [comment]
Hi @NoNameProvided ,
I'll see if I can create a demoApp to demonstrate what happens. Thank you for your attention.
Forgive me the delay in responding...

**Comment by NoNameProvided** [comment]
@joeldatabox No worries take your time:), a demo app always helps a lot!

**Comment by BrandiATMuhkuh** [comment]
@joeldatabox I did not test the realtime functionality yet. Let me look at the demo. that might help. Good luck

**Comment by NoNameProvided** [comment]
Closing this as solved. Feel free to continue the discussion if it's not the case.
