### ISSUE TITLE
VSCode TSC Compilation Errors

### ISSUE THREAD

**Issue by AbbottF** [typestack/class-transformer#1231]
[Class-Tramsformer tsc errors.txt](https://github.com/typestack/class-transformer/files/8839009/Class-Tramsformer.tsc.errors.txt)

I opened the Class-Transformer folder in Vs Code. When I  tsc, here are some of the errors that were thrown.

Are there any other libraries needed to support it in VS Code?

Thanks
Abbott

**Comment by diffy0712** [comment]
The issue does not contain a simple reproduction case.

Closing as invalid.
