### ISSUE TITLE
npm package confusion

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [typestack/class-transformer#124]
So I understand that pleerock was the original author of the package. A month ago or so, I've noticed that his repo redirects to this one, which has few upgrades and patches. And yet, the npm repository still holds the old code, that crashes because of that null in TransformMetadata class. 

Is there a chance that npm repo will be updated with new build anytime soon? If not and pleerock still holds credentials to that, is there a chance to release a fixed package under a different name? I know that this (https://www.npmjs.com/package/class-transformer-fixed) exists, but it started from even another branch and I don't its code is up to date?

**Comment by NoNameProvided** [comment]
Yes, I will update the package on npm soon, I still want to close some tickets and merge the PRs before.

**Comment by sebastian-zarzycki-es** [comment]
Great. Which package, to be sure? class-transformer or class-transformer-fixed?

**Comment by NoNameProvided** [comment]
I will update `class-transformer`. 

I haven't heard about `class-transformer-fixed`, it's not an official package from us. I will reach out to the author to resolve this. Thanks for pointing it out.

**Comment by sebastian-zarzycki-es** [comment]
Any idea, when?

**Comment by NoNameProvided** [comment]
My first idea was to update class-validatior first then move to class-transformer, but I see a lot of people need this so I will just do a fix release for class-transformer, probably in the weekend.

**Comment by sebastian-zarzycki-es** [comment]
Thank you!

**Comment by NoNameProvided** [comment]
Which is the issue you want to get fixed? Has it landed already? If not, can you please link an open issue?

**Comment by NoNameProvided** [comment]
Just published `0.1.9`, please test it and report if you still encounter your issue. Thanks!

**Comment by sebastian-zarzycki-es** [comment]
Oh, it was this commit - https://github.com/typestack/class-transformer/commit/4a393d20d5dca5cfd9fb80ac798917058d5d5f4c - so whatever else is fixed besides that, even better!
