### ISSUE TITLE
serialize a class in an object

### ISSUE THREAD

**Issue by veeramarni** [typestack/class-transformer#126]
I have following object`ICoreFileStat`, which on the server side, URI will be a class created using [vscode-uri](https://github.com/Microsoft/vscode-uri/blob/master/lib/index.ts). How do I convert only URI to string recursively? 
```
export interface ICoreFileStat extends ICoreBaseStat {
  children?: ICoreFileStat[];
}
export interface ICoreBaseStat {
  resource: URI | string;
  name?: string;
}
```

What I was expecting the URI in the above object will be transformed to `string` like `(file:///index.js)` and it will be a pure object like below. 

    const data = {
    children: {
       resource: "///file://tmp"
       children: {
          resource: "///file:/index.js"
        }
    }

**Comment by NoNameProvided** [comment]
You need to use the `@Transform` decorator: 

```ts
export class ICoreFileStat extends ICoreBaseStat {
  @Type(ICoreFileStat)
  children?: ICoreFileStat[];
}

export class ICoreBaseStat {
  @Transform(v => v.toString())
  resource: URI | string;
  
  @Type(String) 
  name?: string;
}
```
