### ISSUE TITLE
ES6 Map not working with a type

### ISSUE THREAD

**Issue by benifest** [typestack/class-transformer#1265]
I am following this instruction: https://www.npmjs.com/package/class-transformer#working-with-arrays

```
export class Weapon {
  name: string;
  range: number;
}

export class Player {
  @Type(() => Weapon)
  weapons: Map<string, Weapon>;
}
```
And this is not working. When i do this i get a broken map.

As i understand i have to pass a type for a property. So it means that i have to pass the Map type, not the Weapon. But i can not use 2 different types.

Is it a bug? Or do i not understand something?

**Comment by dieeisenefaust** [comment]
Agreed. I have questions about how `@Type` is meant to work with `Map ` as well.

When trying to copy the example provided for Maps in the documentation and just using the `@Type` decorator, the tranformation to instance doesn't work.

My scenario involves phone numbers where the key is an enum value: `Map<PhoneType, string>`

I have tried `@Type(() => Map<PhoneType, string>), @Type(() => Map<string, string>)`, etc.

My expectation is that something like `@Type(() => Map<PhoneType, string>)` would complete the transformation correctly without the need for the extra `@Transform` decorator.

The only one has that has worked is when I combine `@Type` with `@Transform` to explicitly give instructions on how to tranform the data as shown below.

If this is intended, then the documentation needs to be updated to reflect this extra requirement, but if class-transformer should be able to perform this transformation without the @Transform decorator then either the documentation needs updating to show exactly how or there is a defect.

Example of the only way I have been able to make it work:

Enum:
```
enum PhoneType {
  Home = "Home",
  Mobile = "Mobile",
  Work = "Work",
}
```

JSON data to instance:
   ```
 "payload": {
        "username": "example1",
        "firstName": "Kevin",
        "lastName": "Smith",
        "password": "thisisatest",
        "phoneNumbers": [
                [
                    "Home", "123-456-7890"
                ],
                [
                    "Cell", "098-765-4321"
                ]
            ]
        }
```
DTO excerpt: 
```
  @Transform(({ value }) => new Map(value), { toClassOnly: true })
  @Transform(({ value }) => JSON.stringify(Array.from(value.entries())), {
    toPlainOnly: true,
  })
  public phoneNumbers: Map<PhoneType, string>;
```
Instance to JSON transformation:
```
User {
  username: 'example1',
  firstName: 'Kevin',
  lastName: 'Smith',
  password: '[***]',
  phoneNumbers: Map(2) {
    'Home' => '123-456-7890',
    'Cell' => '098-765-4321'
  },
  id: 'users/609-A'
}
```

**Comment by diffy0712** [comment]
Hello @dieeisenefaust,
Thank you for the detailed comment. Only string keys are supported currently for maps using Type. If you have any questions left feel free to comment on this issue or open a new one.

Regarding the original issue, I was unable to replicate the bug without the plain object or the details of the meaning of 'broken map'. 
Closing as invalid.
