### ISSUE TITLE
Ability to run custom transforms before library transforms

### ISSUE THREAD

**Issue by guscastro** [typestack/class-transformer#127]
In https://github.com/typestack/class-transformer/blob/master/src/TransformOperationExecutor.ts#L168 , library transforms (`this.transform`) are run before custom transforms. I would like to be able to have my custom transforms run before the library transforms. See the following case:

```
import { ZonedDateTime } from 'js-joda';

class Class {
  @Transform(value => value.format(...), { toPlainOnly: true })
  prop: ZonedDateTime
}
```

When converting `Class` to plain, I would like `value` passed into to my transform function to be a `ZonedDateTime`, including its built-in functions (e.g.: `format`). Instead, `value` is a plain JavaScript object containing only properties of the original `prop`, but none of the functions. This ultimately comes down to the line I mentioned above.

Further, since `class-transformer` tries to traverse the `ZonedDateTime` prop, it hits circular references and forces me to `enableCircularCheck`, which was otherwise not needed for my app.

**Comment by MTschannett** [comment]
I guess it would be a good idea to run custom transformers before the build-in ones.

Maybe we could even skip the execution for these.

@cojack What do you think about this?

**Comment by cojack** [comment]
@MTschannett I think that #160 fix this issue, don't you think? @guscastro can you take a look at it?

**Comment by guscastro** [comment]
Yes, it does. Thank you.
