### ISSUE TITLE
question: is the project still alive ?

### ISSUE THREAD

**Issue by LeoMartinDev** [typestack/class-transformer#1272]
Last release was 22 nov 2021 and documentation is not up to date (e.g: `plainToClass` is deprecated but it's not indicated in documentation)

**Comment by MansurAliKoroglu** [comment]
When I first come here to read the full documentation I also think the same. Current documentation is old. I hope this is still maintained.

**Comment by DnOberon** [comment]
What's replacing `plainToClass` @LeoMartinDev

**Comment by DnOberon** [comment]
This isn't really maintained, or if so - just barely.

**Comment by scpedicini** [comment]
Wish you could filter "meaningless" commit history (such as dependabot) - because this lib hasn't had any real updates since 2021.

**Comment by jsw** [comment]
Has anyone found a suitable replacement?

**Comment by NoNameProvided** [comment]
In short, yes. For details see https://github.com/typestack/class-validator/issues/1775
