### ISSUE TITLE
question: how to set default value

### ISSUE THREAD

**Issue by chacha95** [typestack/class-transformer#1281]
**I was trying to...**
I want to set default value in my dto.
How can I set default value in page variable using class-transformer's decorator?
> sample code
```ts
@ApiPropertyOptional()
@IsOptional()
@IsPositive()
readonly page: number;
```

**Comment by parsaghk** [comment]
You can use `@Transform` decorator.

`
@Transform((params) => params.value || DefaultValue, { toClassOnly: true })
`

**Comment by chacha95** [comment]
@parsaghk 
I just try to `@Transform((params) => params.value || 1, { toClassOnly: true })` but result is same
it cannot catch default value!

> code
```ts
  @ApiPropertyOptional()
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @IsPositive()
  @Transform((params) => params.value || 1, { toClassOnly: true })
  readonly page: number;
```
> error message
```
Query parameter "page" with value "undefined" was resolved as "NaN", please validate your query input! Falling back to default "1".
```

**Comment by s-montigny-desautels** [comment]
@jinhyuckcha You need to use the `@Expose` decorator. Otherwise, the `@Transform` decorator is never called.

**Comment by diffy0712** [comment]
Hello, @chacha95,

you can use the `@Transform` solution mentioned above or use the `exposeDefaultValues` option on your `plainToInstance` call and add default values to your properties as usual in classes.
