### ISSUE TITLE
Provide a default value when doing plainToClass

### ISSUE THREAD

**Issue by kirillgroshkov** [typestack/class-transformer#129]
I have a class:

```typescript
class A {
  a: string = '123'
}
```

When I do `plainToClass(A, {})` it returns me an object where `a` is undefined.

What I expect is to be able to provide default value to properties. It can be whatever syntax, not necessary the one that I shown. E.g if I do just `new A()` then I will have the desired `a === '123'`.

Maybe there is some decorator or other way that I'm missing?

**Comment by guscastro** [comment]
IMO, this is something that should happen by default. If there's a default value set on the target class, don't override it with `undefined`. This is standard behaviour in serialisation libraries I've worked with in the past.
In the meantime, you could work around it with the `Transform` decorator.
```
class A {
  @Transform(value => value || '123', { toClassOnly: true }) 
  a: string
}
```

**Comment by kirillgroshkov** [comment]
@guscastro Thanks for the workaround, I think it will work for my case!

I agree that what I described is kind of `default behaviour` that everyone would expect. So, would be nice to maybe have a specific decorator for that, e.g

```javascript
@Default('123')
a: string
```

**Comment by NoNameProvided** [comment]
Yeah, we can have a `@Default` decorator. This needs co-op with class-validator.

**Comment by krazar** [comment]
Is the workaround given by @guscastro is supposed to work ? 
model.a is still undefined  on my side.

``` typescript
const json = {};
class A {
    @Transform(value => value || "123", { toClassOnly: true })
    a: string;
}
model = plainToClass(A, json);
```

What am I missing ?

**Comment by krazar** [comment]
Ok, it seems that I have to add the @Exposed decorator to the field for it to be picked as key.
Is it supposed to be the default behavior ?

**Comment by otomeskhy** [comment]
Any update on this one? Would be lovely to have @Default decorator...

**Comment by NoNameProvided** [comment]
The solution should be as @guscastro noted: 

> IMO, this is something that should happen by default. If there's a default value set on the target class, don't override it with `undefined`.

**Comment by zenozen** [comment]
Vote for this. There's a corresponding issue in class-validator (https://github.com/typestack/class-validator/issues/177)

**Comment by jbjhjm** [comment]
@jbdemonte 's solution has an issue when used with non-simple data types.
For example if using @Default([]) to initiate an array, all instances would share the same array.
To prevent this, I extended his solution to (flatly) copy array and object values, or to use a function returning some value.

```ts
export function Default(defaultValue: any) {
	return Transform((value: any) => {
		if (value !== null && value !== undefined) return value;
		if(typeof defaultValue==='function') return defaultValue();
		if(Array.isArray(defaultValue)) return [...defaultValue];
		if(typeof defaultValue==='object') return {...defaultValue};
	});
}

@Default([])
@Default({})
@Default(()=>return {...data...} as SomeComplexDefaultValue )
```

**Comment by LuudJanssen** [comment]
If you already have `lodash` installed, @jbjhjm's answer can be written as:

```typescript
import { Transform } from 'class-transformer'
import { cloneDeep } from 'lodash'

export function Default(defaultValue: unknown): PropertyDecorator {
  return Transform((value: unknown) => value ?? cloneDeep(defaultValue))
}
```

**Comment by NoNameProvided** [comment]
There is some related work in #381.

**Comment by Goodluckhf** [comment]
I think it should work without any decorators, because we have in js/ts everything for this. IMHO this is a bug

**Comment by NoNameProvided** [comment]
The feature has been merged, will be released with the next version.
