### ISSUE TITLE
Infer types from Typescript instead of explicitly declaring

### ISSUE THREAD

**Issue by kirillgroshkov** [typestack/class-transformer#130]
It's probably a not very easy thing to do, but ultimately it would be great to utilize Typescript typings instead of explicitly declaring validation types.

Instead of:
```javascript
@IsString()
a: string
```

Just:
```javascript
a: string // @IsString() inferred, also @IsDefined inferred

b?: string // @IsString(), @IsOptional inferred from "?"
```

I was able to achieve that in a long way, by:
1. Using https://github.com/YousefED/typescript-json-schema during build step to generate json schemas, that know about types, also if fields are required or not, and some more things.
2. Use json-schema validator in runtime (there are many) that consume schema generated in step 1 and give validation errors.

Result is that I have type and required/optional validation "inferred" from Typescript.

Any ideas how to achieve that with `class-transformer`, to utilize the beauty of @Annotations (to combine inferred types with custom annotations and use all other features of `class-transformer`).

**Comment by NoNameProvided** [comment]
You mean we should auto-convert values? Example:

```ts
class Test {
  x: number;
}

const instance = plainToClass(Test, { x: '5' });

// instance.x should be a number?
```

**Comment by kirillgroshkov** [comment]
Maybe I'm mixing `class-transformer` and `class-validator` functionality in one, but what I meant is that it should give a validation error.

**Comment by NoNameProvided** [comment]
> Maybe I'm mixing class-transformer and class-validator functionality in one, but what I meant is that it should give a validation error.

Yes, it seems you mix the two, class-transformer, doesn't check anything about the type of the data in the properties, it's simply tries to convert it into the target type. Throwing a validation error is the job of class-validator. 

So for exapmle a property with the signature of `@SomeDecorator() prop: number` recieves a `null` value, then it will simply call `Number(null)` (which will become `0`) and doesn't validate if the recieved value is a valid number or not. 

> It's probably a not very easy thing to do, but ultimately it would be great to utilize Typescript typings instead of explicitly declaring validation types.

It is impossible to do without any decorator attached to the property becaus Typescript generates runtime type information only for properties which has at least one decorator. So it doesn't needs to be our decorator, but it needs to have at least one decorator. This implicty type infer will work in this lib once #191 gets merged.

I will go ahead and close this, but let me know if you have any more question and I will re-open.
