### ISSUE TITLE
question: Is it possible to rename property when I use @Transform

### ISSUE THREAD

**Issue by ymolchaniuk** [typestack/class-transformer#1304]
I wan't to rename property when it will be returned to client, for example I have 
`export class A {
  @Transform(({value})=>4)
  t: string;
}`
I need to rename t when it will be converted to json and recieve: 
`{
 b: 4
}`

**Comment by sleeyax** [comment]
I'm no expert or maintainer of this project but I don't think it's possible. You can rename properties via the `Expose` decorator.

I'm using Nest.JS so I solved this by combining both `Transform` and `Expose` decorators into one. For example:
```ts
import { applyDecorators } from '@nestjs/common';
import { Expose, Transform } from 'class-transformer';

export function TransformToHex(options?: { primary: boolean }) {
  return applyDecorators(
    Transform(
      ({ value }) => {
        return value.toHexString();
      },
      { toPlainOnly: true },
    ),
    Expose({ name: options?.primary ? 'id' : undefined, toPlainOnly: true }),
  );
}

```

**Comment by diffy0712** [comment]
Hello @ymolchaniuk,

you can use @sleeyax approach, or  if your name does not need to be dynamic then you can create a getter and expose it:
```typescript
@Expose()
get b() {
 return 4;
}
```

**Comment by diffy0712** [comment]
Closing as answered. If you have any questions left feel free to comment on this issue.
