### ISSUE TITLE
Date Format?

### ISSUE THREAD

**Issue by jasperblues** [typestack/class-transformer#133]
Excellent library, thank you. Is date conversion based on ISO8601 format? Is it possible to specify that? 

Another library that I used had `@DateLong` for unix/epoch format and `@Date` for ISO8601 format.

**Comment by jasperblues** [comment]
Also interested to know if there's a convenience method to use to convert a single instance (other than `const request: EmailCampaign = plainToClass(EmailCampaign, [req.body])[0]`). Didn't see a reference to that in the docs.

**Comment by NoNameProvided** [comment]
> Is date conversion based on ISO8601 format? Is it possible to specify that?

Date conversion basically just create a new Date from the value via `new Date(value)`, so passing the value as an ISO8601 string is the only reliable option.

If you want some custom solution you can use the `@Transform` decorator to specify how you want to transform specific properties. An example: 

```ts
import { yourCustomParser } from '@root/utils'; 

class Example {
 @Transform(value => yourCustomParser(value))
 date: Date
}
```
