### ISSUE TITLE
question: API Versioning wrong?

### ISSUE THREAD

**Issue by FireRedDev** [typestack/class-transformer#1405]
Hello! Patch- and Minor-Versions are intended to be backwards compatible afaik. However, https://github.com/typestack/class-transformer/blob/master/CHANGELOG.md shows Minor-Versions with lots of breaking changes. Is this because its pre Version 1.0? Am i missunderstanding the npm versioning?

**Comment by ElPerenza** [comment]
In the [Semver spec](https://semver.org/), major version 0 is defined like this:

_Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable._

So I would say that class-transformer does have correct versioning.

**Comment by FireRedDev** [comment]
I was unaware of this difference in version 0, thank you

Pietro Perenzoni ***@***.***> schrieb am Mi., 8. März 2023,
12:33:

**Comment by diffy0712** [comment]
Closing this issue, because @ElPerenza have answered it.
