### ISSUE TITLE
question: Is this repository still maintainable?

### ISSUE THREAD

**Issue by NarHakobyan** [typestack/class-transformer#1425]
Hi, I was wondering if this repository is still being maintained. I noticed that there haven't been any updates in a while, and I'm using this library in many project also we are actively using Nest.js. However, I want to make sure that it is still maintained and supported before I proceed.

If this repository is no longer being actively maintained, I would be interested in taking over maintenance and development of the library. I have experience with the technologies used in this library and would be committed to maintaining and improving it.

Could you please let me know if this repository is still actively maintained, and if not, if you would be interested in transferring ownership to me? If not, do you have any recommendations for similar libraries that are still being maintained?

Thanks in advance for your help.

**Comment by gterras** [comment]
Hi see here https://github.com/typestack/class-validator/issues/1775
