### ISSUE TITLE
Custom @Transform functions are passed plain objects during classToPlain()

### ISSUE THREAD

**Issue by zed0** [typestack/class-transformer#143]
When using `classToPlain()` with a `@Transform` decorator the transformation function is passed a plain object rather than the class it originally was.  This can be annoying if one wants to call a function on the class as part of the transformation.

Example:

```
import {classToPlain, Transform, Type} from "class-transformer";

class Bar {
  constructor(
    public inner: string
  ) {
  }
  
  toString() {
    return this.inner;
  }
}

class Foo {
  @Type(() => Bar)
  @Transform((value, obj, type) => {
    console.log('Passed as "value"', value); // Logs plain object
    console.log('Passed inside "obj"', obj.bar); // Logs class
    return value.toString();
  }, {toPlainOnly: true})
  bar: Bar = new Bar('testString');
}

const foo = new Foo();

const plainFoo = classToPlain(foo);

console.log('Original class:', foo);
console.log('Plain object:', plainFoo); // Logs {bar: "[object Object]"}
```
Link: https://plnkr.co/edit/MKCcMFGxhZraSdrFoYsr?p=preview

In this example we wanted to use the `toString()` on the class to provide our transformed value, but instead ended up with `"[object Object]"`.

It is possible to work around this issue by replacing `return value.toString();` with `return obj.bar.toString()`, however it is tedious since you have to know which field of the parent object you are using, and makes passing a generic transform function impossible.

**Comment by driccio** [comment]
Hello all,

I'm asking the same question. I don't understand why the object (class) is transformed to a basic plain object before to be passed to our transform function. As zed0 said it cause trouble when we need to call specific method on our object.

Please, can you tell us you plan to fix that ? Or if there is a workaround ?

Thanks,

Damien

**Comment by WangZishi** [comment]
I'm facing the same problem here.  @pleerock @NoNameProvided

**Comment by MTschannett** [comment]
This seems fixed. Closing this issue
