### ISSUE TITLE
question: <your-title-goes-here>

### ISSUE THREAD

**Issue by hshahi** [typestack/class-transformer#1436]
Hi,

Was trying to use your method when trsansform to array Like:
MyClass {
}

MyClassCollection extends Array<MyClass> {

    giveME2ndItem() {}
}

in the map after getting json from angular httpclient.get(), the plainToInstance(MyClassCollection, jsonObject) return type
doesnt resolve to MyClassCollection but to MyClass[] and it is not easilty casted to MyClassCollection  due to strictness of Angular and  typescript so that I can call the method of the collection.

So how is the mapper can be use to get this scenario

Thanks
shahi

**Comment by kanghoon-dev** [comment]
you should add(edit...?) a title on your question.

**Comment by diffy0712** [comment]
The issue does not contain a simple reproduction case.

Closing as invalid.
