### ISSUE TITLE
question: I'm trying to convert a model using plainToInstance and it's not returning an undefine property even though I'm passing the correct value

### ISSUE THREAD

**Issue by thiago-js** [typestack/class-transformer#1457]
**I'm trying to convert a model using plainToInstance and it's returning an undefined property even though I'm passing the correct value**

method:
![image](https://user-images.githubusercontent.com/12818093/219974922-8579b4e9-8504-4b04-8b59-a6dfc5098565.png)

correct return probabilities:
![image](https://user-images.githubusercontent.com/12818093/219974991-01897f60-24de-4b5c-b5c2-2f79c42ed633.png)

after convert planToIntance/planToIntance 
![image](https://user-images.githubusercontent.com/12818093/219975126-c13a1174-a710-4860-9c29-480fd7dd6894.png)

the field probability is undefined, but the payload is correct has a value !!

DTO:
![image](https://user-images.githubusercontent.com/12818093/219975218-6ea6b000-20cf-41a4-9067-c6d76c04f666.png)

![image](https://user-images.githubusercontent.com/12818093/219975230-35c90e20-9064-42fa-8e7b-fcc5d9648b67.png)

I don't know what I'm doing wrong or I think I got a bug, when a property is inside an array

I'm using, serverless with node + typescript

node: v16.16.0
serverless: 
  Framework Core: 3.24.1
  Plugin: 6.2.2  
  SDK: 4.3.2
 
these are my dependencies:

![image](https://user-images.githubusercontent.com/12818093/219975405-9647aa21-76c8-4150-8a15-638efa5677b4.png)

**Comment by mrbrunelli** [comment]
Hi @thiago-js.

Try to import `reflect-metadata` in your file:

```typescript 
import "reflect-metadata";
```

Look this example: https://github.com/mrbrunelli/class-transformer-example/blob/main/src/type.spec.ts

**Comment by diffy0712** [comment]
Hello @thiago-js,
on your second image it is visible that your api response contains 'probalility', so the problem is just a typo.
