### ISSUE TITLE
Exclude() isn't working for HTTP POST responses

### ISSUE THREAD

**Issue by kodayashi** [typestack/class-transformer#146]
I'm using class-transformer in a NestJS project with TypeORM. I have configured the classToPlain() method to run for every single API response in NestJS with what they call an "Interceptor":

```typescript
@Interceptor()
export class TransformInterceptor implements NestInterceptor {
  intercept(dataOrRequest, context: ExecutionContext, stream$: Observable<any>): Observable<any> {
    return stream$.map((data) => classToPlain(data));
  }
}
```

My User entity looks like this:

```typescript
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';
import { Exclude } from 'class-transformer';

type Gender = 'm' | 'f';

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({ unique: true })
    email: string;

    @Exclude()
    @Column({ length: 100 })
    password: string;

    @Column({ nullable: true })
    firstName: string|undefined;

    @Column({ nullable: true })
    lastName: string|undefined;

    @Column({ type: 'date', nullable: true })
    dob: Date|undefined;

    @Column({ name: 'gender', type: 'enum', enum: ['m', 'f'], nullable: true })
    gender: Gender|undefined;

    @Column({ nullable: true })
    phoneNumber: string|undefined;
}
```

It's working great except for when I *create* a new User. Calls to get all users or get one user results in the password being excluded. But for some reason when I create a new user with an http `POST`, the response includes my hashed password:

```javascript
{
    "email": "tester016@test.com",
    "firstName": null,
    "lastName": null,
    "dob": null,
    "gender": null,
    "phoneNumber": null,
    "id": 20
}
```

Does `Exclude()` not work when creating new resources?

**Comment by NoNameProvided** [comment]
Hi @kodayashi! 

Have you checked if the `data` is really an instance of `User` when responding to POST requests? I would need some more details, to understand exactly how you experience this issue, but my first thought would be that somehow you end up with a different class or simple object in the interceptor.

**Comment by MTschannett** [comment]
There wasn't a reaction in over a month, I will close this issue because of inactivity.

@kodayashi If you need further help feel free to reopen this issue or create a new one.
