### ISSUE TITLE
question: how to transform a flat object to a nested object ?

### ISSUE THREAD

**Issue by 8naf** [typestack/class-transformer#1479]
I have 3 classes as follows:

```ts
class Server {
	@Expose({ name: 'APP_PORT' })
	@Type(() => Number)
	port: number

	@Expose({ name: 'APP_TAG' })
	@Type(() => String)
	tag: string
}

class Database {
	@Expose({ name: 'DATABASE_PORT' })
	@Type(() => Number)
	port: number

	@Expose({ name: 'DATABASE_NAME' })
	@Type(() => String)
	name: string
}

class Global {
	@Type(() => Server)
	server: Server

	@Type(() => Database)
	database: Database
}
```

I will convert the `plainObject` below into `instance` with the following code:

```ts
const plainObject = {
	APP_PORT: 5000,
	APP_TAG: '1.0.1',
	DATABASE_PORT: 8000,
	DATABASE_NAME: 'test',
}

const instance = plainToInstance(Global, plainObject)
console.log(instance)

```

The returned result is as follows:

```bash
Global {
  server: undefined,   
  database: undefined, 
  APP_PORT: 5000,      
  APP_TAG: '1.0.1',    
  DATABASE_PORT: 8000, 
  DATABASE_NAME: 'test',
}
```

It is not what I expected. I want it to be like this:

```ts
Global {
  server: {
    APP_PORT: 5000,
    APP_TAG: '1.0.1',
  },
  database: {
    DATABASE_PORT: 8000,
    DATABASE_NAME: 'test',
  },
}

```

What adjustments do I need to make to `the 3 classes above` to achieve what I want ?

Additional information is that I temporarily solved it by changing the `plainObject` to the following:

```ts
const plainObject = {
	server: {
		APP_PORT: 5000,
		APP_TAG: '1.0.1',
	},
	database: {
		DATABASE_PORT: 8000,
		DATABASE_NAME: 'test',
	},
}
```
But it is not a "pure" decorator approach.

**Comment by huantaoliu** [comment]
stackoverflow is a better place for this kind of questions
https://stackoverflow.com/questions/73795413/class-transformer-property-that-is-an-object-with-properties-that-is-another-cl/75749108#75749108

**Comment by 8naf** [comment]
@huantaoliu Thank you for responding, but what you provided does not solve my problem. Perhaps you misunderstood the issue, so I have updated my question.

**Comment by bhaugeea** [comment]
I'm pretty sure 8NAF's answer does solve your problem. As that SO answer says, you can use the provided `{ obj }` to access any properties of the whole object to be serialized, not just the property being decorated.

**Comment by diffy0712** [comment]
Hello @8NAF,

You can use [custom transformers](https://github.com/typestack/class-transformer?tab=readme-ov-file#additional-data-transformation) to solve your problem as @huantaoliu's  link to stackoverflow demonstrates.

Closing as answered. If you have any questions left feel free to comment on this issue.
