### ISSUE TITLE
question: How to transform object property with index signature ?

### ISSUE THREAD

**Issue by Maikkiczk** [typestack/class-transformer#148]
Hi everyone,

I actually have a dictionary class who have index signature as key and a Class as value.
How can i actually tell to the library to correctly serialize/deserialize this case ?

```ts
export class ViewDictionary {
  /// Problem here ///
  [key: string]: View;
}

export class View {
  private id: string;
  private name: string;
  @Type(() => SubViewDictionary) 
  private subViews: SubViewDictionary;
}
```

**Comment by MTschannett** [comment]
@Maikkiczk Do you know this keys or are this dynamically added keys?

Another approach to this would be to add a Array of views. So basically this: 

``` 
export class ViewDictionary {
    @type(() => View)
    views: View[];
}
```

**Comment by cojack** [comment]
@Maikkiczk @shishkinilya @MTschannett maybe this article will point some light at this problem https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/

**Comment by NoNameProvided** [comment]
I can reproduce this with the following snipet: 

```ts
import 'reflect-metadata';
import { plainToClass, Type } from 'class-transformer';

export class ListQueryDto {
  readonly limit: number;
}

const tempQuery: ListQueryDto = plainToClass(ListQueryDto, { limit: '100' });
console.log('Modified => ', tempQuery);
```

For now, a quick fix can be to simply specify the expected type explicitly via the `@Type` decorator: 

```ts
export class ListQueryDto {
  @Type(() => Number) 
  readonly limit: number;
}
``` 

But this should not be required and needs to be fixed.

**Comment by olee** [comment]
Did you find any solution for this @Maikkiczk?

**Comment by arvinsingla** [comment]
Also experiencing this problem. Any thoughts on how to solve or alternative approaches?

**Comment by mhthompson86** [comment]
I have a case where I have a class that would look like the following:

```
export class Score {
//  @IsNumber()  <--- would like this to work.  
  [key: number]: number;
}
```

Is there anyway currently to achieve this behavior?

**Comment by NoNameProvided** [comment]
The only was now is using a custom `@Transform` decorator.

**Comment by NoNameProvided** [comment]
We have multiple ways to do this: 
 - use an array as mentioned above
 - use `Map`
 
 I don't think we need some more custom stuff for this.
