### ISSUE TITLE
question: <your-title-goes-here>

### ISSUE THREAD

**Issue by rtarling** [typestack/class-transformer#1488]
**I was trying to...**
import { plainToClass } from "class-transformer";
In a Vue3/Ionic project.

**The problem:**
class_transformer is underlined and I see the message "Cannot find module 'class-transformer'.
However, I can call the plainToClass method and it works fine.
Can you please tell me how to fix this.

**Comment by bhaugeea** [comment]
Can you please at least add a title to your question?

**Comment by diffy0712** [comment]
Closing as invalid. The problem the issue described is not related to this library.
