### ISSUE TITLE
question: `@Expose` decorator  at a class level creates objects with unwanted empty properties

### ISSUE THREAD

**Issue by shusson** [typestack/class-transformer#149]
When `@Expose()` is applied at the class level and `plainToClass` is called with the strategy `excludeAll`, empty properties from the plain object are left over.

e.g 

```ts
@Expose()
export class EntityClassExpose {
  id: string;
}

export class EntityPropertyExpose {
  @Expose() id: string;
}

const blob = {
  id: "fred",
  junk: {
    junk: "junk"
  }
};

const x = plainToClass(EntityClassExpose, blob, { strategy: "excludeAll" });
const y = plainToClass(EntityPropertyExpose, blob, { strategy: "excludeAll" });

console.log(x);
console.log(y);
```

Will print out something like:

```ts
EntityClassExpose { id: 'fred', junk: {} }
EntityPropertyExpose { id: 'fred' }
```
A working example can be found here: https://github.com/shusson/expose-example. 

Is this intended? Is there a way to ensure only the properties in a class are transformed without decorating every property?

**Comment by MTschannett** [comment]
@shusson Thanks for you investigation.

I'm not sure about this.

@bojack Do you know this? Maybe we should add a statement to the documentation.

**Comment by NoNameProvided** [comment]
Hi @shusson! 

class-transformer won't remove any unknown property without asking it to do so, you can go two directions whitelisting, or blacklisting:

```ts
@Exclude() // everything is removed from the object, except the exposed properties
class WhiteListed {
  id: number; // won't exist in the transformed class

  @Expose()
  name: string;
}

// Everything is included except blacklisted properties
class WhiteListed {
  id: number; // it will exist in the transformed class

  @Exclude()
  name: string;
}
```

This is by decision, if you need this for data validation, you can use the whitelisting option in class-validator: 

```ts
import {validate} from "class-validator";
// ...
validate(post, { whitelist: true });
```

This way, class-validator will remove every unknown property.

I will go ahead and close this, if you have any question regarding the topic, please feel free to continue the discussion.

**Comment by shusson** [comment]
@NoNameProvided I'm using the [exclude strategy](https://github.com/typestack/class-transformer#skipping-all-properties-of-the-class)  e.g

```
const x = plainToClass(EntityClassExpose, blob, { strategy: "excludeAll" });
const y = plainToClass(EntityPropertyExpose, blob, { strategy: "excludeAll" });
```

I would expect both x and y to be the same because the only difference is where I placed the `@Expose` decorator.  One is at the class level, the other is at a property level.

**Comment by MTschannett** [comment]
Sure. If you want to help to fix this. Feel free to open a PR.

For now a workaround is the method mentioned by @NoNameProvided.

But i think this is not a ideal solution

**Comment by m-nikhil** [comment]
@NoNameProvided , Willing to work in this bug. Need help here, what would be perfect approach.

**Comment by greenreign** [comment]
I have also observed this issue.  Using `@Expose` at the class level seems to do nothing.  Is it expected to do something?

**Comment by NoNameProvided** [comment]
> Is this intended? Is there a way to ensure only the properties in a class are transformed without decorating every property?

This is intended or more likely a limitation of how JS works. The library cannot know what properties a class has without being decorated with a decorator. Eg:

```ts
class MyExampleClass {
  public someProperty!: string;
}

const instance = new MyExampleClass();
// inteliSense sees instance.someProperty and you can set it but
console.log(Object.keys(instance));
// returns [] when the key is not set to a concrete value 
// if we set some value to it we will see the key, but not before
```

**Comment by NoNameProvided** [comment]
I also checked and actually `excludeAll` is never used anywhere in the code ironically, so this never worked. I will probably deprecate it, but I will sleep one on it before.
