### ISSUE TITLE
Class with nested types returning nested property name: undefined when undefined JSON is being parsed

### ISSUE THREAD

**Issue by airowe** [typestack/class-transformer#1495]
**I was trying to convert JSON to a Class Instance, but have an undefined value if the JSON being parsed was undefined**

```
export class Profile {
  email?: string;
  @Type(() => Membership)
  membership?: Membership;
}

export class Membership {
  id?: string;
}

const json = undefined;
const profile = plainToInstance(Profile, json);
```

**The problem:**
I would expect the above to result in the profile const being undefined, but it is being represented like so:

`{"membership": undefined}`

Is there a way to have `plainToInstance` return undefined for a top level object that contains nested types if the json being passed to it is undefined?

**Comment by diffy0712** [comment]
Hello @airowe,

with the example you provided I correctly got `undefined` as value of `profile`.
Could you please help to reproduce your problem?

**Comment by airowe** [comment]
> Hello @airowe,
> 
> with the example you provided I correctly got `undefined` as value of `profile`. Could you please help to reproduce your problem?

Not sure honestly, this was over a year ago.
