### ISSUE TITLE
ArrayType bug?

### ISSUE THREAD

**Issue by kodeine** [typestack/class-transformer#15]
hello,
i've started to get this error, i've upgraded to `class-transformer`

`/project/node_modules/class-transformer/index"' has no exported member 'ArrayType'.`

also, why do i get error on this code,

``` ts
private user:User;
...
this.user = <User>plainToClass(User, data);
```

`Error TS2352: Neither type 'User[]' nor type 'User' is assignable to the other.`

**Comment by pleerock** [comment]
hello, what is type of `data`. Is it a single object or an array?
you should do it like this:
`this.user = plainToClass(User, data as Object);`- if data is a single object
`this.user = plainToClass(User, data as Object[]);`- if data is an array

**Comment by pleerock** [comment]
and btw there is no `ArrayType` anymore. `Type` does the same thing now

**Comment by kodeine** [comment]
@pleerock okay this works `this.user = <User>plainToClass(User, data as Object);`
so do you suggest i remove `<User>`?
also since im new to typescript, `data as Object` is typescript method or class-transformer?

**Comment by pleerock** [comment]
yes, you should remove <User> since plainToClass already returns you instance of a User class. Also check this.user.* without <User> - autocomplete should work

**Comment by blackmamo** [comment]
The documentation does need updating if ArrayType no longer exists

**Comment by MTschannett** [comment]
I close this because the documentation seems fixed. Please reopen a issue if it's not correct
