### ISSUE TITLE
question: How to serialize a class instance with default values automatically removed?

### ISSUE THREAD

**Issue by ahochsteger** [typestack/class-transformer#1505]
**I was trying to...**
I have a large config class in TypeScript with a lot of default values defined in the class (e.g. empty strings, some boolean values, empty arrays) that I want to serialize back to a minimal JSON representation that just contain the essential part of the config with all properties removed that have values identical to their defined default values.

**The problem:**
How can I do that in a generic way by just using the information that is available from the class definition without having add extra annotation to these properties?

**Comment by diffy0712** [comment]
Hello @ahochsteger,

could you please provide an example for your question? If I understand correctly, there is no option for what you want, but I cannot say it for sure without an example.

Thanks

**Comment by ahochsteger** [comment]
@diffy0712 have a look at this commented-out test case that is currently failing:
https://github.com/ahochsteger/gmail-processor/blob/main/src/test/environment/class-transformer.spec.ts#L182-L192
```typescript
// See the source for the class definitions
it("should serialize to JSON config without default values", () => {
  const obj = getNewRootObj(jsonData)
  const actual: any = instanceToPlain(obj, {
    exposeDefaultValues: false,
    exposeUnsetFields: false,
  })
  expect(actual).toMatchObject(jsonData) // <- this is OK
  expect(actual.str).toBeUndefined() // <- this is failing
  expect(actual.nested?.num).toBeUndefined() // <- this is failing
  expect(actual.nested?.bool).toBeUndefined() // <- this is failing
  expect(actual.nestedArray[0]?.bool).toBeUndefined() // <- this is failing
  expect(actual.nestedArray[0]?.arr).toBeUndefined() // <- this is failing
})
```

It looks like it's the same as this issue: #1609

**Comment by diffy0712** [comment]
hello @ahochsteger,
Yes it seems that it is the same problem as https://github.com/typestack/class-transformer/issues/1609.
if you use `exposeUnsetFields:false` and `exposeDefaultValues:false` together it does not work as expected.

Closing this issue in favor of https://github.com/typestack/class-transformer/issues/1609, please follow the bugfix there.
