### ISSUE TITLE
question: why does @Type(() => Boolean) is intended to always return true?

### ISSUE THREAD

**Issue by kanghoon-dev** [typestack/class-transformer#1506]
**I was trying to...**
get a query string (which is intended to be a boolean value) and transform/validate if it is valid boolean value using class-transformer in NestJs.

**The problem:**
I found that using
`@Type(()=>Boolean)`
makes always `True` as boolean transformed value except for the query string like
`http://localhost:3000?key`.

In #534 and #676 , I got how to make it work properly and the behavior above is intended.
I just want to know **why the behavior is intended**. Is it related to the characteristic of JS/TS type check?

**Comment by Ramazon-hub** [comment]
I think It doesn't return only true

**Comment by kanghoon-dev** [comment]
> I think It doesn't return only true

Can you describe the condition where it does return false? 

In my usage, It always returned true even if I gave `key=false`.

**Comment by diffy0712** [comment]
Hello @hoon5083,

This works as expected. Any non-empty string value is transformed to boolean true by Javascript.
You can force the 'correct' behavior, that you expect with a [custom transformer](https://github.com/typestack/class-transformer?tab=readme-ov-file#additional-data-transformation).
Example:
```
@Transform(({ value }) => {
  if (value === 'true') return true;
  if (value === 'false') return false;
  return value;
})
```

There is a feature issue on `allow casting of primitive values during transformation` https://github.com/typestack/class-transformer/issues/550.
