### ISSUE TITLE
Underscores on Javascript classes

### ISSUE THREAD

**Issue by FredOleary** [typestack/class-transformer#154]
Hi, Im evaluating class-transformer and it looks great. However our project uses plain JS files, not typescript. So variables declared in the class constructor get prefixed with '_'. Eg 'this.name' creates '_name' The result of this is classToPlain creates {_name:xxx } rather than {name:xxx }  Is there anyway to remove these '_' ? (Because its not typescript the @Expose annotation won't work)
Thanks

**Comment by cojack** [comment]
>  (Because its not typescript the `@expose` annotation won't work)

@FredOleary why? Could you explain your problem one more time with better explanation?

**Comment by NoNameProvided** [comment]
Hi @FredOleary, to make it work, you will need to add support for decorators via the Babel [decorator plugin][1].

[1]: https://babeljs.io/docs/en/babel-plugin-syntax-decorators

**Comment by NoNameProvided** [comment]
I will go ahead and close this question, but feel free to continute the conversation if you have any more question.
