### ISSUE TITLE
feature: Add tags to include/exclude fields conditionally at a more global level

### ISSUE THREAD

**Issue by lmexo** [typestack/class-transformer#1543]
### Description
We use class-transformer with nest.js and typeORM. Sometimes we have use-cases where we want to get the typeORM entity with some relations, but depending on the permission some data _should_ or _should not_ be sent to the client.
There are already groups, but as far as I can see groups can not be used to "exclude" data but are only opt-in.

### Proposed solution
I thought of kind of tags which can be applied to the corresponding properties. E.g. `@Tags('sensitive') emailAddress: string`. Now when using nests class transformer interceptor I could e.g. make sure this data is only included/excluded depending on my role and/or permissions, by adding a the tags to the `classToPlain` options
* as opt-in `{ includeTags: ['sensitive'] }` or
* as opt-out `{ excludeTags: ['sensitive'] }`

**Comment by kurt-west** [comment]
One solution is to define a RespsoneDto class that is returned vs your Entity. Your Entity includes all properties that are required for your business (service) layer to function and then at the controller layer you return a new ResponseDto(bussinessEntity);

Additionally, if your controller has access to your user's permissions/role, you can choose which RepsoneDto is returned  - UserResponseDto, AdminUserResponseDto, etc. 

I'm believe this would work with the out-of-the-box Nest ClassSerializerInterceptor; I use a custom serialization interceptor that blocks a plain object response.

**Comment by lmexo** [comment]
I am aware of that, but sometimes it produces more code than necessary since there is only one single member which changes which makes me doing class inheritance and consequently another file and so on... Since the tags are already available I thought it should be easy to add this include/exclude tags feature...

**Comment by diffy0712** [comment]
Hello @lmexo,

What would a 'tag' do that you are unable to solve with `groups`?

If you could phrase your proposal in a simple example (without TypeORM, nestjs or other frameworks and libraries) that would help to understand you problem. As not everyone is familiar with TypeORM or nestjs.

Thank you.

**Comment by lmexo** [comment]
Good question... I think at the time of writing I especially was looking for a mechanism to opt-out certain groups, which I did not find. I guess the `@Expose({ group: 'admin' })` (= "expose only if group is admin") decorator would also work the other way around, e.g `@Exclude({group: 'admin'})` (= "exclude only if group is admin")? If I am right, this should be mentioned in the docs :)

**Comment by diffy0712** [comment]
Hmm, I see, the docs might need to be updated a bit to include Exclude examples as well.
I know it's been a long time since you made this issue, so is this still relevant for you?

**Comment by lmexo** [comment]
Since I now know about the Exclude group, I guess this one is obsolete.
