### ISSUE TITLE
question: is this repo abandoned?

### ISSUE THREAD

**Issue by stasgm** [typestack/class-transformer#1546]
There are no new commits for a long time, the last release was 2 years ago. 
Pull requests have been hanging around for years. 
No development at all

**Comment by whgoss** [comment]
I was wondering the same. There are outstanding bugs and major issues that have yet to be addressed.

**Comment by RonRofe** [comment]
So strange what's going on here.
This package is owned by the the same creators of class-validation which requires class-transformer for many cases.
"class-validator" is fully maintained but they just ignore "class-transformer".
What's even more crazy is that NESTJS relays on this package which is not maintained.

**Comment by flowluap** [comment]
@dartdevdave

**Comment by stasgm** [comment]
@RonRofe I wouldn't say that "class-validator" is fully maintained. One release a year is not the best way to give people what they need. For example, many issues have been fixed in the dev branch, but we will see them, perhaps at the end of this year.

**Comment by kddsultan** [comment]
The same here. Overall the project is really useful. That would be pity

**Comment by kddsultan** [comment]
@NoNameProvided / @jotamorais , any comments on this topic?

**Comment by ddbtrmatic** [comment]
https://github.com/typestack/class-validator/issues/1775
