### ISSUE TITLE
feature: Allow support for multiple nested object

### ISSUE THREAD

**Issue by joker349** [typestack/class-transformer#1549]
### Description

We have a response object, which is sent to us from multiple providers and thus they their response structure is different.
Currently, this library does not support multiple TypeScript Interfaces (see example below for the problem).

### Proposed solution

Add feature to support multiple nested objects.

#### Sample code

```
class ResponseType1 {
  @Expose()
  firstName?: string;
}

class ResponseType2 {
  @Expose()
  lastName?: string;
}

// main class
class Data {
    @Expose()
    response: ResponseType1 | ResponseType2;
};

// sample object
const sampleObj = {
  response:  {
    firstName: 'Foo'
  }
};

const data = plainToInstance(Data, sampleObj, { excludeExtraneousValues: true, enableImplicitConversion: true });

console.log(data);
// Data {
//   response: {}
// }
```

##### Expected result

```
Data {
   response: {
      firstName: 'Foo'
  }
}
```
---
Please let me know if you need some more information 🙋🏻‍♂️
Thanks for creating and maintaining this library 🙏🏻

**Comment by diffy0712** [comment]
Hello @joker349,

could your problem be solved with `discriminator`? [Read more here](https://github.com/typestack/class-transformer?tab=readme-ov-file#providing-more-than-one-type-option).
This could only work if you have some discriminator type on your json (maybe you could attach one before calling `instanceToPlain`).

In the example you provided, I do not see a clear solution for the library to find, which `type` to use.

**Comment by diffy0712** [comment]
Closing as answered. If you have any questions left feel free to comment on this issue.
