### ISSUE TITLE
question: Does CT support the Regular expression content ?

### ISSUE THREAD

**Issue by johnvanderton** [typestack/class-transformer#1577]
I was wondering if the library is able to handle class properties which are containing regular expression during serialization/deserialization ? AI (ChatGPT) was telling me that's not (yet) the case, sorry if I've misunderstand or missed something.

Any help ?

**Comment by johnvanderton** [comment]
Here is the suggested getter/setter fix code from AI, idk if this is relevant in this case ?

```
import { Expose, plainToClass, classToPlain } from 'class-transformer';

class ExampleClass {
  @Expose()
  name: string;

  @Expose()
  regex: RegExp;

  constructor(name: string, regex: RegExp) {
    this.name = name;
    this.regex = regex;
  }

  // Custom serializer for regular expression property
  @Expose()
  get regexString(): string {
    return this.regex.source;
  }

  // Custom deserializer for regular expression property
  set regexString(value: string) {
    this.regex = new RegExp(value);
  }

  static fromJSON(json: string): ExampleClass {
    return plainToClass(this, JSON.parse(json));
  }

  toJSON(): string {
    return JSON.stringify(classToPlain(this));
  }
}
```

**Comment by diffy0712** [comment]
hello @johnvanderton,

I am not sure what do you mean. Could you please provide an example snippet on what you would like to do with 'class-transformer`?

**Comment by diffy0712** [comment]
Closing as invalid, because of inactivity. If you have any questions left feel free to comment on this issue.
