### ISSUE TITLE
question: classToPlain( ) content is showing 

### ISSUE THREAD

**Issue by johnvanderton** [typestack/class-transformer#1578]
I'm doing my own library stuff and trying to serialize it a bit. Here's one of my class property and especially with the `SPC` subtype,

````
   @Expose()
    @Type(() => DomElement, {
        discriminator: {
            property: '__type',
            subTypes: [
              { value: NavPane, name: 'navpane' },
              { value: SPC, name: 'spc' },
            ],
          },
    })
    private _doms : DomElement[] | NavPane[] | SPC[] = new Array<DomElement>();
````

...and here's what i'm having after a `plainToClass()` : 

````
    {
      _element: '',
      _signature: '',
      DOM_VALIDATION_FILTER_SELECTOR_MIN_PARAMETERS_VALUE: 2,
      NUMBER_ARGUMENTS_FILTER_SELECTOR_MAX_VALUE: 3,
      _filterselectorsignature: 'Scope2 Parent2 Child2',
      _siblings: [Array],
      type: 'spc'
    }
````

the `_siblings` field is only showing the `[Array]` value instead of a nice json string. Did I miss something ?

**Comment by diffy0712** [comment]
Hello @johnvanderton,

could you please provide more information to reproduce this?

**Comment by johnvanderton** [comment]
Hello, the `_siblings` field was well identified as an [Array] type by `class-transformer`, but I never managed to reach the content... So, I've decided to implement my own mapper. Unfortunately, all the previous code was then replaced.

**Comment by diffy0712** [comment]
I am sorry to hear that.
I think this issue can be closed then.

Thank you for replying :)
