### ISSUE TITLE
Project status (add maintainers?)

### ISSUE THREAD

**Issue by weeco** [typestack/class-transformer#159]
**The issue:**
There are 18 pull requests now, some of them fix bugs, significantly improve performance or simply improve the Readme. I consider some of these (e. g. https://github.com/typestack/class-transformer/pull/137) as quite important to merge. They have written tests, got a review and feedback as well. This fairly small pull request has been submitted 3 months ago and yet it hasn't been merged.

**Suggestion:**
This library is awesome and I still use it in new projects, however it is in need of maintenance. Could you add maintainers or give it a little more attention?

**Comment by jcudzich** [comment]
@pleerock is the creator of this library, but is mainly involved in the development of TypeORM. I think the class-transformer does not have any dedicated maintainers now.

**Comment by pleerock** [comment]
sorry guys but I don't have that much hands to maintain them all.

I would really appreciate if someone can take responsibility on this one. I remember last time @NoNameProvided wanted to do that, but not sure if he found enough time for it.

Please let me know if you want to maintain it with responsibility in a long term.

**Comment by lordazzi** [comment]
This is a very important project, would be nice if there was a maintainer at least for bugfix or for pull request code review

**Comment by pleerock** [comment]
yes but as you can see noone is taking a responsibility

**Comment by MTschannett** [comment]
I would like to maintain this project. But I don't have any real expirience in maintaining such a big project.  
But I think with a little starting help this shouldn't be a problem. 

I'm using this library in a few projects and really like it. I would be happy to help maintaining this project.

**Comment by NoNameProvided** [comment]
Yeah, I am short on time nowadays, I hope I can get some time soon, but I can't give any promises.

**Comment by MTschannett** [comment]
ping @NoNameProvided  @pleerock

**Comment by rmuchall** [comment]
I would be happy to join the contributors group :)
I'm using TypeStack across multiple projects.

**Comment by ahmadhsalim** [comment]
@pleerock I need some of those pull requests merged asap. If there's no one then I'm willing to maintain this project.

**Comment by nolazybits** [comment]
@pleerock I agree with @weeco and it seems there are at least 2 people keen to help. That would be awesome if we could see some movement :)

**Comment by weeco** [comment]
@pleerock Still no update :(

**Comment by MTschannett** [comment]
@pleerock I'd still like to help if you could give me access

**Comment by YGKtech** [comment]
Hmm, I was considering working on a PR to fix a compatibility issue I found with some key classes used in FireBase, but if there's nobody maintaining the project it's probably not worth my time to set something up right now.

**Comment by MTschannett** [comment]
@NoNameProvided @pleerock could we please add some maintainers? I'd happy be to start working on this project..

**Comment by NoNameProvided** [comment]
Status update: I will take a look this week at the PRs and also release a new routing-controllers version with these changes.

**Comment by weeco** [comment]
@NoNameProvided as requested I did a pre review and also tested it in a production environment, still this PR hasn't been merged yet:

https://github.com/typestack/class-transformer/pull/137

This project needs a fork or new maintainers.

**Comment by MTschannett** [comment]
@weeco if you want to help we could both maintain that fork. 

I guess there won't be added new maintainers in the near future..

**Comment by cojack** [comment]
@MTschannett @weeco @NoNameProvided @YGKtech how about just fork it, rename it and go forward?

**Comment by MTschannett** [comment]
@cojack Sounds good to me . But i want at least a second maintainer. Otherwise we have this drama again.

Would you like to help?

**Comment by cojack** [comment]
@MTschannett @weeco @NoNameProvided @YGKtech wait before fork, I wrote to https://github.com/19majkel94 he is one of the ppl in organization, maybe he will add us as a maintainers if don't, then we will fork it.

**Comment by MTschannett** [comment]
@cojack I'm ok with this . This is also my preferred way.

**Comment by 19majkel94** [comment]
@cojack 
Unfortunately, I'm only a member, not an owner, so I'm not capable of adding new peoples:
![image](https://user-images.githubusercontent.com/10618781/47265205-8adbce00-d524-11e8-9a7c-fb76e30f6b54.png)

You should contact with @pleerock by mail or maybe by a PR on TypeORM's slack:
https://join.slack.com/t/typeorm/shared_invite/enQtNDQ1MzA3MDA5MTExLTFiNDEyOGUxZGQyYWIwOTA0NDQxODdkOGQ0OTUxNzFjYjUwY2E0ZmFlODc5OTYyYzAzNGM3MGZjYzhjYTBiZTY

**Comment by cojack** [comment]
Thanks @19majkel94 for so fast response, I ping @pleerock directly on the slack of TypeORM, we will se if he will respond anyhow.

**Comment by cojack** [comment]
Done, @pleerock gives me a access, so I'm now one of the two collaborators.
@MTschannett @weeco @NoNameProvided @YGKtech  where now?

**Comment by MTschannett** [comment]
Thank you. I've accepted it already. I'm glad we can start working on this.

**Comment by cojack** [comment]
@MTschannett so Im trying to handle the issues, if you could help to solve them or close some, I will be glad.

**Comment by MTschannett** [comment]
Yes I got notified. I'll start working on the issues this afternoon

**Comment by MTschannett** [comment]
@cojack can we close this for now?

**Comment by cojack** [comment]
@MTschannett why not, if anyone else wanna to join, please write here and call @MTschannett and me ;)
