### ISSUE TITLE
fix: Transform is not called for fields not passed in request body

### ISSUE THREAD

**Issue by rohitkhatri** [typestack/class-transformer#1599]
### Description

I am trying to add a field to request payload before validating using Transform, but It's not executed if the field is not present in the request payload

**Code**
```ts
import { ApiProperty } from "@nestjs/swagger";
import { IsNotEmpty, IsString } from "class-validator";
import { Transform, TransformFnParams } from "class-transformer";

export class ReqDTO {
    @ApiProperty({})
    @Transform(({ value }: TransformFnParams) => value?.trim())
    @IsString()
    @IsNotEmpty()
    first_name: string;

    @ApiProperty({})
    @Transform(({ value }: TransformFnParams) => value?.trim())
    @IsString()
    @IsNotEmpty()
    last_name: string;

    @ApiProperty({ readOnly: true })
    @Transform(({ value }) => {
        console.log('Executing Transformer for testing field:', value);
        return value;
    })
    generated_field: string;
}
```
The transformer is not executing for the below payload, but if passed `generated_field`, It executes.

```json
{
    "first_name": "Rohit",
    "last_name": "Khatri"
}
```

### Expected behavior
The Transform should be executing even if the field is not passed in the request body

### Actual behavior
Transform decorator not executing if field is not passed in the payload

**Comment by JoseJavierSA** [comment]
Same problem here

**Comment by ma-sommer** [comment]
Same problem here - any solution yet?

**Comment by diffy0712** [comment]
Hello @rohitkhatri ,

If you have 'exposeUnsetFields' set to `true` on the `plainToInstance` method call, you can add an additional `@Expose` decorator on top of your property.
In you case:

```
@ApiProperty({ readOnly: true })
@Expose()
@Transform(({ value }) => {
    console.log('Executing Transformer for testing field:', value);
    return value;
})
generated_field: string;
```

Hope this helps.

**Comment by diffy0712** [comment]
Closing as answered. If you have any questions left feel free to comment on this issue.
