### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by theapache64** [typestack/class-transformer#161]
Is this compatible with react native ?

**Comment by MTschannett** [comment]
@theapache64 have you tried using it in react native? I would be keen to know if it works with react native.

Otherwise would someone like to test this and add a PR with changes to our documentation?

**Comment by cojack** [comment]
This library is platform agnostic, so I don't see any obstacles that might stay at your way @theapache64 but if any appear, as @MTschannett wrote :+1:
