### ISSUE TITLE
Expose properties with different name using a callback

### ISSUE THREAD

**Issue by thewebartisan7** [typestack/class-transformer#1611]
### Description
I would like to make a PR to allow pass a function to expose decorator for set different name using a callback. Let me know if you would be interested in this.

### Proposed solution
I am not yet sure the best approach to handle this, but quickly checking source code below could be a solution without introducing regression.

```js
import { defaultMetadataStorage } from '../storage';
import { ExposeOptions } from '../interfaces';

// options type can be a function that return ExposeOptions
export function Expose(options: ExposeOptions |  (() => ExposeOptions) = {}): PropertyDecorator & ClassDecorator {

  if (typeof options === 'function') options = options();

  return function (object: any, propertyName?: string | Symbol): void {
    defaultMetadataStorage.addExposeMetadata({
      target: object instanceof Function ? object : object.constructor,
      propertyName: propertyName as string,
      options,
    });
  };
}
``` 

Or also only the `options.name` become a string or a callback. In this case we change `ExposeOptions['name']` to string or function.

**Comment by diffy0712** [comment]
Hello @thewebartisan7,

before getting into any implementation details, could you please give some details on when would this be useful and what limitations this would solve?

Thank you

**Comment by diffy0712** [comment]
Closing as invalid, because of inactivity.
If you want to continue this discussion, feel free to comment on this issue.
