### ISSUE TITLE
Working with generics

### ISSUE THREAD

**Issue by theapache64** [typestack/class-transformer#162]
> Generics are not supported because TypeScript does not have good reflection abilities yet. Once TypeScript team provide us better runtime type reflection tools, generics will be implemented. There are some tweaks however you can use, that maybe can solve your problem. Checkout this example.

I've checked the example, but couldn't understand anything. Could you please show me a simple example here ?

**Comment by MTschannett** [comment]
This question was answered, will close this because of inactivity.

@theapache64  If you need further help feel free to reopen this issue or create a new one.
