### ISSUE TITLE
question: Constructors validation seems to break when using plainToInstance

### ISSUE THREAD

**Issue by mulgurul** [typestack/class-transformer#1624]
I just thought that this package was very usable and so happy, but then I started running into problems with the constructors of my classes.

I'm working in an Electron App where my class objects need to go over several process boundaries which does not support transferring Class objects. So I really need a lot of transforming from plain to instance etc.

But I have classes where I validate that the correct initialization data is provided in the constructor, if not the New xxxClass() throws an Error. And there's also some additional computation/calculation of some props happening in the constructor.
This happens when I'm doing the plainToInstance transformation. The transformation seems to call the constructor but with empty/none arguments. So my validation fails. I can remove the validation and the object seems ok. So it seems like all the class properties are set anyway.

Now I'm wondering what is happening under the hood. And the documentation does not explain anything about constructor behaviour. Is it possible that the new'ing of the instance could happen with real data from the plain object if properties with the same names as constructor parameters could be found?

Maybe I need to new a new class myself with correct const. call and then use plainToInstanceFromExist but with many constructor parameters this gets pretty ugly with many transformations around in the App.

There's also the question of incapsulation of props with "private", etc. These should also be forced to be set in the constructor.

Any ideas of how I could solve this problem would be much appreciated. It's a very handy package, but a bit broken for me if the constructor thing is not possible.

**Comment by littlefyr** [comment]
@mulgurul -- I raised an issue which is related to what you're asking about but in my case I'm working with `URL` which just doesn't work well at all. 

I did find that this works for me: 

```ts
class TypeTransformClass {
    id: number;

    @Type(() => String)
    @Transform(({ value }) => {
        return value instanceof URL ? value : new URL(value);
    })
    image: URL;
}
```
Maybe something similar would work for your case? Set `@Type` to be something that you can pass to your class constructor. its a bit ugly but what can you do?

**Comment by diffy0712** [comment]
hello @littlefyr,

if you want to have instances in your plain object, than you might be able to solve it with `@Transform` decorator as seen above.
But since you provided no concrete example, I cannot suggest any solution.

**Comment by diffy0712** [comment]
Closing in favor of https://github.com/typestack/class-transformer/issues/1443
