### ISSUE TITLE
THIS IS NOT AN ISSUE

### ISSUE THREAD

**Issue by theapache64** [typestack/class-transformer#164]
I've integrated `class-transformer` with one of my pet projects. :+1: :smiling_imp: :laughing: 

![mock-2018-07-18_15 12 24](https://user-images.githubusercontent.com/9678279/42874190-15e78448-8a9e-11e8-9fb5-0208a43e2b11.gif)

**Comment by PaybackMan** [comment]
very nice

**Comment by theapache64** [comment]
:)

**Comment by NoNameProvided** [comment]
I am sure that  @pleerock, every contributor, and mee too are happy to see your life got easier thanks to class-validator. 

Keep up the good work!
