### ISSUE TITLE
feature: function support of options.discriminator.subTypes

### ISSUE THREAD

**Issue by buddh4** [typestack/class-transformer#1651]
### Description
We currently can define discriminator types as follows:

```javascript
@Type(() => Photo, {
    discriminator: {
      property: '__type',
      subTypes: [
        { value: Landscape, name: 'landscape' },
        { value: Portrait, name: 'portrait' },
        { value: UnderWater, name: 'underwater' },
      ],
    },
  })
  topPhoto: Landscape | Portrait | UnderWater;
```

This assumes that we know all subTypes at build time. There is no way (I've found) to add discriminator types at runtime (other that passing the subTypes array around).

Furthermore the transformer throws an error when using `instanceToClass` and the discriminator is not contained in the subTypes. Maybe a `strict` or `fallbackToDefault` configuration would be nice.

### Proposed solution

It would be great if you could also use a function for the `subType` option as follows:

```javascript
@Type(() => Photo, {
    discriminator: {
      property: '__type',
      strict: false,
      subTypes: (subType: string) => getTypeOfPhoto(subType),
    },
  })
  topPhoto: Landscape | Portrait | UnderWater;
```

I'm happy to contribute in case this feature is desired. I did a quick look and it seems this would only require minor changes  [here](https://github.com/typestack/class-transformer/blob/69cd8ccbc672179ea46492a625653ec448f03a17/src/TransformOperationExecutor.ts#L57) and [here](https://github.com/typestack/class-transformer/blob/69cd8ccbc672179ea46492a625653ec448f03a17/src/TransformOperationExecutor.ts#L57).

**Comment by diffy0712** [comment]
Hello @buddh4,

could you please give some use cases for dynamic subTypes?  I assume `getTypeOfPhoto` would do the same as the map, isn't it?
I am not sure when this would be useful.

Thank you

**Comment by diffy0712** [comment]
Closing as invalid, because of inactivity.
If you want to continue this discussion, feel free to comment on this issue.
