### ISSUE TITLE
plainToClassFromExist is Deprecated what is the replacement for generics?

### ISSUE THREAD

**Issue by charlesritchea** [typestack/class-transformer#1653]
**I was trying to...**
deserialize a generic collection

**The problem:**
plainToClassFromExist works, but is marked deprecated; however, I don't see any replacement

**Comment by diffy0712** [comment]
The deprecation comment is saying that 
> This function is being removed. The current implementation is incorrect as it modifies the source object.

According to the code there is no one-to-one replacement, which can be a problem if you need to populate an instance.
You can use `plainToInstance`, but that will create a new instance.

**Comment by diffy0712** [comment]
Closing as answered. If you have any questions left feel free to comment on this issue.
