### ISSUE TITLE
Decode same json object with different model objects

### ISSUE THREAD

**Issue by theapache64** [typestack/class-transformer#168]
**JSON**

```
{
        "car": {
            "name": "Audi",
            "model": "Q3"
        }
}
```
**Model**
```
  @Type(() => CarOne)
  @Expose({ name: 'car' })
  readonly carOne: CarOne;

  @Type(() => CarTwo)
  @Expose({ name: 'car' })
  readonly carTwo: CarTwo;
```

I want to decode an object (`car`) with different modals `(CarOne) and (CarTwo)`.  Is it possible ? As of now, it only decodes the first one defined, in the above case, `CarOne` only.

**Comment by MTschannett** [comment]
What is your usecase for this? I don't understand what you want to achieve. 

Are this different classes or are they on the same?

**Comment by cojack** [comment]
Me either, @theapache64 any explanation?

**Comment by NoNameProvided** [comment]
Closing this as no answer from the questioner.
