### ISSUE TITLE
plainToClass(): omit attrs not in class?

### ISSUE THREAD

**Issue by rynop** [typestack/class-transformer#172]
1st off - this is a great OSS lib. thanks.

When using `plainToClass()` how do I omit attributes that are in the plain JS object that are NOT in the target class?  Ex:

```json
[{
  "id": 1,
  "firstName": "Johny",
  "lastName": "Cage",
  "age": 27,
  "dneInClass": "foo"
},
{
  "id": 2,
  "firstName": "Ismoil",
  "lastName": "Somoni",
  "age": 50,
  "dneInClass": "foo"
},
{
  "id": 3,
  "firstName": "Luke",
  "lastName": "Dacascos",
  "age": 12,
  "dneInClass": "foo"
}]
```
`User` class:

```typescript
export class User {
    id: number;
    firstName: string;
    lastName: string;
    age: number;

    getName() {
        return this.firstName + " " + this.lastName;
    }

    isAdult() {
        return this.age > 36 && this.age < 60;
    }
}
```

`console.log(plainToClass(User,obj))` will output the `dneInClass` attribute.

The use case here is I have a DTO that defines the POST interface for a web API endpoint.  Some of the attributes in the POST are part of my class - but some are not.  In a simple CRUD example, I like to return the created object JSON when Create endpoint is called.  If I `plainToClass(User,myDto)`, save my `User` to the DB and then return the `User` to the caller - I only want the `User` attributes returned - and not some of the extra DTO attributes that tagged along in the `plainToClass()` call.

**Comment by Petr0vi4** [comment]
You need to `Exclude` all class properties, and then `Expose` those one you need

```
@Exclude()
export class User {
    @Expose() @Type(() => Number) id: number;
    @Expose() firstName: string;
    @Expose() lastName: string;
    @Expose() @Type(() => Number) age: number;
}
```

**Comment by rynop** [comment]
Thank you sir! closing.
