### ISSUE TITLE
`Transform` decorator applies transformation multiple times on every `plainToInstance` call

### ISSUE THREAD

**Issue by ghost** [typestack/class-transformer#1720]
I have applied a transformation to my field that transforms it by multiplying with a certain number like this:

```@Transform(({ value }) => value * secondsInHour)```

Whenever a `plainToInstance` is called, it applies this transformation multiple times. I need to apply `plainToInstance` multiple times in a single flow for some reason but I don't want to apply this transformation more than once. 

Could any please suggest some approaches or strategies to avoid multiple transformations?

**Comment by diffy0712** [comment]
The issue does not contain a simple reproduction case.

Closing as invalid.
