### ISSUE TITLE
fix: plainToInstance 实例化不到 @Expose() get xxx

### ISSUE THREAD

**Issue by 2395000206** [typestack/class-transformer#1726]
### Description
 class User { 
  @Exclude()
  leader_group: Group;
 
  @Expose() 
  get isLeaderGroup() :boolean {
    return !!this.leader_group
  } 
}
const user = {
  leader_group: { name: 'aaa' }
}
const row =  plainToInstance(Users, user )
console.log(row) 

//  实际打印 { } ， 希望打印 { isLeaderGroup: true }

```

### Expected behavior
{ isLeaderGroup: true }

### Actual behavior
{ }

**Comment by heifengli001** [comment]
Use other methods to implement it. This version from 3 years ago hasn't been released for a long time
//CN :使用其他方法实现吧，这个3年前的版本了，很久没有release了
  @Expose()
  @Transform(({ obj }) => !!obj. leader_group)
  isLeaderGroup: boolean;

**Comment by fingerart** [comment]
> Use other methods to implement it. This version from 3 years ago hasn't been released for a long time //CN :使用其他方法实现吧，这个3年前的版本了，很久没有release了 @expose() @Transform(({ obj }) => !!obj. leader_group) isLeaderGroup: boolean;

还有什么类似好用的库？

**Comment by diffy0712** [comment]
The issue does not contain a simple reproduction case and does not use plain English.

Closing as invalid.
