### ISSUE TITLE
feature: InstanceToPlain better return type

### ISSUE THREAD

**Issue by samislam** [typestack/class-transformer#1732]
### Description
```ts
class MyClass {
  @Expose({ name: 'desc', toPlainOnly: true })
  description: string
}

const x = { description: 'asc' }
const y = plainToInstance(MyClass, x)
const z = instanceToPlain(y) // type: Record<string, any>
```

### Proposed solution
The return type of `instanceToPlain()` should be `{ desc: string }`.

**Comment by diffy0712** [comment]
Hello @samislam,

do you have a solution on how to get the typing for it right?

**Comment by diffy0712** [comment]
Closing as invalid, because of inactivity.
If you want to continue this discussion, feel free to comment on this issue.
