### ISSUE TITLE
question: plainToInstance should be so permissive?

### ISSUE THREAD

**Issue by renan-almeida-isi** [typestack/class-transformer#1733]
I have had some issues with property matching. Considering:

```
class UserDTO {
  id: number;
  name: string;
  @Transform(({value}) => (value.name))
  parent: string;
  @Exclude()
  parent_id: number
}

let instance = plainToInstance(UserDTO, {name: "John"})
console.log(instance) // UserDTO { name: "John" }
```

Is this the expected output or am I missing something? I would expected that the defined properties in the instance are required and should raise an error if they doesn't exist on the plain.
I found frustrating that code errors (like not loading a relation, which is defined in my DTOs) aren't handled by this lib and couldn't find a better way to make sure that all properties I need in a DTO are really there than check field by field.

Any tips about it?

**Comment by diffy0712** [comment]
Hello @renan-almeida-isi,

could you please check the answer for this issue https://github.com/typestack/class-transformer/issues/1719 if this is an answer to your question as well?

**Comment by renan-almeida-isi** [comment]
Hello and thank you for you replying.
I read this issue already, but my complaint is more about property name matching than type matching. I found it odd that I pass a defined data structure as the target to be transformed, and the function doesn't point out missing keys in the input data. I would suggest an option to change this (like excludeExtraneousValues), or even a decorator to define required properties in the input object. I probably misunderstood the use of plainToClass, and this is just my point of view, but this behavior of letting missing properties pass undetected could lead to unexpected results.
Thanks for your time, I will close this issue.

**Comment by renan-almeida-isi** [comment]
Hello and thank you for you replying.
I read this issue already, but my complaint is more about property name matching than type matching. I found it odd that I pass a defined data structure as the target to be transformed, and the function doesn't point out missing keys in the input data. I would suggest an option to change this (like excludeExtraneousValues), or even a decorator to define required properties in the input object. I probably misunderstood the use of plainToClass, and this is just my point of view, but this behavior of letting missing properties pass undetected could lead to unexpected results.
Thanks for your time, I will close this issue.

**Comment by diffy0712** [comment]
Hello @renan-almeida-isi,

So you do not want a type checking, just the ability to know what ia missing at runtime?
You would want a `strict mode` so it does throw an Error when the key it was expecting does not exists?
