### ISSUE TITLE
attribute name with @Expose don't work with lazy relation

### ISSUE THREAD

**Issue by cooperons** [typestack/class-transformer#177]
Hello,
I have this  attribute in my user entity witch is a lazy relation   : 

   ```
 @ManyToMany(type => Course)
    @JoinTable()
    @Expose({groups: ['user'], name: 'courses'})
    courses: Promise<Course[]>;
```

When I apply this code in my controller :
`res.send({user: classToPlain(user, {groups: ['user']})});`

I have __courses__ in  the response API and not courses. Note that the transformation name works fine  with eager relations.

Thanks

**Comment by cojack** [comment]
@cooperons did you populate your model with this relation?

**Comment by NoNameProvided** [comment]
> I have courses in the response API and not courses. 

What do you mean, you use the same word. **courses** equals to courses.

**Comment by NoNameProvided** [comment]
Closing as no answer from OP.
