### ISSUE TITLE
chore(*): Merge develop into master and bump version up to 0.2.0

### ISSUE THREAD

**Issue by cojack** [typestack/class-transformer#180]

**Comment by cojack** [comment]
So, today was a quite good day that we fix a lot of issue, and bring some new features to this library, quite impressive.

If you don't mind, I'm for semver, but bumping Major? Meh, test are passing, I don't see any breaking changes (or Im blind, I can not say), but we can do few things, like `0.2.0` version for all of this stuff, and also `0.1.11` for some bug fixing, but do we really need it?

I also see that there is requirement to rewrite few parts to smaller chunks, because `TransformOperationExecutor` going TO Fword BIG!

@MTschannett please help me, Im counting on you :heart:

**Comment by MTschannett** [comment]
@cojack Yes it was a good day. 

Yeah I overestimated the changes in #125. They seemed bigger than they acutally were (first day huh ^^)

I would also be for semver. I think it would be a 0.2.0 then. (Its more than small patches, so this seems acurate for me)

Yes I guess there is enough work to be done and I'm looking forward to tackle them ^^

**Comment by cojack** [comment]
@MTschannett I have change the version as you suggest up to 0.2.0, tomorrow?

**Comment by MTschannett** [comment]
Sounds good for me. Can't wait to release our first version ^^

**Comment by NoNameProvided** [comment]
> I'm not sure if #125 doesn't have some breaking changes. Using semver this would result in a new major version.

Below 1.x a minor bump is considered major by npm, so yes we are using semver.

**Comment by NoNameProvided** [comment]
I think it's just easier to create a release PR (`release: 0.x.x`) and do the discussion there.
