### ISSUE TITLE
Remove Node Version 6 from travis

### ISSUE THREAD

**Issue by MTschannett** [typestack/class-transformer#184]
It looks like Node Version 6 is causing problems when tests are running. 

This should be changed.

**Comment by MTschannett** [comment]
@cojack Do you now how to do this? I have never used travis before.

**Comment by NoNameProvided** [comment]
@MTschannett NodeJS 6 is still supported. The test should be fixed, not Node 6 being removed. We can remove support for Node 6 after 2019 April.

**Comment by MTschannett** [comment]
Yes you are right. I thought i heard something about, but I mixed up some numbers.
