### ISSUE TITLE
Add dependency manager

### ISSUE THREAD

**Issue by MTschannett** [typestack/class-transformer#185]
I've seen we have very old versions in our repository. 

Maybe we could use something like https://greenkeeper.io/ to keep them at the latest versions.

Is there an open source thing we could use?

@cojack  Do you have an idea about this?

**Comment by NoNameProvided** [comment]
Greenkeeper is just fine, however, it's not easy to add it, as the major update of the testing tools breaks the tests. See typestack/class-transformer#186.

**Comment by MTschannett** [comment]
Is gulp breaking? 

```
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/travis/build/typestack/class-transformer/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/travis/build/typestack/class-transformer/node_modules/undertaker/lib/task.js:13:8)
    at MetadataStorage.registerTasks (/home/travis/build/typestack/class-transformer/node_modules/gulpclass/MetadataStorage.js:41:44)
```

I guess we should investigate this before proceeding. 

I think having old dependencies to keep things from breaking is a bad option.

**Comment by MTschannett** [comment]
Same here. I don't use gulp somewhere else.

Do you want to investigate or should i take a look at it?

**Comment by NoNameProvided** [comment]
Actually, I think I managed to update it in class-validator. First now I want to take a look at PRs, catch up with issues. Then I will start with this before doing any other fixes.
