### ISSUE TITLE
Add formatter for code

### ISSUE THREAD

**Issue by MTschannett** [typestack/class-transformer#194]
In my last review i saw that the formatting of the code differs from commit to commit.

This makes it harder to read . 

we could enforce the usage of an code formatter like prettier to keep this consistent.

**Comment by NoNameProvided** [comment]
Prettier should be added, I prefer, single quotes, 2 space for tab. I can do this in like 5 minutes, but that will make every PR unmergeable basically.

**Comment by MTschannett** [comment]
I like these styles

Hmm. I don't know if git is smart enough fpr this.

Shoudn't this work if both, PR and origin is formatted?

**Comment by NoNameProvided** [comment]
Actually, not so hard, we just need to decide on the PRs which we are not sure about if we want to close them or merge them.

**Comment by MTschannett** [comment]
That's true :)

**Comment by NoNameProvided** [comment]
Done.
