### ISSUE TITLE
onSerialized/onDeserialized callbacks

### ISSUE THREAD

**Issue by geleto** [typestack/class-transformer#20]
I need this feature to initialize the serialized data. Would be nice to have access to the class instance or the plain object in these callbacks, though just the callback with no parameters will suffice in my case.

**Comment by juracy** [comment]
I've started to use it, and for my use case this feature would be great!

**Comment by NoNameProvided** [comment]
You can easily implement this via 

```ts
const instance = plainToClass(MyClass, obj);
instance.initalize()
```
