### ISSUE TITLE
stenciljs: 'Type' is not exported by node_modules/class-transformer/index.js

### ISSUE THREAD

**Issue by mcelotti** [typestack/class-transformer#200]
I'm using stenciljs 0.15.2 (rollup) and importing Type with:
`import {Type} from 'class-transformer';`
The result is:
`[ ERROR ]  Rollup: Missing Export: src/models/forecast.js:11:9
           'Type' is not exported by node_modules/class-transformer/index.js`

As a workaround I'm importing Type from decorators and import reflect-metadata globally:
```
import "reflect-metadata";
import {Type} from 'class-transformer/decorators';
```

Thanks,
Marco

**Comment by mcelotti** [comment]
Hi @NoNameProvided , yes I noticed it's exported there but stenciljs (that uses rollup) gives me that error.
Might be a problem on the stenciljs side though.

**Comment by pairmix** [comment]
Same issue for me.
@mcelotti , did you find a way to let it work ?

**Comment by mcelotti** [comment]
@pairmix as I wrote the workaround that I found is:
```
import "reflect-metadata";
import {Type} from 'class-transformer/decorators';
```

the "reflect-metadata" is a global import I placed in my "app.ts" so it gets loaded before the actual imports "import {Type} from 'class-transformer/decorators';", these imports are placed in specific files where the "type" annotation in required

**Comment by pairmix** [comment]
@mcelotti : You're right. I forgot to import my main.ts file from my old ionic project into my new pwa/stencil project.
I used to import:
````
import 'core-js/es7/reflect';
````

Thank you very much!
