### ISSUE TITLE
@Expose incompatible with @computed

### ISSUE THREAD

**Issue by johnhamm** [typestack/class-transformer#205]
I'm not sure if this bug belongs here or in the mobx github.

I use class-transformer together with mobx.  They work great together (particularly for initializing an object with observable properties).

However, the  `@Expose` decorator is incompatible with mobx's `@computed` decorator.
The following throws an error regardless if we use `@Expose() @computed` or `@computed @Expose()`:

```ts
class User {
  firstName;
  lastName;
  
  @Expose()
  @computed get name() {
    return this.firstName + ' ' + this.lastName;
  }
}

const u = new User();
u.firstName = 'cat';
u.lastName = 'stevens';

const json = serialize(u);
console.log(json);
```
:exclamation:  |  **Error**
--- | ---
&nbsp; | [mobx] [ComputedValue 'ExposedAndComputedUser@35.someName'] It is not possible to assign a new value to a computed value.
&nbsp; | at invariant (https://z280j6jnk4.codesandbox.io/node_modules/mobx/lib/mobx.js:2668:15)
&nbsp; | at ComputedValue.set (https://z280j6jnk4.codesandbox.io/node_modules/mobx/lib/mobx.js:756:13)
&nbsp; |  at ObservableObjectAdministration.write (https://z280j6jnk4.codesandbox.io/node_modules/mobx/lib/mobx.js:1036:24)
&nbsp; | at ExposedAndComputedUser.set (https://z280j6jnk4.codesandbox.io/node_modules/mobx/lib/mobx.js:1238:61)
&nbsp; | at _loop_1 (https://z280j6jnk4.codesandbox.io/node_modules/class-transformer/TransformOperationExecutor.js:222:47)

Here's a code sandbox of the issue:
https://codesandbox.io/s/z280j6jnk4

**Comment by MTschannett** [comment]
I think this is not a bug, but rather a wanted behaivior from mobx.

Could it be that they block access to the setter of that value?

You only implement the getter that leads me to this conclusion.

**Comment by johnhamm** [comment]
Ah, so the class-transformer serialize method writes to getters in order to serialize it?

**Comment by MTschannett** [comment]
when a object has  getter or setter in this form they are always used for this.
 
This is a normal JS behaivior. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

**Comment by johnhamm** [comment]
I meant that it tries to "set" the value of the getter property?  If there's no setter, then why would class-transformer try to assign a value?

**Comment by johnhamm** [comment]
The issue was with my original plain objects not with class-transformer.

**Comment by MTschannett** [comment]
First thanks for your CodeSandbox reproduction :) Made it real easy to play a bit with your code :).

As i guessed, mobx creates a setter for your value.

In your example you have the getter `get someName`. Mobx automatically creates a setter on that class.

So when you create a class (with plainToClass(...)) we get our object with the computed getter and a setter (automatically created from mobx) which throws an error. (I think normally JS would simply ignore it when you set a value to a non existent setter, based from my observations in the chrome dev tools)

Here is a instantiated object from your CodeSandbox:

![image](https://user-images.githubusercontent.com/18646672/48692779-954abf80-ebd7-11e8-89e2-2369839b1be5.png)

As you can se we have a `get someName` and a `set someName` (in the proto field of our object)

My understanding from mobx (I don't use it) is that this should a pure function (as much as possible in this context). So why do you not ignore someName and only set `firstName` and `lastName` and let mobx do its magic?
