### ISSUE TITLE
在ie11Possible Unhandled Promise Rejection: TypeError: 对象不支持“find”属性或方法

### ISSUE THREAD

**Issue by wang-jiyu** [typestack/class-transformer#206]
Possible Unhandled Promise Rejection: TypeError: 对象不支持“find”属性或方法

**Comment by MTschannett** [comment]
@lazarljubenovic I'm glad that you can read this ^^
@wang-jiyu Please try to polyfill like mentioned above

I'll close this feel free to reopen when you need more help
