### ISSUE TITLE
Error while deserializing optional array with discriminated type

### ISSUE THREAD

**Issue by tstavinoha** [typestack/class-transformer#207]
Hello,

I've noticed that undefined arrays which have discriminated types throw an error when being deserialized. Undefined arrays without discriminator transform to undefined without issue, and the same should happen for arrays with discriminated types.

Here's a code sandbox illustrating the issue: https://codesandbox.io/s/vmkmr69vv0
The failing test is located in file polymorphic-array.test.ts.

**Comment by digeomel** [comment]
I think I'm having the same issue with null fields. If I specify a nullable field with a union type based on a discriminator, I get an exception like this:

core.js:15724 ERROR TypeError: Cannot read property '__typename' of null
    at TransformOperationExecutor.js:159

In my  case, as you can see above, the discriminator field is '__typename', coming from Apollo GraphQL data.
Any ideas how to work around this?

**Comment by NoNameProvided** [comment]
Closed in #245. Will be released as `0.2.2`
