### ISSUE TITLE
plainToInstance

### ISSUE THREAD

**Issue by geleto** [typestack/class-transformer#21]
I need to deserialize to an existing class instance.
For example in Aurelia I don't have control of the instantiation of the view-model objects and have to perform the deserialization from the constructor.
Also I expect to receive data updates for the objects and it would be much easier to just update the properties, rather than change the whole object.

**Comment by geleto** [comment]
... found plainToClassFromExist in the source, you should document it

**Comment by kirillgroshkov** [comment]
I'd like to see some example of `plainToClassFromExist` as well

**Comment by NoNameProvided** [comment]
Docs added by @MTschannett.
