### ISSUE TITLE
Subclasses won't deserialize types in superclass

### ISSUE THREAD

**Issue by RobertGardner** [typestack/class-transformer#210]
The following used to work, but stopped working recently. I believe it was when I upgraded to Typescript 2.8 but it could have been something else. Unfortunately, a number of things changed on my project at the same time and I haven't been able to narrow it down further.

I've simplified the breaking code to the following:

file: foo.ts
```
import { Type } from "class-transformer";
import "reflect-metadata";

export class FooMoney {
  pennies: number;

  constructor(value: number) {
    this.pennies = value * 100;
  }
}

export class FooBase {
  @Type(() => FooMoney)
  amount: FooMoney;
}

export class Foo extends FooBase {
}
```

file: foo.spec.ts
```
import { plainToClass } from "class-transformer";
import { Foo, FooMoney } from "~/app/models/foo";

describe("Foo Serialization", () => {
  it("deserializes", () => {
    let plain = {
      amount: { pennies: 1000 }
    };
    let f = plainToClass(Foo, plain);
    expect(f instanceof Foo).toBeTruthy();
    expect(f.amount).toEqual(new FooMoney(10));
  });
});
```

This gives the error:
```
Expected object to be a kind of FooMoney, but was Object({ pennies: 1000 }).
```

Interestingly, if I change the test to deserialize to `FooBase` instead of `Foo` then it works:
```
    let f = plainToClass(FooBase, plain);
    expect(f instanceof FooBase).toBeTruthy();
```
With that change, the test passes.

**Comment by RobertGardner** [comment]
I found a workaround, though with a lot of properties, it's unpleasant.

I noticed that Typescript decorates `FooBase` with `amount`'s type (`FooMoney`). But it does not decorate `Foo`. Apparently `class-transformer` is not examining the inheritance tree to find decorations (though since this used to work, apparently it used to walk the tree?).

So I modified `Foo` to include a (redundant) decoration:

```
export class Foo extends FooBase {
  @Type(() => FooMoney)
  amount: FooMoney;
}
```

The test now passes and the class behaves as expected.

I think `class-transformer` should walk the inheritance tree up to the root to find decorations.

**Comment by MTschannett** [comment]
Thanks for this detailed description. I'll guess this would be a good behaivior, otherwise information about the object is lost.

**Comment by RobertGardner** [comment]
Correct. The biggest problem is if the inner class has functions. For example, if `FooMoney` had methods like `add()` or `subtract()`, those would not be available after deserialization.

That's actually how I found the problem because I kept getting errors about trying to call functions that don't exist.

**Comment by Rmannn** [comment]
Any news on this ? I have the same kind of errors

**Comment by Rmannn** [comment]
To help others, be sure to have the same unique version of the module across node_modules, also, avoid using npm link or yarn link as your module will have his own folder of dependencies.
Using yalc instead has helped me.

**Comment by phyllisstein** [comment]
I'm running into something similar. I have a superclass called `Node`:

```ts
export abstract class Node {
    id: string

    order: number

    kind: NodeKind

    @Exclude()
    protected _children: Node[]

	@Expose()
	@Transform(transformFn)
	get children(): Node {
		return this._children
	}
```

And it has a subclass called `Tree`:

```ts
export class Tree extends Node {
    @Type(() => Content)
    content: Content

    kind = NodeKind.TREE

    constructor({ id }: TreeParams = {}) {
        super({ id })
    }
}
```

When a `Tree` is serialized, however, neither the directive to exclude `_children` nor the directive to expose `get children` is honored:

```json
{
    "_children": [],
    "id": "bBdX8Rax6XHKXGZ3St5Jc",
    "kind": "TREE"
}
```

**Comment by NoNameProvided** [comment]
Cannot reproduce anymore the original example works as intended:

```ts
import 'reflect-metadata';
import { plainToClass, Type } from './index';


export class FooMoney {
  pennies: number;

  constructor(value: number) {
    this.pennies = value * 100;
  }
}

export class FooBase {
  @Type(() => FooMoney)
  amount: FooMoney;
}

export class Foo extends FooBase {}

const plain = { amount: { pennies: 1000 } };
const instance = plainToClass(Foo, plain);

console.log(instance); // logs Foo { amount: FooMoney { pennies: 1000 } }
console.log(instance instanceof Foo); // logs true
console.log(instance.amount instanceof FooMoney); // logs true
```

**Comment by NoNameProvided** [comment]
I also cannot reproduce @phyllisstein example. Which is full of sytactical errors and not a minimal reproducible example but I tried to keep it as close as possible to the example:

```ts
import 'reflect-metadata';
import { Type, Expose, Exclude, classToPlain } from './index';


class Node {
  id: string;

  order: number;

  kind: string;

  @Exclude()
  _children: string[];

  @Expose()
  get children(): string[] {
    return this._children;
  }
}

class Tree extends Node {
  @Type(() => String)
  content: string

  kind = '<tree-kind>';
  
  constructor() {
    super()
    // some custom stuff;
    console.log('custom-stuff');
  }
}

const instance = new Tree();

instance.id = '<some-id>'
instance.order = 1;
instance._children = [];

console.log(classToPlain(instance));
// logs { kind: '<tree-kind>', id: '<some-id>', order: 1, children: [] }
```

**Comment by phyllisstein** [comment]
Thanks for your response. You're right: `console.log`ging the `classToPlain` call shows the expected output. Must have made an error elsewhere.
