### ISSUE TITLE
NaN fails to round-trip

### ISSUE THREAD

**Issue by pickle-ts** [typestack/class-transformer#211]
NaN fails to round-trip.

Test:

```typescript
class TestObj {
  foo: number
}

function getA() {
  const a = new TestObj()
  a.foo = NaN
  return a    
}

function getB() {
  const a = getA()
  const s = serialize (a)
  const b = deserialize (TestObj, s)
  return b
}

const aFoo = getA().foo   // NaN
const bFoo = getB().foo   // null (should be NaN)
```    
Run test code live:
https://stackblitz.com/edit/serialization?file=index.ts

**Comment by MTschannett** [comment]
Thanks, seems like a bug.

**Comment by pickle-ts** [comment]
I followed up on this one and discovered that:

The JSON standard doesn't support NaN:
https://tools.ietf.org/html/rfc8259#page-7
"Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted."

In light of this, the current behaviour - replace `NaN` with `null` - seems reasonable to me.

Happy for you to not fix this and close this issue.

**Comment by MTschannett** [comment]
@pickle-ts: Thank you for this link.

After reading a bit through it I think this current behaivior is ok.

Also following code returns a null for the property a: 
```
    JSON.stringify({
        a: NaN
    })
```
So we are "spec-compliant" with this one ^^
