### ISSUE TITLE
question: using @Type with subclasses of the same class

### ISSUE THREAD

**Issue by patricknazar** [typestack/class-transformer#212]
I've been trying to use `@Type()` with itself:

```
import { Type } from 'class-transformer';

class User {

  @Type(() => User, {
    discriminator: {
      property: 'type',
      subTypes: [
        { value: HappyFriend, name: 'happy' },
        { value: SadFriend, name: 'sad' },
      ],
    },
  })
  friend: HappyFriend | SadFriend;
}

class HappyFriend extends User {
  doHappy() {}
}

class SadFriend extends User {
  doSad() {}
}
```

but I can't because `[ts] Class 'HappyFriend' used before its declaration. [2449]` and `[ts] Class 'SadFriend' used before its declaration. [2449]`

Any idea what I can do here?

**Comment by patricknazar** [comment]
I managed to use `@Transform()` to do it. It calls a recursive function imported from another file which in turn imports the classes and uses a `switch()` to check. I was worried about a circular reference but apparently not.

**Comment by hedegitsinue** [comment]
Hello @patricknazar 

I've encountered the same problem and still not able to find a proper solution. Can you please share the solution you came up with or at least the basics of the idea?

**Comment by patricknazar** [comment]
@hedegitsinue 

```
import { Transform, TransformationType, classToPlain, plainToClass, classToClass } from 'class-transformer';

function transformFn(value: User, obj, type) {
  if (type === TransformationType.PLAIN_TO_CLASS) {
    return User.fromObject(value);
  } else if (type === TransformationType.CLASS_TO_PLAIN) {
    return classToPlain(value);
  } else if (type === TransformationType.CLASS_TO_CLASS) {
    return classToClass(value);
  }
}

class User {
  type: string = '';

  name: string;

  @Transform(transformFn)
  friend: User;

  sayHi() {
    console.log(`${this.getMessage()}\n`);
  }

  getMessage() {
    return `My name is "${this.name}", I am a *${this.friendlyType()}*${this.friend ? ` and my friend says:\n${this.friend.getMessage()}` : '.'}`;
  }

  friendlyType() { return 'Base User'; }

  static fromObject(value) {
    switch (value.type) {
      case 'happy':
        return plainToClass(HappyUser, value);
      case 'sad':
        return plainToClass(SadUser, value);
      default:
        return plainToClass(User, value);
    }
  }
}

class HappyUser extends User {
  friendlyType() { return 'Happy User'; }
}

class SadUser extends User {
  friendlyType() { return 'Sad User'; }
}

plainToClass(User, {
  name: 'A',
  friend: {
    name: 'A\'s Friend',
    type: 'happy',
  }
}).sayHi();

plainToClass(User, {
  name: 'B',
  friend: {
    name: 'B\'s Friend',
    type: 'sad',
  }
}).sayHi();

plainToClass(User, {
  name: 'C',
  friend: {
    name: 'C\'s Friend',
    type: 'unknown',
    friend: {
      name: '2nd Level Friend',
      type: 'happy',
      friend: {
        name: '3rd Level Friend',
        type: 'another',
      }
    }
  }
}).sayHi();
```

**Comment by hedegitsinue** [comment]
Thank you very much! @patricknazar

**Comment by patricknazar** [comment]
No worries @hedegitsinue hope it helps!

**Comment by hedegitsinue** [comment]
@patricknazar 

Today I found a way to use this functionality and maybe you will find this helpful. 

**What I did:** I wanted to transform JSON to object  that has children of same kind ("Tag" class). But it was giving me "Tag_1" is not defined. Then I thought that transform function was changing the metadata definitions. I decided to take the class name outside of transform function and export it with a constant. After that it started to work properly. And also `@Type()` decorator started to work.


```
@Exclude()
export class Tag {

  @Expose({name: 'children_tags', toClassOnly: true})
  /*@Transform((childrenTags) => {
    if (childrenTags) {
      return childrenTags.map(child => plainToClass(TagClass, child));
    }
    return childrenTags;
  }, {toClassOnly: true})*/
  @Type(() => TagClass)
  children: Array<Tag> = [];

}

export const TagClass = Tag;
```

**Comment by NoNameProvided** [comment]
If you still experience an issue with using discriminator with `@Type` decorator then please open a new issue and please
provide a __minimal__ reproducible example showcasing your problem. The example should:

- be as short as possible why showcasing the problem
- has no external dependencies used, only this lib
- the expected and actual behavior should be explained

**Comment by NoNameProvided** [comment]
Closing as the question is old.

**Comment by 4imble** [comment]
I am having this same issue.
The strange thing is I have exactly the same code in another project (using a different front end framework) and it's working fine. 
I am not sure if there's something about CRA project that is causing the issue but nothing I have tried has allowed me to get past this issue.

https://github.com/4imble/class-transformer-recursion-issue
Here is the same project that errors with: 
`ReferenceError: Cannot access 'Container' before initialization at ./src/domain/container.ts (container.ts:12:1)`

```
import Base from "./base";
import Item from "./item";
import { Type } from 'class-transformer';

export default class Container extends Base
{
    @Type(() => Base, {
        discriminator: {
            property: "type",
            subTypes: [
                { value: Item, name: "item" },
                { value: Container, name: "container" }
            ]
        }
    })
    children: Array<Item | Container> = []
}
```
https://github.com/4imble/class-transformer-recursion-issue/blob/3ca9dbee794cb900a6753da70e485e1a3472f14f/src/domain/container.ts

**Comment by 4imble** [comment]
Long story short, I gave up, re created my project using Vite instead of CRA and it's working now.
