### ISSUE TITLE
Expose multiple times a property fails

### ISSUE THREAD

**Issue by jbdemonte** [typestack/class-transformer#214]
Trying to use more than once a property fails.
It would be great to be able to use it more than once especially when building some different values thanks to transformers on nested objects for example.

In my case, I only try to swap some properties and I have to deal with fake property names, which is just an ugly workaround

```
  it('fails', () => {
    class CastDto {
      @Expose()
      @Transform(() => 123)
      id: string;

      @Expose({ name: 'id' })
      prevId: string;
    }
    expect(plainToClass(CastDto, { id: 456 })).toEqual({ id: 123, prevId: 456 });
  });

  it('works', () => {
    class CastDto {
      @Expose({ name: 'fake_id' })
      @Transform(() => 123)
      id: string;

      @Expose({ name: 'id' })
      prevId: string;
    }
    expect(plainToClass(CastDto, { id: 456 })).toEqual({ id: 123, prevId: 456 });
  });
```

**Comment by NSExceptional** [comment]
+1, I want to expose the same property multiple times using different transforms. It's more concise than using getters

**Comment by sabrinaToulouse** [comment]
Hi, same here

**Comment by NoNameProvided** [comment]
What would be the expected behavior here? The first example works correctly.

```
import 'reflect-metadata';
import { Expose, Transform, classToPlain } from '.';

class ExampleClass {
  @Expose()
  @Transform(() => 123)
  id!: string;

  @Expose({ name: 'id' })
  prevId!: string;
}

const instance = new ExampleClass();
instance.id = 'id';
instance.prevId = 'prevId'

console.log(classToPlain(instance));
// logs { id: 'prevId' }
```

This is the currently expected behavior as the explicitly named Expose overrides the first implicit one. This is not an elegant solution as we should warn in this case but it works. I fail to see why the result should be `{ id: 123, prevId: 456 }` mentioned in the example.  

Your second example also incorrect as the returned value is different and the below is the correct behavior.

```ts
import 'reflect-metadata';
import { Expose, Transform, classToPlain } from '.';

class ExampleClass {
  @Expose({ name: 'fake_id' })
  @Transform(() => 123)
  id!: string;

  @Expose({ name: 'id' })
  prevId!: string;
}

const instance = new ExampleClass();
instance.id = 'id';
instance.prevId = 'prevId'

console.log(classToPlain(instance));
// logs { fake_id: 123, id: 'prevId' }
```

**Comment by NoNameProvided** [comment]
Closing this as invalid.
