### ISSUE TITLE
Type decorator metadata not correctly set when using discriminator

### ISSUE THREAD

**Issue by barisere** [typestack/class-transformer#217]
### I am Reporting

A bug.

### What my Code Looks Like

I have a class with a field whose type is a union type. To handle union types, class-transformer suggests providing an object (of type `TypeOptions`) that specifies a discriminator to the `@Type` decorator (see https://github.com/typestack/class-transformer#providing-more-than-one-type-option).
The field with the union type in my class is as follows.
```typescript
  // ...
  @ValidateNested()
  @Type(() => Object, {
    discriminator: {
      property: "type",
      subTypes: [
        { name: FeaturedContentTypes.album, value: FeaturedAlbumShallow },
        { name: FeaturedContentTypes.song, value: FeaturedSongShallow },
        { name: FeaturedContentTypes.playlist, value: FeaturedPlaylistShallow },
      ],
    },
    keepDiscriminatorProperty: true,
  })
  content: FeaturedAlbumShallow | FeaturedSongShallow | FeaturedPlaylistShallow;
  // ...
```
### How the Code Behaves

When I run the code and inspect the decorator metadata extracted, I notice that the decorator metadata are not correctly set. Specifically, the `subTypes` field (of type `JsonSubType`) of the discriminator has only the first element set correctly. The rest of the elements of the array have their `value` properties set to `undefined`, as shown in the screenshot below.

![Incorrect decorator metadata as seen in VS Code debugger](https://user-images.githubusercontent.com/20553476/49394400-10fa4f80-f734-11e8-8532-beac2e2b629c.png)

### What I Expected

In the `subTypes` array, I expect the second element (index 1) to have `{ name: "song", value: class FeaturedSongShallow { ... } }`. Similarly, I expect the third element (index 2) to have `{ name:  "playlist", value: class FeaturedPlaylistShallow { ... } }`
Consequently `plainToClass` does not set the properties of the `content` field correctly when used with objects that have a `content.type` property set to either "song" or "playlist", but it works when `content.type` is set to "playlist".

**Comment by mitkoevoets** [comment]
I was having some issues with this myself and managed to solve it. Maybe I can help you out.

Could you post more of your code?
The Classes you are trying to cast, where you are calling the plainToClass() function and the json that is being used as a schema (if that's what you are doing)

**Comment by barisere** [comment]
@mitkoevoets I'm sorry I've not had time to look back at this issue. I encountered the problem I described during my internship, but now I'm back to school. I'll find time later to look at it and see if I can follow it up properly.

**Comment by SamuelGaona** [comment]
I'm kinda having this problem right now.

**Comment by barisere** [comment]
> @mitkoevoets I'm sorry I've not had time to look back at this issue. I encountered the problem I described during my internship, but now I'm back to school. I'll find time later to look at it and see if I can follow it up properly.

Wow, it's been over a year already. How time flies!

I tried to reproduce this issue, but I couldn't. The metadata was correctly set this time. But I noticed a behaviour that may be worth looking into: deeply nested properties may not be transformed using their correct class constructors.
I show this using some test cases available on codesandbox.io. Here's the [link to the sandbox](https://codesandbox.io/s/class-transformer-issue217-ycsjb).

@SamuelGaona please see the link to the sandbox, it may help you with this issue. If it doesn't, here's how I solved it last year.
I replace the discriminator property approach with the `TypeHelpOptions` as follows.
```typescript
  @Type((opts: TypeHelpOptions) => {
    switch (opts.object[opts.property].type) { // this is unsafe, and it won't be smooth if you have strict null checks enabled.
      case FeaturedContentTypes.album:
        return FeaturedAlbumShallow;
      case FeaturedContentTypes.playlist:
        return FeaturedPlaylistShallow;
      case FeaturedContentTypes.song:
        return FeaturedSongShallow;
    }
  })
  content: FeaturedAlbumShallow | FeaturedSongShallow | FeaturedPlaylistShallow;
```
Both approaches produce equivalent results, but the `TypeHelpOptions` approach may not be smooth if your tsconfig options has strict null checks enabled (it should). Let me know whether it works for you.

**Comment by SamuelGaona** [comment]
Holy crap, that works. I was having problem with deeply nested properties, and i was thinking it could be because of inheritance, but this solves my problem for now.

There is one note, if the property is a array, you have to check the first item, that is `(opts.object[opts.property][0].discriminator)`

**Comment by barisere** [comment]
> Holy crap, that works. I was having problem with deeply nested properties, and i was thinking it could be because of inheritance, but this solves my problem for now.
> 
> There is one note, if the property is a array, you have to check the first item, that is `(opts.object[opts.property][0].discriminator)`

I'm glad this hack helps you. I'll close this issue, because I could not reproduce the error scenario that I reported.
