### ISSUE TITLE
Date object is not serializing

### ISSUE THREAD

**Issue by ankurgupta4891** [typestack/class-transformer#22]
I'm using Type decorator for Date. Even after it's not serializing and json has empty object instead.  
**Sample code:**

class d {
    id:number;
    @Type(() => Date)
    da: Date;
}

let obj:d = new d();
obj.id = 1;
obj.da = new Date();

console.log(serialize<d>(obj));

**Output** 
{ id: 1, da: {} }

Is this an issue or am I missing something here?

Note: deserializing a string date to date object is working though.

**Comment by cojack** [comment]
It's fixed.
