### ISSUE TITLE
Routing controllers & Class transformer

### ISSUE THREAD

**Issue by cernicc** [typestack/class-transformer#229]
Hi.
In my JsonController I am returning a model that is Transforming a moment object.

Something like:
`
@Transform((value: Moment.Moment) => Moment(value).toISOString(), { toPlainOnly: true })
public deletedAt: Moment.Moment;`

Controller is not calling `classToPlain` on the returned model object.
Transformer is called and it works if I call `classToPlain` on my object before returning it in the conntroller. 

Thank you. Good day.

**Comment by alexpls** [comment]
Hi @cernicc, I'm not understanding exactly what your issue is? You mention that the object gets serialized when you call `classToPlain`, which is the expected behavior of `class-transformer`, right?

**Comment by NoNameProvided** [comment]
Sorry for the slow reply. Closing as out of date, if you still experience the issue, please open a new one. Thanks.
