### ISSUE TITLE
Deserialization doest not set value when property has default value in prototype

### ISSUE THREAD

**Issue by nouc23** [typestack/class-transformer#233]
When you setup default property value by property, for example:
```
class TestObject {
    normalProp: string = "Hello!";
    prototypedProp: string;
}

TestObject.prototype.prototypedProp = "I'm a BUG!";
```

and than you try to create object

```
const payload = {
    normalProp: "Goodbye!",
    prototypedProp: "Goodbye!"
};

plainToClass(TestObject, payload)
```

You will get
```
{
    normalProp: "Goodbye!",
    prototypedProp: "I'm a BUG!"
}
```

**Comment by nouc23** [comment]
#234

**Comment by NoNameProvided** [comment]
Closed in #234. Will be released as `0.2.2`.

**Comment by NoNameProvided** [comment]
This change will be reverted because it breaks `@Exclude`

**Comment by NoNameProvided** [comment]
Has been reverted in `0.2.3`

**Comment by nouc23** [comment]
> This change will be reverted because it breaks `@Exclude`

Can you provide some example or explain the problem in more detail?

**Comment by NoNameProvided** [comment]
This is not the case anymore. Unknown properties are not transformed anymore.
