### ISSUE TITLE
Use `plainToInstance` instead of `plainToClass`

### ISSUE THREAD

**Issue by ghost** [typestack/class-transformer#235]
Hi,
just came along usage of `class-transformer` usage in one project I work on and I have a big problem with the naming used in this package API and docs which is very misleading, concretely:

What do you refer as a `class` is actually an `instance`

https://en.wikipedia.org/wiki/Instance_(computer_science)
https://en.wikipedia.org/wiki/Class_(computer_programming)

My suggestion is just to:
- make a copy of `plainToClass`  which will be `plainToInstance` or some other reasonable name
- mark `plainToClass` as deprecated
- change the docs
- after some time remove `plainToClass` for ever

**Comment by rostyslav-diakiv** [comment]
@Michall @NoNameProvided 
If you don't mind I can do that and send you a pool request to review =)

**Comment by NoNameProvided** [comment]
Fixed in 01db22254fd3c2ae03279c567d27312afa2ad14f,
