### ISSUE TITLE
feat: include custom option keys as argument in @Transform

### ISSUE THREAD

**Issue by bladerunner41** [typestack/class-transformer#238]
The `@Transform` arguments should change from: 
`@Transform((value, obj, type) => value)` 
to include an options parm (i.e. version, group + custom keys) 
`@Transform((value, obj, type, options) => value)` 
so that 
`classToPlain(user, { version: 0.5 });` and `classToPlain(user, { groups: ["user"] });` 
can also support custom keys: 
`classToPlain(user, { version: 0.5, key1:value, key2:value });` 
that can be accessed in transform: 
`@Transform((value,options) => options.key1)`

why?

use case 1: Moment Timezone support (the current moment example is great but without support for a TZ it is limited.  We are a multi-tenanted SaaS app so the TZ of the account needs to be passed in (it is not stored on each entity which is what the obj param would provide access to.  The TZ needs to be provided at run-time - not static on the metadata at design time.

```
@Transform((value,options) => moment(value).tz(options.timezone), { toClassOnly: true })
date: Moment;

classToPlain(user, { timezone: "America/Los_Angeles" });
```
use case 2: currency formatting - similar again need to pass in the country/currency code.  Any localisation of numbers, time, dates, currency etc

use case 3: resolve references - when serialising an object need to be able to resolve references to objects by ID and serialise the name - easy - just pass in the object need to resolve as a option at run time and write an `@Transform` function.

I see there is a similar but different PR open https://github.com/typestack/class-transformer/pull/209/files

**Comment by dobromyslov** [comment]
Thank you for this feature.

I noticed that the [ClassTransformOptions interface](https://github.com/typestack/class-transformer/blob/8266303892f02e1469e1ec1828da3b3c7ebc7695/src/interfaces/class-transformer-options.interface.ts#L6) does not describe any ability to extend it with additional options for Transform functions.

I think the interface definition should be like:
```typescript
export interface ClassTransformOptions {
  ...
  /** Additional options for Transform functions */
  [key: string]: any;
}

**Comment by NoNameProvided** [comment]
Open a new issue for this please.
