### ISSUE TITLE
Generic types

### ISSUE THREAD

**Issue by TheAifam5** [typestack/class-transformer#241]
Hey!
Its possible to serialize/deserialize for generic types like:

class BaseObject {
  id: string;
}

type Generic<T extenss BaseModel> = BaseObject& T;

I want do deserialize the Generic<CustomEntity>.

Regards,
TheAifam5

**Comment by kaleb** [comment]
https://github.com/typestack/class-transformer#working-with-generics

**Comment by alexpls** [comment]
Hey @TheAifam5, if @kaleb's answer worked for you, would you mind closing this issue? I'm not a maintainer of this package but am trying to get some issues closed while the maintainers are away.
