### ISSUE TITLE
flatmap-stream problem

### ISSUE THREAD

**Issue by CristhianParra** [typestack/class-transformer#243]
After run npm install --save class-transformer

npm ERR! code ETARGET
npm ERR! notarget No matching version found for flatmap-stream@0.1.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'event-stream'
npm ERR! notarget 

Since the package was eliminated for security reasons

**Comment by alexpls** [comment]
I'm not seeing this issue. Are you trying to install `class-transformer@0.2.0`?:

```
$ npm install --save class-transformer
npm notice created a lockfile as package-lock.json. You should commit this file.

+ class-transformer@0.2.0
added 1 package from 1 contributor and audited 1 package in 0.617s
found 0 vulnerabilities
```

**Comment by NoNameProvided** [comment]
Hi @CristhianParra! 

I cannot reproduce this issue either. I will go ahead and close this issue, but please comment if you still facing any issue.
