### ISSUE TITLE
0.2.2 breaks @Exclude/@Expose

### ISSUE THREAD

**Issue by RobertGardner** [typestack/class-transformer#254]
Sorry, not enough time to chase down the bug and present it more concisely, but I thought I'd report it in case you can easily find it. Release 0.2.2 breaks my transform that is working correctly in 0.2.0. If I simply revert the version back to 0.2.0 then my code works.

Here's the class that fails to transform correctly (sanitized, hopefully I didn't introduce a breakage by doing that!):

```ts
export class FType {
  @Exclude()
  category: FCategory;
  @Exclude()
  variation: string;

  @Expose()
  get strType(): string { return `${this.category}/${this.variation}`; }
  set strType(type: string) {
    const bits = type.split("/");
    this.category = <FCategory>bits[0];
    this.variation = bits[1];
  }

  constructor(category: FCategory, variation: string) {
    this.category = category;
    this.variation = variation;
  }
}

class Foo {
  @Type(() => FType)
  type: FType;
}
```

If I deserialize a json that looks like:

```
{
  "type": { "strType": "Bar/v1" }
}
```

using:

```ts
plainToClass(Foo, json);
```
then I get `category: undefined`, `variation: undefined`, and `strType: undefined/undefined`. With 0.2.0 I get `category: Bar`, `variation: v1`, and `strType: Bar/v1`, as expected.

**Comment by NoNameProvided** [comment]
Hi! 

Can you check if it's working in `0.2.1`? (For me the example seems to work, but let's check with your codebase as well.)

Here are the changes between `0.2.1` and `0.2.2`: https://github.com/typestack/class-transformer/compare/6d33aa771bd86a4a604556ec7251744ac1c833ca...824e27e1826ae6b4afe30c8b681bd4e885089c52

The following three things changed between `0.2.1` and `0.2.2`:
 - in plain-to-class transfomration, we try to infer the type of the property is it's a primitive type (#191)
 - we prevent breaking the transformation when an undefines is passed for an array with a discriminator defined (#245)
 - we allow writing to properties which have been defined already on the prototype (#234)

**Comment by NoNameProvided** [comment]
Can you try replacing `((descriptor && !descriptor.writable) ` in the  218th line in `node_modules/class-transformer/TransformOperationExecutor.js` to `((descriptor && !descriptor.set)` ?

```diff
- && ((descriptor && !descriptor.writable) || newValue[newValueKey] instanceof Function)) //  || TransformationType === TransformationType.CLASS_TO_CLASS
+ && ((descriptor && !descriptor.set) || newValue[newValueKey] instanceof Function)) //  || TransformationType === TransformationType.CLASS_TO_CLASS
```

Let me know if this will make it work.

**Comment by RobertGardner** [comment]
This change works.

**Comment by CubixSystem** [comment]
Hi!

Similar issue for me, my code works in `0.2.0` and doesn't work in `0.2.1`, `0.2.2` (`childrens` is empty array)

My code is something like this (artificial example):
```javascript
@Exclude()
export class Tree {
  @Expose()
  @Type(() => UnimplementedNode, {
    discriminator: {
      property: "id",
      subTypes: [
        { value: FooNode, name: "FooNode" },
        { value: BarNode, name: "BarNode" },
      ],
    },
    keepDiscriminatorProperty: true,
  })
  public childrens: (
    | FooNode
    | BarNode
    | UnimplementedNode)[] = [];
}
```

**Comment by NoNameProvided** [comment]
Hi @CubixSystem! And does the above change fix your problem? Because that change was in 0.2.2

**Comment by NoNameProvided** [comment]
@RobertGardner & @CubixSystem `0.2.3` has been released. Please give it a try and let me know if it works or not.

**Comment by RobertGardner** [comment]
This works for me. Thanks!
