### ISSUE TITLE
How to transform string to enum

### ISSUE THREAD

**Issue by thatsmeta** [typestack/class-transformer#256]
Hi,
I'm very happy I found this project and hope it is still under active development.
How can I map a JSON string to a Typescript enum with the help of class-transformer?
Suppose my JSON looks like this `{ "encryptionLevel": "ENCRYPTED"}`, how can I map this to an enum?
I tried just setting 
```
@Type(() => EncryptionLevel)
public encryptionLevel: EncryptionLevel;
```

with
```
export enum EncryptionLevel {
    ENCRYPTED,
    NOT_ENCRYPTED
}
```
But it does not work. I know that in Typescript mapping from a string to an enum (or even to a string enum) is a bit more complicated, but when I tried using a custom transformation function via
`@Transform(value => mapStringToEnum(value, EncryptionLevel))`, the value was alway `NaN`.

**Comment by NoNameProvided** [comment]
Hi @thatsmeta!

Currently only number enums are supported and we already have a ticket for string enum support: #90
