### ISSUE TITLE
Option to disable implicit type conversion introduced in 0.2.2

### ISSUE THREAD

**Issue by keenondrums** [typestack/class-transformer#257]
In [this commit](https://github.com/typestack/class-transformer/commit/c3ced62663ba5f68a2a3d0583632870dc1e58dc8) an implicit type conversion based on TS reflected type was introduced.  It makes DTO validation less strict without a way to disable it.
Consider us having a DTO "Cat":
```ts
import { IsString } from 'class-validator'

class CatDTO {
  @IsString()
  tail: string
}
```
If we convert a plan object with `tail` as a number to CatDTO using `plainToClass`, class-transformer would convert `tail` to a string automatically.
```ts
import { validate } from 'class-validator'

const obj = {
  tail: 123
}
const catInstance = plainToClass(CatDTO, obj)
// { "tail":"123" }
validate(catInstance) // passes
```
With this implicit type conversion we can no longer have a strict validation of incoming data.

This functionality could be useful to some people, but I believe it should be optional and disabled by default.

What do you think?

Would you be willing to accept a PR which adds a new option to `plainToClass` - `implicitTypeConversion` set to `false`?

**Comment by kamilmysliwiec** [comment]
This change has broken many e2e tests in lots of NestJS production applications since it introduced a breaking change in the library behavior.

**Comment by vizlibdk** [comment]
> With this implicit type conversion we can no longer have a strict validation of incoming data.

This change broke my application. Make this functionality optional, please. I had to decrease `class-transformer` version to keep strict validation working well.

**Comment by NoNameProvided** [comment]
Hi all! Thanks for the feedback! This will be addressed. Until it’s fixed you can pin class-transformer at 0.2.0 to prevent this behavior.

**Comment by kamilmysliwiec** [comment]
Thanks @NoNameProvided! I'll pin the version as soon as possible @vizlibdk

**Comment by NoNameProvided** [comment]
Hi all! 

`0.2.3` has been released what hides the implicit conversion behind the `enableImplicitConversion` flag and disabled by default. It also reverts a change what caused issues with the `@Exclude` decorator (#254). 

Please let me know if the problem is fixed. Thanks.

**Comment by SeWaS** [comment]
Hi @NoNameProvided,

Thanks for the update! To me, upgrading from `0.2.0` to `0.2.3` worked like a charm.

**Comment by vizlibdk** [comment]
Hi @NoNameProvided thank you very much, everything works fine!
