### ISSUE TITLE
Cannot access 'x' before initialization

### ISSUE THREAD

**Issue by niveo** [typestack/class-transformer#258]
> typescript: 3.4.5
> angular: 8.0.0-rc.4
> class-transformer: 0.2.2

```
export class ConfTable {
  id: number;
  @Type(() => ConfField)
   idField: ConfField;
}
export class ConfField{
   id: number;
    @Type(() => ConfTable)
    confTable: ConfTable;
}
```
Error: Cannot access 'ConfField' before initialization

I have a circular dependency that is generating an error, does anyone know how to solve it?

**Comment by NoNameProvided** [comment]
Please provide a minimal reproducible test case. (Aka please include the transformed payload as well.)

**Comment by niveo** [comment]
the error only occurs with the tsconfig.json target other than es5

**Comment by anpross** [comment]
i had the same error message but without producing a (obvious) circular reference: i was placing my static transformer functions (for `@Transform()`) into the same class, and was referencing those from dependant objects. moving those methods in there own classes solved the problem.

**Comment by AFDevMike** [comment]
I am working through this as well.

@NoNameProvided - in our case the app does not boot so there is no transformed payload.  We only get the error stated in the Question.  We are on es2015 and es2018.    

We are able to work around by(using the above example) 
Changing `idField: ConfField;` to `idField: null | ConfField;`
And `confTable: ConfTable;` to `confTable: null | ConfTable;`
