### ISSUE TITLE
Buffer is undefined on plainToClass

### ISSUE THREAD

**Issue by JCKodel** [typestack/class-transformer#259]
Error:
```
Uncaught (in promise) ReferenceError: Buffer is not defined
    at t.transform (p-39aba6d2.js:1)
    at t.plainToClass (p-39aba6d2.js:1)
    at e.plainToClass (p-39aba6d2.js:1)
    at Ki.querySingleClass (p-0a2d55c9.js:1)
    at async u.loadResume (p-elexrork.entry.js:1)
    at async u.onRouteDidChange (p-elexrork.entry.js:1)
```

Code at error:
```javascript
...
:null==e?e:new Date(e);if(a()&&(r===Buffer||e instanceof Buffer)&&!s)return null==e?e:Buffe
...
```

Context:
An StencilJS app using this code:
```typescript
import { plainToClass } from "class-transformer";

export class RecipeUser
{
	public id: string;
	public avatarUrl: string;
	public displayName: string;
}

export default class Recipe
{
	public sentBy: RecipeUser = plainToClass(RecipeUser, { avatarUrl: "assets/logo.svg", displayName: "Display Name" });
}
```

Details:
Works fine on dev, but when built to production it fails.

Possible causes:
StencilJS/RollUp tree shaking

Workaround (gives me a warning in StencilJS compilation :( ):
1) npm install buffer
2) Import and add Buffer to window manually on global\app.ts:
```typescript
import "reflect-metadata";
import "@ionic/core";
import { setupConfig } from "@ionic/core";
import * as buffer from "buffer";

(window as any).Buffer = buffer.Buffer;

setupConfig({ backButtonText: null });
```

(StencilJS warnings:
```
[ WARN  ]  Bundling Warning PLUGIN_WARNING
           preferring built-in module 'buffer' over local alternative at
           'E:\Projects\KD\MeuCronogramaCapilar\MeuCronogramaCapilar\node_modules\buffer\index.js', pass
           'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'buffer' is imported by src\global\app.js, but could not be resolved – treating it as an external dependency
```
)

Reproduction steps:
1) npm init stencil
2) Answer ionic-pwa, anyProjectName, Confirm Y
3) cd anyprojectname
4) npm install class-transformer reflect-metadata
5) Edit tsconfig.json to emit metadata decoration ("emitDecoratorMetadata": true)
6) On src/components/app-home/app-home.tsx, insert the following code:
```typescript
import "reflect-metadata";
import { plainToClass } from "class-transformer";

class User
{
  id: number
  firstName: string
  lastName: string
}
```

and in the render method:
```typescript
const user = plainToClass(User, { id: 1, firstName: "First", lastName: "Last" });

...
<ion-content padding>
    <p>{user.firstName} {user.lastName}</p>
...
```

7) npm install (sometimes stencil is not found)
8) Run with npm start (everything works just fine and home shows First Last.
9) Build with npm run build
10) Serve the folder www (maybe with npm install -g http-serve?)
11) Open in your browser (if http-serve is being used, it is http://localhost:8080)
12) Check the error:
```
p-1040ff6c.js:1 ReferenceError: Buffer is not defined
    at t.transform (p-j2o2unx7.entry.js:1)
    at t.plainToClass (p-j2o2unx7.entry.js:1)
    at e.plainToClass (p-j2o2unx7.entry.js:1)
    at T.render (p-j2o2unx7.entry.js:1)
    at ut (p-1040ff6c.js:1)
    at Array.<anonymous> (p-1040ff6c.js:1)
    at g (p-1040ff6c.js:1)
    at v (p-1040ff6c.js:1)
```

**Comment by JCKodel** [comment]
Noticed that this workaround works and nothing is ever written in the console (so, I guess Buffer isn't really being used at runtime?)
```typescript
(<any>window).Buffer = function()
{
	console.warn("BUFFER");
	console.dir(arguments);
};
```

**Comment by tricki** [comment]
I think I found the problem: If I build for production the minifier changes the `testForBuffer` method from 

```js
function testForBuffer() {
    try {
        Buffer;
        return true;
    }
    catch (_a) { }
    return false;
}
```
to 
```
function o(){try{return!0}catch(t){}return!1}
```

The `Buffer;` line is completely removed. So thebest  solution is probably to do a more explicit check for whether `Buffer` exists, perhaps something like `return "Buffer" in global`?

**Comment by NoNameProvided** [comment]
The implementation of detecting buffer has changed since. This should be solved.
