### ISSUE TITLE
Build always fails on Travis on Node.js stable

### ISSUE THREAD

**Issue by Carlovan** [typestack/class-transformer#263]
I noticed all the builds fails on Travis for Node.js stable.
I guess it's a problem with Gulp version because:

- all the PRs after April 26th fails and Node.js 12 has been released on April 23th
- we are using Gulp 3 and [it doesn't work with Node.js 12](https://github.com/gulpjs/gulp/issues/2324)

So we need to upgrade Gulp or stop testing it on Node.js 12

**Comment by Carlovan** [comment]
Unfortunataly upgrading Gulp seems to be a little difficult since we use [gulpclass](https://github.com/pleerock/gulpclass) that does not support Gulp 4...

**Comment by jotamorais** [comment]
This issue was fixed via https://github.com/typestack/class-transformer/pull/338
