### ISSUE TITLE
miniprogram developsment with  Reflect.getMetadata is not a function .

### ISSUE THREAD

**Issue by binfy** [typestack/class-transformer#267]
I have imported ""reflect-metadata"" and "es6-shim"  in  app.ts.

Why still have problem？

Reflect.getMetadata is not a function 
 TypeError: Reflect.getMetadata is not a function

**Comment by eBaeza** [comment]
I have the same problem

**Comment by NoNameProvided** [comment]
You probably import it after importing class-transformer. `reflect-metadata` must be the first line of the file you will start when executing the program.
