### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by gempain** [typestack/class-transformer#269]
Hello,

For the past few months, we've seen this repository slowly maintained, which is normal as it approaches maturity. However, sometimes, PRs are merged in but take weeks to get released, so I was wondering whether we should automate the release process with [semantic-release](https://github.com/semantic-release/semantic-release).

All the best;

**Comment by jotamorais** [comment]
@gempain 
I agree, but first of all, we have to define and standardize commit hooks, PRs pre-check (like build and tests passing) and also standardize on branch naming convention and workflow.
I believe the best way moving forward would be 

tags (contains the release candidates and stable releases - created off of master branch, always)
master (default branch) - accepts merges from next branch, only
next (branch containing PR merges), but still not integrated with master

changes should only make its way to next branch, via PR - should not accept direct push.

With that in place, we can then create the release automation based on tag name convention using semantic versioning, as you suggested.

Example:

tag: 0.2.4-beta.1 created off of master branch in GitHub - automatically generates a release candidate in NPM

tag: 0.2.4 created of of master branch in GitHub - automatically generates a stable release in NPM

**Comment by NoNameProvided** [comment]
Tooling has been updated in the meantime, now we have automatic package release as well when a maintainer creates a release from a tag.
