### ISSUE TITLE
feature: allow `@Transform` on classes

### ISSUE THREAD

**Issue by joscha** [typestack/class-transformer#274]
Hello,

I have a few entitites that I want to serialize that have a map-like member. For accessor and API reasons that map-like type is not a simple `Map` object itself but looks like this:

```ts
class Env {
  public readonly vars: Map = new Map();
}
```
it is used like this:
```ts
export class Entity {
  public readonly env: Env;
}
```

Now the serialization of an instance of `Entity` that I want to achieve looks like this:
```json
{
  "env": {
    "key": 1,
    "key2": 2
  }
}
```
i.e. the `Env` class has no other members that I want to be serialized - the values in the `vars` map is all the information needed.

This doesn't currently seem to be possible to do, as I would always receive a nesting inside a serialized `Entity` instance:
```json
{
  "env": {
    "vars": {
      "key": 1,
      "key2": 2
    }
  }
}
```
The only way I found sofar to achieve this is to use a transformer on the containing class:

```ts
function transformEnv(env: Env) {
  return env.vars;
}

class Entity {

  @Transform(value => transformEnv(value))
  public readonly env: Env;
}
```

but this is very tedious as I have many different types of classes that all contain an `Env` instance in various levels. All of these need to be annotated with the transformer. I know that an instance of `Env` will always look the same, so I am hoping to do something like this:

```ts
@Transform(value => value.vars)
class Env {
  public readonly vars: Map = new Map();
}

class Entity {
  public readonly env: Env;
}
```

instead, where each `Env` will always be defined by the contents of the nested map.

**Comment by NoNameProvided** [comment]
This is currently not possible.

**Comment by NoNameProvided** [comment]
`@Transforms` on class won't be implemented, but your use-case should be possible via custom `@Transform` decorators.
