### ISSUE TITLE
plainToClass function values bug

### ISSUE THREAD

**Issue by Goodluckhf** [typestack/class-transformer#276]
I have case when i have an object where values can be either `function` either `class` or even other types. Now if i use `plainToClass` I will get error, because it will try to invoke it.
![image](https://user-images.githubusercontent.com/9287861/60499353-f899e580-9cc0-11e9-8b5f-f57c7a65be82.png)

As I understand, this behaviour is not acceptable for `plainToClass`

My case:
```
class ServiceA {}
class DTO {
        public token: string;
        public useClass: any;
};

const object  = {
         token: 'ServiceA',
         useClass: ServiceA,
};

const dto = plainToClass(DTO, object);
```
I have pull request for this bug: https://github.com/typestack/class-transformer/pull/275

**Comment by NoNameProvided** [comment]
The provided example completes without errors in the current release.

**Comment by sebastian-zarzycki-es** [comment]
It most certainly does not. class-transformer still tries to evaluate functions and instantiate classes when doing plainToClass.
