### ISSUE TITLE
feature: Type-safe @Expose decorator

### ISSUE THREAD

**Issue by Can-Sahin** [typestack/class-transformer#278]
I am re-opening the issue, since its closed #157

There is a big problem for me that made me stop using this package. I cannot safely map two fields of objects to be transformed.

The problem is let say there is an object
```typescript
class User {
	name: string;
}
```

and you are transforming it into

```typescript
class UserDto {
  	@Expose({name: 'name'})
	firstname: string;
}
const dto = plainToClass(UserDto, userObj);
```

This works. However this cannot be **refactored**. When you change User's `name` into another thing you have to update `@Expose` too and compiler will not warn you to do. 

When the project is growing there are lot of refactoring happening and you loose track of what to change and since its not fully type-safe, typescript doesn't warn you. 

Mapping objects with **refactorable** way is something I need very often!

**Comment by Petr0vi4** [comment]
If you need type-safe property names, you can use typescript lookup types (`keyof` operator), for example:
```
const nameof = <T>(name: keyof T) => name;

interface User {
  name: string;
}

class UserDto {
  @Expose({name: nameof<User>('name')})
  firstname: string;
}
```
So, after renaming `User.name` property to `name2` you will get compile error
> error TS2345: Argument of type '"name"' is not assignable to parameter of type '"name2"'.

**Comment by NoNameProvided** [comment]
This is working as intended, I don't think it's even possible via the current TS type possibilities. Anyway, you can use the workaround commented above.
