### ISSUE TITLE
@Expose and @Exclude don't work together.

### ISSUE THREAD

**Issue by roelvdboom** [typestack/class-transformer#279]
It is not possible to use the expose decorator with the name function and the exclude together when they have the same name.

```ts
export class Settings {
    @Type(() => Customer)
    @Exclude({ toPlainOnly: true })
    defaultCustomer: Customer | null;
    @Type(() => Location)
    @Exclude({ toPlainOnly: true })
    defaultLocation: Location | null;

   @Expose({ name: "defaultCustomer", toPlainOnly: true })
    defaultCustomerId: number | null;
    @Expose({ name: "defaultLocation", toPlainOnly: true })
    defaultLocationId: number | null;
}
```

When using `plainToClass(Settings, data)` the `defaultLocation` and `defaultCustomer` will not be set. When removing the Expose decorators the `defaultLocation` and `defaultCustomer` are set.

**Comment by Petr0vi4** [comment]
Can you provide contents of `data` variable and desired result?

**Comment by roelvdboom** [comment]
@Petr0vi4 

Data:
```ts
{
    defaultCustomer: {
        id: 1,
        name: "Test Customer"
    },
    defaultLocation: {
        id: 1,
        name: "Test Location"
    },
    defaultCustomerId: 1,
    defaultLocationId: 1,
}
```
Expected result
```ts
{
    defaultCustomer: 1,
    defaultLocation: 1,
}
```

**Comment by Petr0vi4** [comment]
Do you really talk about `plainToClass` operation? Your want to transform Data object to `Settings` object with `defaultCustomer` property equals `1`, but `Settings` class describes `defaultCustomer` property as `Customer |
 null` type.

**Comment by Petr0vi4** [comment]
If you need `classToPlain`, it seems that everything works well: https://stackblitz.com/edit/typescript-vt7ny9
