### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by HirenParekh** [typestack/class-transformer#28]
I am having three classes Person, BasicDetails and CloudResponse, when I extend BasicDetails class in Person class and then I run the following code it gives me error.

```
return this.http.post(Environment.domain, JSON.stringify(requestObj), {headers: this.headers})
      .map((res: Response) => {
        return res.json();
      })
      .map(res => plainToClass(MeraCRMCloudResponse, res as Object))
      .catch((error: any) => Observable.throw(console.log(error)));
```

TypeError: Cannot read property 'prototype' of undefined
    at http://localhost:4200/main.bundle.js:60194:84
    at Array.filter (native)
    at MetadataStorage.findMetadatas (http://localhost:4200/main.bundle.js:60194:46)
    at MetadataStorage.findTransformMetadatas (http://localhost:4200/main.bundle.js:60098:21)
    at TransformOperationExecutor.applyCustomTransformations (http://localhost:4200/main.bundle.js:59887:58)
    at _loop_1 (http://localhost:4200/main.bundle.js:59854:41)
    at TransformOperationExecutor.transform (http://localhost:4200/main.bundle.js:59876:31)
    at http://localhost:4200/main.bundle.js:59736:41
    at Array.forEach (native)
    at TransformOperationExecutor.transform (http://localhost:4200/main.bundle.js:59733:19)

**Comment by pleerock** [comment]
can you represent this issue as small as possible and create a plunker for it?

**Comment by HirenParekh** [comment]
here is the [Plunker Link](https://plnkr.co/edit/V51E6n?p=preview).

i have found that the error only occurs when i use Transform() function in my BasicDetail class.

**Comment by nyerel** [comment]
I'm having the same problem.

**Comment by andfaulkner** [comment]
I'm having the same problem as well.

**Comment by britvik** [comment]
I'm getting the same error when trying to call classToPlain before sending data to server.
This fails with error mentioned above.
`@Type(() => Date)
 @Transform(value => moment(value).format('YYYY-MM-DDTHH:mm:ssZZ'), { toPlainOnly: true })
  visibleTo: Date;`
This works fine but uses default conversion.
`@Type(() => Date)
  visibleTo: Date;`

**Comment by daco** [comment]
It looks like this is still an issue. I also get the Cannot read property 'prototype' of undefined error

**Comment by PetrBrabec** [comment]
Me too, I even don't have to extend the class. It does the same when i have some property from inversify container in that class.

**Comment by sandcake** [comment]
I have the same error.
As soon as i use a transformation, plainToClass fails with the error message: 

> Cannot read property 'prototype' of undefined

After debugging it a little i found out that when checking if there is a custom transformation associated with a field, the prototype of the type ( or constructor ) of the field is accessed. The type of the field is (surprise, surprise) undefined.
```javascript
private findMetadatas<...>(metadatas: T[], target: Function, propertyName: string): T[] {
    ...
    const metadataFromChildren = metadatas.filter(meta => target.prototype instanceof meta.target && meta.propertyName === propertyName);
    ...
}
```

in src/metadata/MetadataStorage.ts line 159.

A possible fix would be to give back an empty array of transformation metadata when the target argument is undefined.

`

**Comment by britvik** [comment]
I made a naive fix long time ago in my fork. It worked in my situation, but I have no idea if it might have any implications somewhere else.
https://github.com/britvik/class-transformer/commit/0a1144ce787ec04b19088a621f8e905b35852875

**Comment by bbottema** [comment]
Running into this as well, even if using the value as the result itself:

```typescript
    @Transform(value => value, { toClassOnly: true })
    public readonly date: string;
```

> App_Host.html:1 ERROR TypeError: Cannot read property 'prototype' of undefined

**Comment by gempain** [comment]
#63, #64

**Comment by rphelan** [comment]
The solution is you MUST provide `@Type` annotations for all arrays.

I was able to fix the error in @HirenParekh 's plunk -- the `CloudResponse` model had a property called `data` typed as `any` but it was really an array.  [Here's my working version](https://plnkr.co/edit/VV7FyWvI6etgNFCnMrcy).

That being said, it would be helpful if we at least got a descriptive warning in this scenario.

**Comment by HirenParekh** [comment]
@rphelan `data` property of `CloudResponse` model is of type _any_ because it can be any data. Sometimes in might be number or string or an Array of other objects. `CloudResponse` is a common model of response i for every request, So it is not feasible to define `data` property as array of `Person` model.

**Comment by rphelan** [comment]
@HirenParekh I assumed as much, I was just trying to show that it is possible to avoid the error without modifying class-transformer.

It does say in the documentation "When you are using arrays you must provide a type of the object that array contains"

**Comment by xujif** [comment]
Also exits this bug.

**Comment by xujif** [comment]
@pleerock I found that if a object inside of an plain object will raise this error. see #93

**Comment by janis91** [comment]
https://github.com/typestack/class-transformer/issues/115

**Comment by mosesoak** [comment]
reposted from #114:

+1 This crash is happening for me every time I use `@Transform(customFunction)`.

I don't feel like patching this library so I'm going to skip transforming the incoming query parameter and apply workarounds elsewhere. Look forward to a fix on this!

More information: 
* passing query param `user_ids="1"` vs. `user_ids="1"&user_ids="2"` gives a string or an array, which makes handling the param difficult later
* I'm trying to transform the incoming parameter to an array in the single-string case
* I used `@Type(() => String)` and `@Transform(stringOrArray, { toPlainOnly: true })` where `stringOrArray` is my custom transformer that converts the string to an array.
* Besides fixing the bug on this ticket it would be nice to get this type of transform out of the box since it's a common use case to pass multiple individual params and then want to handle them as a list

**Comment by electrotype** [comment]
(In case it help some) 

I did get this issue too, but it was my fault/lack of understanding after all (in my case)....

What I realized, is that you *have* to use `@Type()` on all fields that are not primitive objects. Not only on those with a custom `@Transform`, on all of them. 

Note that you can use this as a general decorator : `@Type(() => Object)`.

**Comment by Diluka** [comment]
I use `@Transform(value => JSON.parse(value), {toClassOnly: true})` got `TypeError: Cannot read property 'prototype' of undefined`
checked https://github.com/britvik/class-transformer/commit/0a1144ce787ec04b19088a621f8e905b35852875
I do exactly the same with @electrotype https://github.com/typestack/class-transformer/issues/28#issuecomment-358020636

**Comment by pschuster** [comment]
@electrotype This works for me, too! Thanks for that solution!

**Comment by NoNameProvided** [comment]
I think this has been fixed in #100.

I will leave this issue open for now. After the next release please report it the issue still exists.

**Comment by NoNameProvided** [comment]
Just published `0.1.9`, please test it and report if you still encounter this issue. Thanks!

**Comment by electrotype** [comment]
All my tests are passing here, using `0.1.9` and without any extra fix.

Thank you @NoNameProvided !

**Comment by NoNameProvided** [comment]
Thanks! I will go ahead and close this then. If anyone else still encountering this issue, don't hesitate to comment here and I will re-open.
