### ISSUE TITLE
Using type File. TypeError: Failed to construct 'File': 2 arguments required, but only 0 present

### ISSUE THREAD

**Issue by alexsandr1992** [typestack/class-transformer#280]
Hi,

I have next class

```
export class ITestDTO {
    
       Image1Uploader: File | null = null;

}
```

where File is class of typescript.lib.dom.d.ts

```
interface File extends Blob {
    readonly lastModified: number;
    readonly name: string;
}

declare var File: {
    prototype: File;
    new(fileBits: BlobPart[], fileName: string, options?: FilePropertyBag): File;
};
```

when I upload file performed class transformation by plainToClassFromExist.

But I have next error:
TypeError: Failed to construct 'File': 2 arguments required, but only 0 present

How I can resolve this problem?

**Comment by Petr0vi4** [comment]
`ITestDTO.Image1Uploader` property has no `@Type` decorator, so no transormation applied in `plainToClassFromExist`.
Can you provide full example to reproduce error?

**Comment by alexsandr1992** [comment]
This problem can be described in another way.

Let there is a nested object that needs to pass some parameters in the constructor.

How can i do this?

**Comment by alexsandr1992** [comment]
I resolve my problem by next solution:

```
export class ITestDTO {
    @Type(() => Object)
    @Transform((value: any, obj: any) => {
        return obj.image1Uploader;
    })
    image1Uploader: File | null = null;
}
```
