### ISSUE TITLE
fix: classToPlain different behaviour with remote debug running.

### ISSUE THREAD

**Issue by Genhain** [typestack/class-transformer#287]
`classToPlain` and `serialize` produces different results depending on wether you are running with remote debugging turned on.

I am using it to send data to the server, and naturally it was fine initially, but then i turned debugging off it produces an empty result, which is not going down too well with our backend API

here is a list of dependencies used
```
"dependencies": {
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "class-transformer": "^0.2.3",
    "moment": "^2.24.0",
    "react": "^16.8.6",
    "react-native": "^0.60.4",
    "react-native-country-picker-modal": "^0.7.1",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-progress": "^3.6.0",
    "react-navigation": "^3.11.0",
    "realm": "^2.26.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^6.5.2"
  },
```

**Comment by NoNameProvided** [comment]
Hi! 

Thanks for the report, however, this is not enough to track this down. If you are still experiencing the issue please provide 
 - a minimal reproduction sample (using only class-transformer) 
 - description of how do you debug your code

Thanks!
