### ISSUE TITLE
Importing the correct Function

### ISSUE THREAD

**Issue by imalhasaranga** [typestack/class-transformer#29]
I'm getting the following error while trying to convert a Json to Plain Object 

`Type 'VdUser[]' is not assignable to type 'VdUser'.`

This is the code line 

`let vduser:VdUser = plainToClass(VdUser, response.json());`

vdUser is just a plain typescript class and I don't see any problem with the code, I think tsLint is taking the wrong function when validating the code. 

is there a way I can specifically import the function ?

**Comment by Petr0vi4** [comment]
Same issue #30

**Comment by NoNameProvided** [comment]
Duplicate of #30.
