### ISSUE TITLE
Question: How do I change a property's name?

### ISSUE THREAD

**Issue by aidanmcdonagh22** [typestack/class-transformer#291]
I am unsure whether or not I can do this using @Transform() or Expose(), I have read the documentation and do not fully see how to use it as there is very limited examples. Is it possible to do this and if so could you provide an example?

I have a class with a key: `readonly model?: string;` and would like to convert it or add a new property as `readonly ap_model?: string;`.

**Comment by blacksteed232** [comment]
@aidanmcdonagh22 Here
https://github.com/typestack/class-transformer#exposing-properties-with-different-names

**Comment by NoNameProvided** [comment]
As @blacksteed232 answered. You need to use the `@Expose` decorator.

```ts
import { Expose } from 'class-transformer';

class Example {
  @Expose({ name: 'newPropertyName' })
  oldPropertyName: string;
}
```
