### ISSUE TITLE
How to keep already matching properties?

### ISSUE THREAD

**Issue by AndKiel** [typestack/class-transformer#293]
Is there a way to convert a plain object to class and keep properties that already have correct names?

**Comment by kevinrambaud** [comment]
Are you referring to what the `plainToClassFromExist` function does? see https://github.com/typestack/class-transformer#plaintoclassfromexist

**Comment by AndKiel** [comment]
@kevinrambaud, no, I'm referring to a single object that needs transformation but some of its properties already match the desired result. `FromExist` variant requires two different objects. But the issue can be closed as I solved the problem in my codebase.
