### ISSUE TITLE
Is it possible to outsource the desciminator-object?

### ISSUE THREAD

**Issue by NLueg** [typestack/class-transformer#297]
Hello.
I use the class-transformer in a quite complicated class-structure.
The class-transformer does a great job and gives me the correct classes from the given JSON.
Now to my problem:

The base-classes that I use, are getting used in several classes and always resolve in the same way.
Because of that, I need to do a lot of copy-and-paste which results in a heavy maintenance effort.
I tried to outsource the descriminator object to a function. This works fine if I use the function just once, but won't work if I use the function multiple times.
Then I will get a compile error.

Is is a known error?

I can provide you with more information if necessary.

**Comment by kevinrambaud** [comment]
Can you share an example of this issue?

**Comment by NLueg** [comment]
Of course.
I have two classes inherited from a base class.
Namely, the classes `OperandNode` and `ArrayOperandNode` inherit from `BaseOperandNode`, while `BaseOperandNode` ist abstract. 
Now I want to get the correct type from a JSON-String. Therefore I have a string-value inside the JSON-String which determines the type.
I use the class-transformer in the two following classes.

```ts
export class ArrayOperandNode extends BaseOperandNode {
    @Type(() => BaseOperandNode, {
        discriminator: {
            property: "type",
            subTypes: [
                { value: OperandNode, name: "OperandNode" },
                { value: ArrayOperandNode, name: "ArrayOperandNode" }
            ]
        }
    })
    private items: BaseOperandNode[];
}
```

```ts
export class FunctionOperandNode extends BaseOperandNode {
    @Type(() => BaseOperandNode, {
        discriminator: {
            property: "type",
            subTypes: [
                { value: OperandNode, name: "OperandNode" },
                { value: ArrayOperandNode, name: "ArrayOperandNode" }
            ]
        }
    })
    private parameters: BaseOperandNode[];
}
```

This is working fine but it is not very maintainable.
When I need to add a new class, I need to add it to several type-decorators.
Therefore I tried to outsource the discriminator-object like this:

 ```ts
export class TypeDecorator {
    public static getOperationOptions(): TypeOptions {
        return {
            discriminator: {
                property: "type",
                subTypes: [
                    { value: OperandNode, name: "OperandNode" },
                    { value: ArrayOperandNode, name: "ArrayOperandNode" }
                ]
            }
        };
    }
}
```

So with this code, I would change the code in both classes to something like this.

```ts
export class ArrayOperandNode extends BaseOperandNode {
    @Type(() => BaseOperandNode, TypeDecorator.getOperationOptions())
    private items: BaseOperandNode[];
}
```

```ts
export class FunctionOperandNode extends BaseOperandNode {
    @Type(() => BaseOperandNode, TypeDecorator.getOperationOptions())
    private parameters: BaseOperandNode[];
}
```

And now I get the following error in the compiled JavaScript-Code:

![image](https://user-images.githubusercontent.com/48101693/66284793-ed5ee300-e8c9-11e9-8ae4-4cad1d1e085c.png)

Strange enough, this is working as expected when I use the static method only in one class.
I'm not sure if this is because of the limitations of the decorator-object or because of the class-transformer.
I also tried this with a static function instead of a static method.

Is there a way to outsource the discriminator-object and use it in several-classes?
I can't be the first one asking for this, can I?
