### ISSUE TITLE
I see examples with classes but not interfaces.

### ISSUE THREAD

**Issue by hmendezm** [typestack/class-transformer#298]
Hi Guys,

I am trying to use class-transformer but it is not working for me if I have interfaces. Example:

```ts
export interface ADTO{
  @Type(() => BDTO)
    topLeft: BDTO;
  @Type(() => BDTO)
    bottomRight: BDTO;
}

export interface BDTO{
    x: number;
    y: number;
}
json = {
          topLeft: {
            x: 38,
            y: -77
          },
          bottomRight: {
            x: 38,
            y: -76
          }
        }
 const pDTO = plainToClass(ADTO, json);
```
Best
hmendezm

**Comment by kevinrambaud** [comment]
Interfaces and classes are two different concepts. 

You can think about an Interface as something that describes the shape of an object or a contract. Classes are actual javascript objects.

You need to use these decorators on a class as illustrated in all the examples.

**Comment by NoNameProvided** [comment]
As Kevin said. Interfaces are removed at compile-time so this library (or any decorator) works with classes only now with interfaces.
