### ISSUE TITLE
plainToClass : Type 'XX[]' is not assignable to type 'XX'

### ISSUE THREAD

**Issue by samfrach** [typestack/class-transformer#30]
Using webpack and angular2 + Webstorm, I've got an error ...

These 2 methods have the same name but one is for array..

export declare function plainToClass2<T, V extends Array<any>>(cls: ClassType<T>, plain: V, options?: ClassTransformOptions): T[];
export declare function plainToClass<T, V>(cls: ClassType<T>, plain: V, options?: ClassTransformOptions): T;

I have a class XX in TypeScript

private _myVar : XX;
....
this._myVar = plainToClass(XX, obj['xx'])

Webstorm shows it in red..... and webpack doesn't want to compile...

I have to rename this function so that it works (I don't use arrays). 
export declare function plainToClass2<T, V extends Array<any>>(cls: ClassType<T>, plain: V, options?: ClassTransformOptions): T[];

thank you for your help

**Comment by devpreview** [comment]
`let user: User = plainToClass<User, Object>(User, json);`

**Comment by jelling** [comment]
Thanks for the answer. This should be added to the docs.

**Comment by jelling** [comment]
Sometimes you have to do this instead:

```
  const app: BusinessApplication = plainToClass(BusinessApplication, req.body as Object);
```

**Comment by NoNameProvided** [comment]
This has been fixed. Currently not reproducible with `0.3.1`. Minimal example: 

```ts
import 'reflect-metadata';
import { plainToClass, Expose, Exclude } from 'class-transformer';

@Exclude()
class Example {
  @Expose()
  name: string;

  constructor(name: string) {
    this.name = name;
  }
}

const nameA = new Example('A');
const nameB = new Example('B');

const result = plainToClass(Example, [nameA, nameB]);
// result has the proper type: Example[]
```
