### ISSUE TITLE
optional transformation

### ISSUE THREAD

**Issue by rubiin** [typestack/class-transformer#305]
Is there a way to use @Transform  on a entity only if it satisfies a condition like:
if (name.length >=0) transform

**Comment by rubiin** [comment]
@NoNameProvided

**Comment by AmirTugi** [comment]
Why isn't something like 
```javascript
@Transform(value => {
  if (value.length < 0) return value;

  // Do the transform
})
```

I agree that having an unrelated parameter for this might be nice
