### ISSUE TITLE
[bug/proposal] for boolean prop type and enabled `enableImplicitConversion` flag

### ISSUE THREAD

**Issue by ruscon** [typestack/class-transformer#306]
version: `"class-transformer": "0.2.3"`

*example:*
```typescript
import 'reflect-metadata';
import { Expose, plainToClass } from 'class-transformer';

class TestClass {
    @Expose()
    prop: boolean;
}

console.log(plainToClass(TestClass, {
    prop: 'false',
}, {
    enableImplicitConversion: true,
}));
```

*returned:* `TestClass { prop: true }`
*expected:* `TestClass { prop: false }`

**proposal:**
if  `value === 'true' || value === true || value === 1 || value === '1'` then `true`
otherwise `false`

somethink like ths:
```typescript
import { Transform } from 'class-transformer';

export function ToBoolean(): (target: any, key: string) => void {
    return Transform((value: any) => value === 'true' || value === true || value === 1 || value === '1');
}
```

**Comment by joeloudjinz** [comment]
Looks like we have the same issue.
see my [SOF question](https://stackoverflow.com/questions/59046629/boolean-parameter-in-request-body-is-always-true-in-nestjs-api/59047196#59047196)

**Comment by dsbert** [comment]
This issue also means `@IsBoolean` is useless since any value can be transformed to a boolean.

**Comment by adzamkomladev** [comment]
Since this is still open, is there any work around?

**Comment by ruscon** [comment]
@adzamkomladev I'm still waiting for an answer from the developer on how it should work

**Comment by marcj** [comment]
This is supported out of the box in [Marshal.ts](https://github.com/marcj/marshal.ts). Class-transformer is dead, time to switch.

**Comment by leepood** [comment]
same  problem here

**Comment by mostafa-hz** [comment]
> This issue also means `@IsBoolean` is useless since any value can be transformed to a boolean.

Until the issue gets fixed, I'm using this approach to handle it:

```typescript
// ...

@IsBoolean()
@Transform(it => {
  switch (it) {
    case 'true':
      return true;
    case 'false':
      return false;
    default:
      return it;
  }
})
verified!: boolean;

// ...
```

**Comment by karam94** [comment]
Same problem here... I have a DTO with a boolean type on it, but I can't actually treat it like a boolean because at runtime it has type string everywhere...

**Comment by numToStr** [comment]
The shortest version I can think of

```ts
import { Transform } from "class-transformer";

export function ToBoolean() {
    return Transform(v => {
        return ["1", 1, "true", true].includes(v);
    });
}
```

**Comment by pichillilorenzo** [comment]
You can take a look and try also my library [`jackson-js`](https://github.com/pichillilorenzo/jackson-js), which has a lot of decorators and features to easily manipulate JSON, including class transformation as this one. Class transformation is only a little part of what my library can do! As the name implies, it is heavily inspired by the famous Java [FasterXML/jackson library](https://github.com/FasterXML/jackson) and implements almost all of the Java Jackson annotation!

It already supports implicit conversion thanks to `DeserializationFeature.ALLOW_COERCION_OF_SCALARS`. You can set to `true` to enable this feature.

From the **API doc**:
_Feature that determines whether coercions from secondary representations are allowed for simple non-textual scalar types: numbers and booleans.
When feature is enabled, conversions from JSON String are allowed, as long as textual value matches (for example, String "true" is allowed as equivalent of JSON boolean token `true`; or String "1.5" for `Number`)._

Alternatively, you can customize per-JavaScript type o per-class property using other decorators, such as `@JsonDeserialize()`.

**Comment by DanielLoyAugmedix** [comment]
@numToStr I think this is rather misguided as it will convert all objects not in the set ["1", 1, "true", true] to false. I think this is far too broad a definition for type coercion.

**Comment by NoNameProvided** [comment]
Hi all! 

You can see some comments about this on #334 and #363. In short `Boolean('false') == true` so the library behaves as expected. We still need some discussion about the correct approach, most probably we will add a custom flag for this.

**Comment by davidoween** [comment]
I have same problem :( 

any solution?

**Comment by NoNameProvided** [comment]
A tracking issue has been created for this at #550. If you have any feedback regarding the feature, please leave it there.
