### ISSUE TITLE
question: mixing multiple classes to reuse properties

### ISSUE THREAD

**Issue by Sturgelose** [typestack/class-transformer#311]
Imagine we have a property (or set of properties) that appears consistently in different classes (here I'm using both class-transform and class-validate decorators):

```typescript
  @IsOptional()
  @Transform((value: any) => value === 'true' || value === true || value === 1 || value === '1')
  propertyA?: boolean;
```

Is there any way to avoid having to write each time `propertyA` and its decorators in all the different transformation classes?

Our usecase is that we use class-transformer and class-validator to transform JSON inputs of a NestJS API, and most of the endpoints reuse similar structures of query objects, so instead of writing 15 times the same parameter, we could somehow extend, inhert it. However, this happens with multiple groups of parameters, so we need to inhert from multiple classes at the same time (which is a mixin pattern, no?)

I've been checking on using a mixin, but it seems it's not possible, as mixins in TypeScript do not accept  decorators inside of them:

```typescript
class ClassB {
  @IsOptional()
  propertyB?: boolean;
}

type Constructor<T = {}> = new (...args: any[]) => T;

function AddPropA<TBase extends Constructor>(Base: TBase) {
  return class extends Base {
     @IsOptional()
     @Transform((value: any) => value === 'true' || value === true || value === 1 || value === '1')
     propertyA?: boolean;

    constructor(...args: any[]) {
      super(...args);
    }
  };

  // Maybe we can se the transformation/validation here, without a decorator?

}

const ClassBWithPropA = AddPropA(ClassB);
```

Is there any way to attach a `@Transform` decorator without using the decorator, after defining the class? Or at least to write the metadata that the Transform decorator writes, without using the decorator?

**Comment by Sturgelose** [comment]
I kinda found the following way (note that the names of the decorators do not match the previous example.

```typescript
import { IsOptional } from 'class-validator';
import { plainToClass, Transform } from 'class-transformer';

export function ToBoolean(): (target: any, key: string) => void {
  return Transform((value: any) => value === 'true' || value === true || value === 1 || value === '1');
}

function withNotSold<T extends new(...args: any[]) => {}>(constructor: T) {
  const withNotSoldClass = class extends constructor {
    withNotSold?: boolean;
  };
  ToBoolean()(withNotSoldClass.prototype, 'withNotSold');
  IsOptional()(withNotSoldClass.prototype, 'withNotSold');
  return withNotSoldClass;
}

function historicPrediction<T extends new(...args: any[]) => {}>(constructor: T) {
  const historicPredictionClass = class extends constructor {
    historicPrediction?: boolean;
  };
  ToBoolean()(historicPredictionClass.prototype, 'historicPrediction');
  IsOptional()(historicPredictionClass.prototype, 'historicPrediction');
  return historicPredictionClass;
}

@withNotSold
@historicPrediction
class NewClass {}

const test = plainToClass(
  NewClass,
  {
    withNotSold: 'false',
    historicPrediction: 'false',
  });
console.log(test); // Returns: withNotSoldClass { withNotSold: false, historicPrediction: false }
```

Mostly what it does is call manually the decorator(s) and pass the reference to the class to the given decorator instance (so mostly I instance it manually).

It seems to do the trick and even if it's a bit complex, being able to use `@withNotSold` and `@historicPrediction` at will, and mixing them, seems pretty powerful :) I might try to parametrize it, so it is possible to generate this "mixins" and improve the extensibility of this awesome library :)

**Comment by marcj** [comment]
Inheritance is supported out of the box in [Marshal.ts](https://github.com/marcj/marshal.ts). Class-transformer is dead, time to switch.

**Comment by pichillilorenzo** [comment]
You can take a look and try also my library [`jackson-js`](https://github.com/pichillilorenzo/jackson-js), which has a lot of decorators and features to easily manipulate JSON, including class transformation as this one. Class transformation is only a little part of what my library can do! As the name implies, it is heavily inspired by the famous Java [FasterXML/jackson library](https://github.com/FasterXML/jackson) and implements almost all of the Java Jackson annotation! Inheritance is supported!

**Comment by NoNameProvided** [comment]
Am I understanding correctly that you want to keep the property decorators when a class is inherited? If yes, I believe it should work like this. If not then this is a good feature to have.

**Comment by NoNameProvided** [comment]
Closing as no answer from OP.
