### ISSUE TITLE
Is it support below usage?

### ISSUE THREAD

**Issue by zquancai** [typestack/class-transformer#316]
original JSON:
```json
{
  "id": 123,
  "a": "xxxxx"
}
```

```ts
class UserModel {
  @Expose('i')
  id: number;
  @Expose({ name: 'a'  })
  avatar: string;
  @Expose({ name: 'a' })
  get avatarUrl() {
    return 'https://cdn.com/' + this.avatar;
  }
}
```

I walk through all the code, I found it uses Map structure to store originKey/newKey, and the key was unique.

**Comment by pichillilorenzo** [comment]
You can take a look and try also my library [`jackson-js`](https://github.com/pichillilorenzo/jackson-js), which has a lot of decorators and features to easily manipulate JSON, including class transformation as this one. Class transformation is only a little part of what my library can do! As the name implies, it is heavily inspired by the famous Java [FasterXML/jackson library](https://github.com/FasterXML/jackson) and implements almost all of the Java Jackson annotation!

**Comment by zquancai** [comment]
> You can take a look and try also my library [`jackson-js`](https://github.com/pichillilorenzo/jackson-js), which has a lot of decorators and features to easily manipulate JSON, including class transformation as this one. Class transformation is only a little part of what my library can do! As the name implies, it is heavily inspired by the famous Java [FasterXML/jackson library](https://github.com/FasterXML/jackson) and implements almost all of the Java Jackson annotation!

it looks like a very useful converter, but I already write a simple converter to support this kind of usage. Thank you so much!
here is my package: https://www.npmjs.com/package/class-converter
