### ISSUE TITLE
`Map` functionality not working on browser

### ISSUE THREAD

**Issue by marcalj** [typestack/class-transformer#320]
```ts
class LoveB {
  @IsString()
  readonly name: string = null;
}

class LoveA {
  @Type(() => LoveB)
  love: Map<string, LoveB> = new Map();
}
```

```ts
it('transform', () => {
  const test = JSON.parse('{"love": {"feature1": {"name": "feature1-name"}}}');
  const transformedObject = plainToClass(LoveA, test);
  expect(test).toBeInstanceOf(LoveA); // Ok in browser and NodeJS
  expect(test.love).toBeInstanceOf(Map); // Ok in Node, fails in browser
  expect(test).toBeInstanceOf(LoveB); // Ok in browser, fails in NodeJS
});
```

**Comment by pichillilorenzo** [comment]
You can take a look and try also my library [`jackson-js`](https://github.com/pichillilorenzo/jackson-js), which has a lot of decorators and features to easily manipulate JSON, including class transformation as this one. Class transformation is only a little part of what my library can do! As the name implies, it is heavily inspired by the famous Java [FasterXML/jackson library](https://github.com/FasterXML/jackson) and implements almost all of the Java Jackson annotation! It supports also other JavaScript native types such as Maps, Sets, etc.

**Comment by marcalj** [comment]
Thanks, I'm missing validation on jackson-js, it's a requirement for us.

**Comment by chriswhite199** [comment]
@marcalj - Are you using Angular 10? We've recently upgraded from A7 to A10 and this has now broken as you note. I imagine there's something required in the angular configuration that's messing with the reflection metadata and class-transformer is no longer able to detect the field is a Map.

**Comment by chriswhite199** [comment]
Maybe related: https://github.com/angular/angular/issues/26714

**Comment by chriswhite199** [comment]
If have to retro fit the following on my Map fields to get this working with Angular 10

```typescript
@Type(() => LoveB)
@Transform(value => {
        const map = value && new Map<string, LoveB>();
        if (value) {
            Object.entries(value).forEach(entry => {
                map.set(entry[0], plainToClass(LoveB, entry[1] as object));
            });
        }
        return map;
    }, {toClassOnly: true})
love: Map<string, LoveB> = new Map();
```

Here's Chrome debugging showing the reflection metadata doesn't appear to be available, and class-transformer thinks that the field is not a `isSubValueMap`. Also note that the type reflection metadata shows the options field as undefined, which is used to determine the value of `isSubMapValue` further up in `TransformOperationExecutor.js`

![Screen Shot 2020-09-12 at 11 33 43 AM](https://user-images.githubusercontent.com/1356204/93002590-eafb0500-f4ec-11ea-8437-ecab892d0b40.png)

**Comment by chriswhite199** [comment]
I've managed to get this working in a vanilla Angular 10 project, using angular cli 10.1.1. Here's my change list from the vanilla output of `ng new`

## Install deps
```
npm i class-transformer reflect-metadata
```

## Update src/polyfills.ts

```typescript
import 'node_modules/reflect-metadata/Reflect.js';
```

## Update tsconfig.json
```diff
   "compilerOptions": {
     "baseUrl": "./",
+    "emitDecoratorMetadata": true,
     "outDir": "./dist/out-tsc",
```

## app.component.ts

```typescript
import {Component, OnInit} from '@angular/core';
import {classToPlain, plainToClass, Type} from 'class-transformer';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  value: TestModel;
  plain: object;

  get isSubMapAMap(): boolean {
    return this.value.subMap instanceof Map;
  }

  ngOnInit(): void {
    this.value = plainToClass(TestModel, {
      subMap: {
        a: {
          name: 'value1',
          age: 99
        }
      }
    });

    this.plain = classToPlain(this.value);
  }
}

export class TestSubModel {
  name: string;
  age: number;
}

export class TestModel {
  @Type(() => TestSubModel)
  subMap: Map<string, TestSubModel>;
}
```

## app.component.html
```html

<p>
  {{ value | json }}
</p>

<p>
  Is subMap a map: {{ isSubMapAMap }}
</p>

<p>
  {{ plain | json }}
</p>
```

**Comment by chriswhite199** [comment]
Fixed the issue when migration from angular 7 to angular 10 - you need to make sure that the `tsconfig.base.json` (now called `tsconfig.json` in a vanilla A10 app) has the emitDecoratorMetadata set:

```diff
   "compilerOptions": {
     "baseUrl": "./",
+    "emitDecoratorMetadata": true,
     "outDir": "./dist/out-tsc",
```

**Comment by NoNameProvided** [comment]
Thanks, @chriswhite199 for debugging this! Closing this as invalid, as there is no issue with `class-transformer`.

**Comment by marcalj** [comment]
@chriswhite199 sorry for the delay. We've discarded using `class-transformer` on our projects because was adding a lot of latency parsing our objects (due to reflect metadata library). We created a simple parsing library on our end.
