### ISSUE TITLE
[Closed] Date not properly converted with plainToClass

### ISSUE THREAD

**Issue by cyrilfr** [typestack/class-transformer#322]
In this example:

```
class User {
  name: string;
  createdAt: Date;
}

const user = {
  name: 'John',
  createdAt: '2020-01-10 21:16:40'
};

console.log(plainToClass(User, user).createdAt.getTime());
```

getTime() is not a function of createdAt, even if createdAt is a Date.

This example works:

    console.log(new Date('2020-01-10 21:16:40').getTime()); // prints the time

**Comment by tmtron** [comment]
Read [Сonverting date strings into Date objects](https://github.com/typestack/class-transformer#%D1%81onverting-date-strings-into-date-objects)

**Comment by saulotoledo** [comment]
@jotamorais Another issue to close.
