### ISSUE TITLE
Implicit conversion example not working

### ISSUE THREAD

**Issue by lapwat** [typestack/class-transformer#324]
The example [Implicit Type Conversion](https://github.com/typestack/class-transformer/#implicit-type-conversion) is not working:

`index.ts`
```ts
import "reflect-metadata";

import { plainToClass } from "class-transformer";
import { IsString } from 'class-validator'

class MyPayload {
  @IsString()
  prop: string
}

const result1 = plainToClass(MyPayload, { prop: 1234 }, { enableImplicitConversion: true });
const result2 = plainToClass(MyPayload, { prop: 1234 }, { enableImplicitConversion: false });

/**
 *  result1 will be `{ prop: "1234" }` - notice how the prop value has been converted to string.
 *  result2 will be `{ prop: 1234 }` - default behaviour
 */

console.log(result1) // MyPayload { prop: 1234 }
console.log(result2) // MyPayload { prop: 1234 }
```

Run with `tsc --target ES5 --experimentalDecorators index.ts && node index.js`

**Comment by tmtron** [comment]
* what version of class-validator are you using?
* what is the output of `console.log(typeof result1.prop);`

**Comment by lapwat** [comment]
@tmtron 

- Last version for all packages

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "class-transformer": "^0.2.3",
    "class-validator": "^0.11.0",
    "reflect-metadata": "^0.1.13"
  }
}
```

- console.log(typeof result1.prop) gives me `number`

**Comment by tmtron** [comment]
you must also set `"emitDecoratorMetadata"` to `true`

see [`tsconfig.json`](https://github.com/tmtron/class-transformer-324/blob/master/tsconfig.json) in my test project [class-transformer-324](https://github.com/tmtron/class-transformer-324)

**Comment by lapwat** [comment]
Ok thanks now it is working:
`tsc --target ES5 --experimentalDecorators --emitDecoratorMetadata index.ts && node index.js`
