### ISSUE TITLE
plainToClass does not convert a Date to string

### ISSUE THREAD

**Issue by tmtron** [typestack/class-transformer#326]
According to [the docs][1] a `Date` object should be converted to a `string`:

> Note, that dates will be converted to strings when you'll try to convert class object to plain object.

My example-code with class-transformer `0.2.3` does not work as expected:

```typescript
    class TestDate {
      @Type(() => Date)
      aDate!: Date;
    }

      const testDate = new TestDate();
      testDate.aDate = new Date();
      const result: any = classToPlain(testDate);
      console.log(typeof result.aDate);
```

This prints `object` to the console, but I'd expect `string`.  
What am I missing?

[Stackoverflow reference](https://stackoverflow.com/questions/59899045/plaintoclass-does-not-convert-a-date-to-string)

  [1]: https://github.com/typestack/class-transformer#%D1%81onverting-date-strings-into-date-objects

**Comment by jenssegers** [comment]
Any updates about this issue?

**Comment by pichillilorenzo** [comment]
You can take a look and try also my library [`jackson-js`](https://github.com/pichillilorenzo/jackson-js), which has a lot of decorators and features to easily manipulate JSON, including class transformation as this one. Class transformation is only a little part of what my library can do! As the name implies, it is heavily inspired by the famous Java [FasterXML/jackson library](https://github.com/FasterXML/jackson) and implements almost all of the Java Jackson annotation!

For `Date` type, my library converts it into timestamp representation. However you can disable this behaviour setting to `false` the `WRITE_DATE_KEYS_AS_TIMESTAMPS` serialization feature.
To convert you class instance into a plain object, you need to use `JsonStringifier.transform(value: any, context?: JsonStringifierContext)` method.

Also, if you need `aDate` to be string, you can use the `@JsonSerialize()` decorator such as:
```typescript
@JsonSerialize({using: (date) => date.toString()})
```

**Comment by NoNameProvided** [comment]
This is the desired behavior. `classToPlain` will convert the received class instance into a regular JS object and not into JSON. 

If you need to stringify dates you can either 
  - use a custom transformer with `toPlainOnly` set to true
  - call `JSON.parse(JSON.stringify(result))` 
  - use the `serialize` function but that will output a _JSON string_ not a JS object

I will close this questions as answered, if you have any questions regarding this feel free to comment and I will reopen the issue.

**Comment by tmtron** [comment]
>Note, that dates will be converted to strings when you'll try to convert class object to plain object.

@NoNameProvided so this sentence in the docs is wrong, right?

**Comment by NoNameProvided** [comment]
Yes I believe that is an incorrect statement there. Reopening the issue to fix it.

**Comment by NoNameProvided** [comment]
Removed in 6c2f8ce951fa0d8359c529915cf7aa6fb9c8c7dc.
