### ISSUE TITLE
Get datatype of properties

### ISSUE THREAD

**Issue by s888** [typestack/class-transformer#328]
I there a built-in way to get datatype of exposed properties?

I can do this

```ts
function logType(target : any, key : string) {
    var t = Reflect.getMetadata("design:type", target, key);
    console.log(`${key} type: ${t.name}`);
}
class User {
 @logType()
 @Expose()
 id: number
}

//to get datatype of id
logType(User.prototype,'id')
```

But then I have to always use @logType with @Expose to get the datatype.

Thanks in advance.

**Comment by marcj** [comment]
This is supported out of the box in [Marshal.ts](https://github.com/marcj/marshal.ts). Class-transformer is dead, time to switch.

```typescript
import {f, getClassSchema} from '@marcj/marshal';
class User {
    @f id: number;
}

getClassSchema(User).getProperty('id').type //'number'

```

**Comment by s888** [comment]
Great I will try that out but does marshal have supported for nested types too? https://github.com/typestack/class-transformer#working-with-nested-objects

**Comment by s888** [comment]
> This is supported out of the box in [Marshal.ts](https://github.com/marcj/marshal.ts). Class-transformer is dead, time to switch.
> 
> ```ts
> import {f, getClassSchema} from '@marcj/marshal';
> class User {
>     @f id: number;
> }
> 
> getClassSchema(User).getProperty('id').type //'number'
> ```

Great I will try that out but does marshal have supported for nested types too? https://github.com/typestack/class-transformer#working-with-nested-objects

**Comment by marcj** [comment]
> But when there is a nested field info
getClassSchema(User).getProperty('info').type returns class instead of actual className

Which is correct. You can resolve those further using `

```typescript
getClassSchema(User)
  .getProperty('info')
  .getResolvedClassSchema()
  .getProperty('field_of_info')
  .type;
```

**Comment by NoNameProvided** [comment]
No there is no way to get the inferred type via a built-in decorator. Since this feature can be added easily via the mentioned custom decorator I don't think we will land a feature for this. For quick reference here is a sample decorator which will assign the type of the property to a different one:

```ts
function ExposeType(target : any, key : string) {
  const type = Reflect.getMetadata("design:type", target, key);
  target[`${key}__type`] = type'; // make sure you don't overwrite any existing properties here.
}
```
