### ISSUE TITLE
Question: how to use this for mapping FirebaseFirestore.DocumentData in to a custom Object Module?

### ISSUE THREAD

**Issue by aytunch** [typestack/class-transformer#333]
Inside of my Cloud Functions code written in TypeScript, I have 2 custom models which I want to populate with `FirebaseFirestore.DocumentData` maps. Also when writing to Firestore, I would like to deserialize the custom objects into `FirebaseFirestore.DocumentData`s. 

Can I use this library with cloud functions? would it help with this mission? I am somewhat of a noob with web technologies and backend. So please help me out. 

**This explains the issue in greater detail. with code:**
Also before coming up with this library, I asked a question in SO: [Cloud Functions(TypeScript) - How to use custom Models instead of nested maps/dictionaries](https://stackoverflow.com/questions/60578556/cloud-functionstypescript-how-to-use-custom-models-instead-of-nested-maps-di). If I can solve it with this, It would be nice to have an answer in SO so others can see this library.

**Comment by frankps** [comment]
I'm using the combination (Firebase functions/class-transformer), therefore I have written the helper class below. Hope this helps you!

import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
import { plainToClass } from 'class-transformer';


export class PlatformHelper {

    /** Dates coming from firestore are already of type 'Timestamp', plainToClass() from 'class-transformer' is throwing an exception on these Timestamps, therefor we need to convert Timestamp's to 
     * Javascript Date's before calling plainToClass()
     */
    static convertTimestampToDate(obj: any) {

        if (!obj)
            return obj

        Object.keys(obj).forEach(key => {

            let value = obj[key]

            if (value) {

                if (value instanceof admin.firestore.Timestamp) {
                    obj[key] = obj[key].toDate()
                } else if (value instanceof Object) {
                    this.convertTimestampToDate(value)
                }

            }

        })
    }

    static snapshotToType<T>(snapshot: functions.firestore.DocumentSnapshot, type: { new(): T; }): T {

        if (!snapshot) return null

        let obj = snapshot.data()

        if (!obj) return null

        obj.id = snapshot.id

        PlatformHelper.convertTimestampToDate(obj)

        console.log(obj)

        let typed = plainToClass(type, obj);

        return typed
    }


    static querySnapshotToArray<T>(snapshot: FirebaseFirestore.QuerySnapshot<FirebaseFirestore.DocumentData>, type: { new(): T; }): T[] {

        if (!snapshot || !snapshot.docs) return []

        return snapshot.docs.map(doc => PlatformHelper.snapshotToType<T>(doc, type))
    }


    static snapshotToObject(snapshot: functions.firestore.DocumentSnapshot): any {

        let obj = snapshot.data()
        obj.id = snapshot.id

        PlatformHelper.convertTimestampToDate(obj)

        return obj
    }



}

**Comment by pichillilorenzo** [comment]
You can take a look and try also my library [`jackson-js`](https://github.com/pichillilorenzo/jackson-js), which has a lot of decorators and features to easily manipulate JSON, including class transformation as this one. Class transformation is only a little part of what my library can do! As the name implies, it is heavily inspired by the famous Java [FasterXML/jackson library](https://github.com/FasterXML/jackson) and implements almost all of the Java Jackson annotation!

**Comment by frankps** [comment]
Thx Lorenzo: I check it out!!

**Comment by NoNameProvided** [comment]
I am not familiar with Firebase, but generally, you should be able to use it.

I am closing this issue as solved by @frankps. If this is not the case feel free to comment and I will reopen.
