### ISSUE TITLE
@Transform - add option to skip the circular check

### ISSUE THREAD

**Issue by geleto** [typestack/class-transformer#34]
Hello,
I am using data transformations to avoid circular references by storing an id reference of the object, rather than the object itself.
But class-transformer adds the object to `transformedTypes` and by the time it has to be serialized, rather than just referenced - it is skipped because isCircular returns true.

Maybe a skipCircularCheck option can be added to  @Transform:
`@Transform(value => value.id, { toPlainOnly: true,  skipCircularCheck:true })`

I think this is a common use case - I quite often need to serialize data that contains multiple/circular references to the same object.

**Comment by geleto** [comment]
I have a @RefById() transform decorator which rather than serializing the object - stores just the id of the object. When deserializing, the id is used to transparently set the reference to the existing object. Because of this, the transform does not need to be checked for circular references.

While I can use a getter/setter that does the id reference, this is not as clear and simple and my code would be littered with such getters/setters.

My implementation was probably a bit too complex, I modified a few things in class-transformer. One was disabling the circular checks, another was supplying the parent object to transformFn.

Maybe what class-transformer actually needs is the ability to serialize/deserialize references to objects. In my case Id references.

**Comment by NoNameProvided** [comment]
Hi @geleto! 

You can control circular check via `enableCircularCheck` in the third parameter of `classToPlain`.

**Comment by alexpls** [comment]
Hey @geleto, if your question's been answered by @NoNameProvided, would you mind closing this issue? Thanks!
