### ISSUE TITLE
Prototype pollution issue

### ISSUE THREAD

**Issue by vschoener** [typestack/class-transformer#343]
It seems the package has an issue with prototype pollution

see: https://github.com/advisories/GHSA-6gp3-h3jj-prx4

![image](https://user-images.githubusercontent.com/1213200/80716775-5a50f900-8af8-11ea-9851-db23645ca6ab.png)

If someone wants to take a look at this one and bring a fix?

**Comment by Syy0n** [comment]
Already created an issue 25 days ago. https://github.com/typestack/class-transformer/issues/339

**Comment by saulotoledo** [comment]
@jotamorais This issue may be closed.
