### ISSUE TITLE
feat: add support for ES import/export

### ISSUE THREAD

**Issue by ajitjha393** [typestack/class-transformer#344]
Class-transformer module doesn't work with es6 modules if modules is set in tsconfig.json
But works properly for commonjs

**Comment by pichillilorenzo** [comment]
You can take a look and try also my library [`jackson-js`](https://github.com/pichillilorenzo/jackson-js), which has a lot of decorators and features to easily manipulate JSON, including class transformation as this one. Class transformation is only a little part of what my library can do! As the name implies, it is heavily inspired by the famous Java [FasterXML/jackson library](https://github.com/FasterXML/jackson) and implements almost all of the Java Jackson annotation!

**Comment by ajitjha393** [comment]
Ohh great would love to try that ....
I went through your repository it actually has some good utilities provided in there for Ts.
Great Job. Keep it up!

**Comment by NoNameProvided** [comment]
What is your project setup? Frontend or backend, how you build your app? We emit only commonJS exports, but bundlers should be able to detect and handle that. If you are in NodeJS, you should keep using commonJS modules.

**Comment by ajitjha393** [comment]
Project setup was Frontend written in Typescript.  Was just trying out this class transformer Library but was getting error when setting the module System to es6 , so had to set module System back to commonjs for continuing further

**Comment by NoNameProvided** [comment]
A rework of build pipeline just landed in class-validator. Some changes still breaking a build, once those figured out it will be ported to class-transformer as well.

**Comment by david-shortman** [comment]
Angular projects that depend on this lib will likely want this upgrade, since Angular 10 introduced a warning for dependencies that are packaged with CommonJS.

> When you use a dependency that is packaged with CommonJS, it can result in larger slower applications.
Starting with version 10, we now warn you when your build pulls in one of these bundles. If you’ve started seeing these warnings for your dependencies, let your dependency know that you’d prefer an ECMAScript module (ESM) bundle.

https://blog.angular.io/version-10-of-angular-now-available-78960babd41#16c4

**Comment by NoNameProvided** [comment]
Added in 26b5dac86e41ef206a9ca06eed1993308d6e1481. It will be included in the next release.
