### ISSUE TITLE
Custom array transformation not working

### ISSUE THREAD

**Issue by ricardoekm** [typestack/class-transformer#348]
Hi, first of all thanks for the great library!

It seems custom array transformation is not working when using plainToClass, as shown in the docs:

```ts
import {Type} from "class-transformer";

export class AlbumCollection extends Array<Album> {
    // custom array functions ...
}

export class Photo {

    id: number;

    name: string;

    @Type(() => Album)
    albums: AlbumCollection;
}
```

The class is transformed into an array[] rather than AlbumCollection. Is this related to [Typescript breaking changes](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work)?

Thanks

**Comment by NoNameProvided** [comment]
You doesn't include what an Album is, but it's probably an interface. Interfaces are compiled away and don't exist at runtime, so use a class instead. 

Minimal working example with class: 

```ts
import 'reflect-metadata';
import { plainToClass, Type, Exclude } from 'class-transformer';

class Album { }

class AlbumCollection extends Array<Album> { }

class Photo {
  name: string;

  @Type(() => Album)
  albums: AlbumCollection;
}

const instance = plainToClass(Photo, { albums: [{}, {}]});

console.log(instance)
// instance is a Photo class 
// with an albums property what contains two Album class
```

Closing as solved. If still experience any issue regarding this question, please comment on this issue and I will reopen.
