### ISSUE TITLE
List of exhibited properties

### ISSUE THREAD

**Issue by La-source** [typestack/class-transformer#349]
Hello,

As part of the development of a Rest API I encounter a problem for the implementation of the HTTP PUT verb.

The verb PUT requires the complete replacement of the resource, however information may not be accessible via the API but exist in the entity.

I must therefore be able to delete only all of the accessible properties (`@Expose` or !`@Exclude`). However, there are no functions proposed by `class-transformer` to obtain all the modifiable properties. Can you add this function ?

**Comment by NoNameProvided** [comment]
I am not sure I understand what you want to achieve. Please provide some example code.

**Comment by NoNameProvided** [comment]
Closing as OP is not responsive. If you are still experiencing the problem please open a new issue.
