### ISSUE TITLE
Feature Request: produce a web-optimized "module" entrypoint

### ISSUE THREAD

**Issue by closet6** [typestack/class-transformer#350]
### Description

Feature Request: produce a web-optimized "module" entrypoint

https://github.com/rollup/rollup/wiki/pkg.module

### Reproduction

go to pika and search for:  class-transformer 

### Environment

- [ x] deno: 1

**Comment by NoNameProvided** [comment]
Hi @closet6! 

Can you elaborate on what do you mean by this? Minification? Tree-shaking support, something else?

**Comment by NoNameProvided** [comment]
Tracked in #344.
