### ISSUE TITLE
fix: classToClassFromExist modifies sourceObject

### ISSUE THREAD

**Issue by lgarczyn** [typestack/class-transformer#351]
My understanding of classToClassFromObjectfrom is hazy at best, given the lack of examples about it, but it appears to transform a plain object into a source object's class, and copy the source object's data over to the existing object.

However, after very simple tests, it appears that sourceObject is also modified in the process.

I think clarification and documentation would be vital for this function

``` js
            console.log('converted ' + data.type);
            classToClassFromExist(this.target, data);
            // Different type is logged
            console.log('converted ' + data.type);
```

**Comment by NoNameProvided** [comment]
Fixed in f09d6baba8d1836ddffe4e59fd7544e0e71024c4, deprecated the whole stuff altogether.
