### ISSUE TITLE
Using a schema-based transformation

### ISSUE THREAD

**Issue by aabuelenin** [typestack/class-transformer#352]
Is it possible to declare a schema instead of using decorators, similar to class-validator?
https://github.com/typestack/class-validator#defining-validation-schema-without-decorators

I'm looking for a way to declare a contract/schema that contains everything related to transformation and validation, that's meant to make the business models more readable and promote sharing the contract with other components/services.

**Comment by NoNameProvided** [comment]
No, it's not. I would like to deprecate the schema-based validation in class-validator as well, so this feature won't be implemented.
