### ISSUE TITLE
class-transformer vulnerability found in package-lock.json

### ISSUE THREAD

**Issue by ishaileshmishra** [typestack/class-transformer#356]
moderate severity
Vulnerable versions: <= 0.2.3
Patched version: No fix
### class-transformer through 0.2.3 is vulnerable to Prototype Pollution. The 'classToPlainFromExist' function could be tricked into adding or modifying properties of 'Object.prototype' using a 'proto' payload.

**Comment by stellar-noah** [comment]
Duplicate of #343 #340 #339 
Closed by #341 #342

**Comment by saulotoledo** [comment]
@jotamorais This issue may be closed.
