### ISSUE TITLE
Decorator Metadata missing after transpiling

### ISSUE THREAD

**Issue by hepiyellow** [typestack/class-transformer#36]
Hi,

I have a package A which defines classes and uses class-transformer decorators.
When I test the package and use `classToPlain`, the decorators are used and I get my custom transforms and everything as expected.

Then I transpile this package with `tsc`, and import this package in package B.
When in package B I used `classToPlain` the decorator metadata is missing. I actually debugged it and saw that metadata is empty. Although I do see the `__decorate` and `__metadata` in the transpiled code (The `js` code).

I made sure that in package B:
- installed `class-transformer`
- installed 'reflect-metadata` and require in global place before everything
- added to tsconfig.json this "experimentalDecorators": true (although I think it is not necessary if I don't use new decorators, just the ones from package A)

Notes:
- I am using `ts-node/register` in my `mocha` tests in package B
- Using typescript 2.1.4

**Comment by pleerock** [comment]
its a known issue in typescript 2.1.x - there are issues with emitting decorators. Try to downgrade to 2.0.x

**Comment by hepiyellow** [comment]
I downgraded to typescript 2.0.10 in both package A and B,
and the problem still exists.

Just to make it clear, for example I have a @Transform decorator on a property which transforms a`number into a `string` when transforming `classToPlain`.
When I run the test in package A, I see the `string` (@Transform worked),
when I run it in package B, the created plain object has a `number`.

Could it be something else in package A, that I am forgetting?

**Comment by BrandiATMuhkuh** [comment]
Did you make progress with this issue? I have the same issue when importing the package into another one.

**Comment by BrandiATMuhkuh** [comment]
To double check, I have copied the source from my package A into package B. That seems to work now. 
I'm using typescript version 2.8.1

here is the `tsconfig.json` file for package A (The exporting package)

```
{
  "compilerOptions": {
    "lib": [
      "es6",
      "es2017"
    ],
    "module": "commonjs",
    "target": "es6",
    "sourceMap": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "declaration": true,
    "outDir": "./dist",
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "dist"
  ],
  "include": ["./src/**/*.ts"]
}
```

**Comment by hepiyellow** [comment]
Sorry i think i let it go back then. And never came back to it.

**Comment by patricknazar** [comment]
I am experiencing this too.

**Comment by patricknazar** [comment]
I worked around this by providing a static method inside the library class. It makes the call to `plainToClass`.

```
// in library
import { plainToClass } from 'class-transformer';
const transformFn = () => {....}

class Bla {
  @Transform(transformFn)
  property: SomeType

  static fromObject(obj) { return plainToClass(Bla, obj); }
}

// in consuming app
import { Bla } from 'my-library';
const instance = Bla.fromObject({property: ...})
```

Naturally it uses *it's* version of `class-transformer` and not the consuming app's one.

**Comment by spech66** [comment]
We run about this, too. If you have mutliple modules all of the class-transformers will maintain their own MetadataStorage instance therefore you have to use the approach of @patricknazar 
Is this considered the best-practice for this case?
