### ISSUE TITLE
Is dynamic property name supported?

### ISSUE THREAD

**Issue by sourcebit** [typestack/class-transformer#362]
I have a JSON like below: 
{
  'string1': Details [Object],
   'string2':  Details [Object],
}

string1 and string2 are dynamic string that can take on any value.

Is this supported in class -transformer?

Im using nestjs with typescript

**Comment by sourcebit** [comment]
Ok. I have resolved above by using below model

export class model {
 readonly [dynamicProperty: string]: Details
}

But in above I'm not able to use @Type decorator

**Comment by NoNameProvided** [comment]
No, dynamic property values are not supported.
