### ISSUE TITLE
Is string value supported in IsEnum now?

### ISSUE THREAD

**Issue by Zach-Ma** [typestack/class-transformer#364]
I want to check my query if it is valid below.
```JavaScript
 enum PRODUCT {
    "Dorado V6" = 1,
    "OceanStor 100p" = 2,
    "OceanStor 200p" = 3,
    "OceanStor 300p" = 4,
    "OceanStor 400p" = 5,
    "OceanStor 500p" = 6,
  }
```
But I got errors `must be a valid enum value` for using numbers as a query.
Is there a way to fix this? thanks

**Comment by NoNameProvided** [comment]
`IsEnum` is not part of the class-transformer library. If your question is still relevant you must ask it in the class-validator repository.
