### ISSUE TITLE
Bump npm package version

### ISSUE THREAD

**Issue by gregsolo-intent** [typestack/class-transformer#370]
Hello there! Any chance anyone could bump npm package version and release the package with the fixed vulnerability? 🙏

**Comment by asaunin** [comment]
@NoNameProvided are you planning to release new version?

**Comment by saulotoledo** [comment]
@gregsolo-intent, @asaunin A new version is being discussed internally. We are indeed waiting for a long time for this fix, but a few other PRs are being reviewed and merged for this new version. There is also an issue with permissions in the repository that are being discussed, but as soon as all this is resolved (and I think it will take a few days, but not much longer than that) you will see a new version of the library.

**Comment by tbrannam** [comment]
Pleased to see that there's movement on this project!  I'd suggest that releasing a version with just the security patch quickly as a minor release reduces the upstream risk vs bundling additional features/functionality.   At this point a couple more days probably won't make a massive difference though.

**Comment by NoNameProvided** [comment]
Done. 0.3.1 release with currently merged fixes.
