### ISSUE TITLE
Dynamic object key to class property name conversion for `plainToClass`

### ISSUE THREAD

**Issue by sido420** [typestack/class-transformer#372]
I am new to `class-transformer` and could not find what I was looking.

Is it possible to pass a function that gets called for each source object key and returns the target class's property name?
We can extend it to also convert values during transformation.

This is useful in cases where you have legacy code written and source object's keys/properties have different names than target class's property names (applicable to `plainToClass` obviously but can work for reverse function as well).

I noticed enable implicit conversion option but thats for conversion of types only I believe.

**Comment by NoNameProvided** [comment]
You can use the `@Transform` decorator for that. It receives the source value and the source object. So you can use something like: 

```ts
import 'reflect-metadata';
import { Expose, Transform, plainToClass } from 'class-transformer';

class Example {
  @Expose()
  @Transform((value, obj, type) => obj['oldPopr'])
  newProp: string;
}

const instance = plainToClass(Example, { oldPopr: 'value' }, { excludeExtraneousValues: true });

console.log(instance);
```

**Comment by NoNameProvided** [comment]
Closing as answered. If you have any questions left feel free to comment on this issue.
