### ISSUE TITLE
question: is typescript a non-negotiable requirement?

### ISSUE THREAD

**Issue by airtonix** [typestack/class-transformer#398]
Need to continue discussion of #139 ...

So essentially outcome of that is the you **must** use typescript? one can't use es6 with babel only?

**Comment by NoNameProvided** [comment]
Currently yes. We use the metadata emitted by the TypeScript compiler. 

Technically we could create an JS only version with decreased functionality, but I would rather not do that. Typescript is awesome and it can be easily enabled in any JS project with the `allowJS` option. So I don't see the increased maintenance cost justified for this functionality.
