### ISSUE TITLE
The @Type cannot detect in a dictionary?

### ISSUE THREAD

**Issue by tedwong** [typestack/class-transformer#40]
I found that it seems that it cannot be detected, did I do something wrong?:

```
    @Type(() => Album)
    albums : {
      [key : string]: Album
    };
```

**Comment by paulwalker** [comment]
+1

**Comment by Petr0vi4** [comment]
Same issue #31

**Comment by NoNameProvided** [comment]
Hi guys! 

I have removed the +1, as they don't add to the conversation, please add a thumb up emoji to the original question if you want to show your support. Thanks!

**Comment by NoNameProvided** [comment]
Closing this in favor of #31.
