### ISSUE TITLE
feature: classToPlain to return concrete type

### ISSUE THREAD

**Issue by ivawzh** [typestack/class-transformer#432]
### Description

Currently 

```
export declare function classToPlain<T>(object: T, options?: ClassTransformOptions): Record<string, any>;
export declare function classToPlain<T>(object: T[], options?: ClassTransformOptions): Record<string, any>[];
```

That is, `classToPlain` only returns arbitary `Record<string, any>` type.

It is critically useful to let `classToPlain` infer the concrete type of its result with supports of `@Expose`, `@Exclude`, and `@Transform`. 

E.g.

```ts
class User {
  @Exclude() id: number;
  @Exclude() setName: (fullName: string) => void;
  @Expose() firstName: string;
  @Expose() lastName: string;
  @Transform((value: Date) => value.toISOString(), { toPlainOnly: true })
  createdAt: Date
}

const userPlain: UserPlain = classToPlain(user);
type UserPlain = {
  firstName: string
  lastName: string
  createdAt: string
}
```

### Proposed solution

I am not familiar with the implementation of `@Expose`, `@Exclude`, and `@Transform`. But I'd hope it will be possible to create some mapped types that can handle these decorators/metadata.

**Comment by mponizil** [comment]
Perhaps something like this could be helpful? https://stackoverflow.com/a/55480598/712895

**Comment by NoNameProvided** [comment]
What you want would be a great feature but it is not possible with Typescript currently. However every function is typed so you can define your return type in the function call, that is the closest you can get to your desired behavior. 

```ts
classToPlain<Omit<BaseType, 'someExcludedProperty'>>(yourInstance);
```
