### ISSUE TITLE
Bar[] vs Array<Bar>

### ISSUE THREAD

**Issue by maartenmensink** [typestack/class-transformer#44]
I encountered the following issue

 ```
newValue_1.push is not a function
    at http://localhost:3000/main.bundle.js:217:36
    at Array.forEach (native)
    at TransformOperationExecutor.transform (http://localhost:3000/main.bundle.js:209:19)
    at _loop_1 (http://localhost:3000/main.bundle.js:332:45)
    at TransformOperationExecutor.transform (http://localhost:3000/main.bundle.js:355:17)
    at ClassTransformer.plainToClass (http://localhost:3000/main.bundle.js:143:25)
    at Object.plainToClass (http://localhost:3000/main.bundle.js:624:29)
```

After some testing i found out that `Bar[]` works fine and  `Array<Bar>` doesnt

**Works**
```
@Type(() => Bar)
Bars: Bar[] = new Bar[]();
```
**Doesn't work**
```
@Type(() => Bar)
Bars: Array<Bar> = new Array<Bar>();
```

**Issue?**
After some digging i found out that the reflected type was incorrect.

The reflectedType is `reflectedType:Object()` 
```
TransformOperationExecutor.prototype.getReflectedType = function (target, propertyName) {
        if (!target)
            return undefined;
        var meta = storage_1.defaultMetadataStorage.findTypeMetadata(target, propertyName);
        return meta ? meta.reflectedType : undefined;
    };
```

**Versions**
"class-transformer": "0.1.6",
"reflect-metadata": "0.1.8"

**Comment by 19majkel94** [comment]
Currently TypeScript reflection doesn't support generics, so `Array<Foo>` is registered as `Array` Type, so you need to decorate property with `@Type(() => Bar)`.

Also, you can't instantiate array in JS using `new Bar[]()` syntax. Array is a collection that can hold any type, the generic is only a support for developer and it's erased at compilation time.

**Comment by lavavrik** [comment]
Having the same issue after updating project to webpack 4 (using `thread-loader` now). With webpack 2/3 same code was working fine. Maybe I'm missing some configuration?
