### ISSUE TITLE
question: plainToClass ignores @Expose?

### ISSUE THREAD

**Issue by paolorr** [typestack/class-transformer#450]
I'm trying to transform an object using plainToClass but the getters on my class are not called. If I use classToClass the are called. Is this the expected behavior?
Ps: the service returns an array that was parsed from JSON, that's why I don't use classToClass

```ts
	...

	const appointments = await service.execute({ providerId, day, month, year });
	return response.json(plainToClass(Appointment, appointments));
```

Getter definition in the class

```ts
	...

	@Expose({ name: 'customProp' })
	getCustomProp(): string | null {
		console.log('----> called');
		return 'custom-value';
	}
```

EDIT:

I managed to get what I wanted by calling classToClass passing the return of plainToClass
```ts
	...

	const appointments = await service.execute({ providerId, day, month, year });
	return response.json(classToClass(plainToClass(Appointment, appointments)));
```

**Comment by NoNameProvided** [comment]
Closing as solved as OP commented on its own question.
