### ISSUE TITLE
question: Apply custom transform without running default transform

### ISSUE THREAD

**Issue by naiveal** [typestack/class-transformer#474]
I was trying to using custom transformer to transform an array from objects to class. The array is very big，so I want to improve the performance of the transformer step, so I want pass the objects directly to the custom transformer. But I found even I didn't set the Expose Type the transformer always apply default transform, this transform changes nothing, so is there any way to jump this useless transform.

**Comment by NoNameProvided** [comment]
I am not sure if I understand your question. What do you mean by passing the elements of the array directly to a custom transformer? If do you have a custom function which does the transformation already, why are you not calling it directly? Eg:

```js
hugeArray.map(myCustomTransformer)
```

**Comment by NoNameProvided** [comment]
Closing as no answer from OP.
