### ISSUE TITLE
fix: npm package does not contain esm5

### ISSUE THREAD

**Issue by FreekMencke** [typestack/class-transformer#485]
### Description
Currently the npm package does not contain the esm5 build files. I see there is a build:esm5, and that it's run in the continuous deployment pipeline, but in the npm package, it does not exist. There is only 1 build present in the npm package.

![image](https://user-images.githubusercontent.com/7610043/94261044-80f14f80-ff31-11ea-9e99-a45bef64994b.png)

### Expected behavior
All builds, including esm5, should be present in the npm package.

### Actual behavior
Only 1 type is available, and that type does not work on IE 11 (yea I know, but we must support it).

**Comment by guitarooman14** [comment]
+1 Waiting for it as well.

**Comment by jscssphtml** [comment]
+1

**Comment by NoNameProvided** [comment]
It should contain it now.
