### ISSUE TITLE
feature: expose metadata storage as part of public api

### ISSUE THREAD

**Issue by matt-psaltis** [typestack/class-transformer#487]
### Description
I would like to be able to inspect the class transformer decorators on my model classes to, for example generate graphql queries that match the model shape. Being able to inspect the properties and type metadata as well as property naming overrides would help keep this in sync and maintain a single source of truth for the client side models. 

### Proposed solution
Exporting the storage as part of the default public api exports would provide access to the same metadata storage that class transformer uses.

**Comment by NoNameProvided** [comment]
The metadata storage is intentionally an internal API. You can import it via passing a direct path, but it's not part of the public API so I don't have to make its internal API backward compatible. This won't change.
