### ISSUE TITLE
plainToClass conversion throwing TypeError: newValue_1.push is not a function

### ISSUE THREAD

**Issue by Jagpreet16** [typestack/class-transformer#49]
I am using Angular2 and while converting my jSon to object facing the error 
Uncaught TypeError: newValue_1.push is not a function
    at http://localhost:4200/vendor.bundle.js:105285:36
    at Array.forEach (native)
    at TransformOperationExecutor.transform (http://localhost:4200/vendor.bundle.js:105277:19)
    at _loop_1 (http://localhost:4200/vendor.bundle.js:105400:45)
    at TransformOperationExecutor.transform (http://localhost:4200/vendor.bundle.js:105423:17)
    at http://localhost:4200/vendor.bundle.js:105280:41

The JSON I am using is :
[{
	"name": "LegalStructure",
	"id": 1,
	"values": [{
		"id": 2,
		"name": "Besloten Vennootschap"
	}, {
		"id": 3,
		"name": "Naamloze Vennootschap"
	}]
}, {
	"name": "AddressType",
	"id": 9,
	"values": [{
		"id": 10,
		"name": "Registered Address"
	}, {
		"id": 11,
		"name": "Office Address"
	}, {
		"id": 12,
		"name": "Home Address"
	}]
}]

and the class to which I am converting is

import {Type} from 'class-transformer';
/**
 * Model for dropdown name and corresponding array of values of ApplicationValue type.
 *
 * @author pankaj.khurana@vernuso.com (Pankaj Khurana)
 */
export class ApplicationType {
    id: number;
    name: string;
    @Type(() => ApplicationValue)
    values: Array<ApplicationValue>;
}

/**
 * This signifies the value populated in the dropdown and its corresponding id.
 * As this class cannot stand alone, thereby making it a part of ApplicationType only.
 *
 * @author pankaj.khurana@vernuso.com (Pankaj Khurana)
 */
export class ApplicationValue {
    id: number;
    value: string;
}

Please suggest if I am missing something.

**Comment by anatoly-spb** [comment]
Try this 

```
export class ApplicationType {
   id: number;
  name: string;
  @Type(() => ApplicationValue)
  values: ApplicationValue[];
}
```

**Comment by Jagpreet16** [comment]
Thanks, it worked with this way!

But dont we have array support in this API yet?


On Fri, Feb 24, 2017 at 11:35 PM, Anatoly Shirokov <notifications@github.com

**Comment by 19majkel94** [comment]
Generics are not reflected by TypeScript yet, it resolves just to `Array`, no information about ApplicationValue.

**Comment by NoNameProvided** [comment]
Hi all!

I am closing this as answered/solved, please feel free to continue the discussion if it's not the case.
