### ISSUE TITLE
question: Release strategy of the library

### ISSUE THREAD

**Issue by anton-johansson** [typestack/class-transformer#490]
**Background**
#129 was fixed and merged (in #381) more than two months ago. Me (and probably many more) are waiting for this feature to avoid keep using workarounds.

**Question**
How's the plan/strategy for releases of this library? How soon can one expect new features to be released? I don't see any milestone or similar for the next release either, so it's a bit hard to know when it's due.

**Comment by anton-johansson** [comment]
Shameless bump. I really like this library, but I need the new functionality. If nothing happens, I'm going to need to consider an alternative. :(

**Comment by NoNameProvided** [comment]
Hey! 

Sorry for the caused inconvenience. I thought the changes were released and I had no time for TypeStack at the end of the year, so I haven't seen the complaints. Now the referenced changes are released. 

To prevent stuff like this from happening in the future, you can join or Slack and ping me when something like this happens. You can join via writing to typestack-slack-invite@outlook.com for now and I will add you manually.

**Comment by anton-johansson** [comment]
Thanks for the release and the information! I've sent an email regarding Slack. :)
