### ISSUE TITLE
question: Is it possible to make class-transformer use getters/setters when converting to/from json

### ISSUE THREAD

**Issue by PavelKastornyy** [typestack/class-transformer#496]
I am trying to port JavaFx to typescript and I wonder if class-transformer can help with converting from/to json when properties are used.

Let's suppose I have a json:

    {"firstName": "Mike", "age": 35}

And a class:

    export class Person {
         
        private firstName: StringProperty = new SimpleStringProperty();
        
        private age: NumberProperty = new SimpleNumberProperty();
        
        public constructor() {
            //does nothing
        }
        
        public setFirstName(firstName: string): void {
            this.firstName.set(firstName);
        }
        
        public getFirstName(): string {
            return this.firstName.get();
        }
     
        public firstNameProperty(): StringProperty {
            return this.firstName;
        }
        
        public setAge(age: number): void {
            this.age.set(age);
        }
        
        public getAge(): number {
            return this.age.get();
        }
        
        public  ageProperty(): NumberProperty {
            return this.age;
        }
    }

Can class-transformer serialize/deserialize instance of such class using getters and setter? If yes, could anyone show how to do it using this example?

**Comment by Roms1383** [comment]
Not sure I understand your question, you mean like serialize/deserialize to/from Java class?

**Comment by Roms1383** [comment]
If it's just about JS getter/setter, you should have a look at the documentation I think it already handles it.

**Comment by PavelKastornyy** [comment]
@Roms1383 No, serialize/deserialize to/from json. Yes, I've read about getters (@Expose()) in documentation but not sure if it is what I need. Besides, I found no information about setters that's why I asked this question.

**Comment by Roms1383** [comment]
What you depicted above, with `class-transformer`, would be as simple as :
```ts
export class Person {
    @Expose()
    firstName: string
    
    @Expose()
    age: number
}
```
Then if you get any specific requirements, there are tons of ways to customize your serialization/deserialization.

**Comment by PavelKastornyy** [comment]
@Roms1383 Thank you for your help, but I don't have `string` and `number` fields in my example. That's why I asked to give an example on the base of the code I provided.

**Comment by Roms1383** [comment]
Ah you mean you would like to have all the methods provided by `StringProperty` and `NumberProperty` as you would in Java ? No of course this you would have to implement it yourself, but here again `class-transformer` can probably make your life easier : have a look at all the examples with `@Expose` / `@Transform`.

**Comment by Roms1383** [comment]
Maybe something like :
```ts
import { Expose } from 'class-transformer';

export abstract class Base<T> {
  protected abstract value: T
  abstract getValue():T
  abstract setValue(value: T):void
  // and many other methods inherited from JavaFX
}
export class StringProperty extends Base<string> {
  // implement it using TypeScript
}
export class NumberProperty extends Base<number> {
    // implement it using TypeScript
}
export class Person {
   private firstNameProperty: StringProperty
   private ageProperty: NumberProperty

   @Expose()
   get firstName() { return this.firstNameProperty.getValue() }
   set firstName (value: string) { this.firstNameProperty.setValue(value) }

   @Expose()
   get age() { return this.ageProperty.getValue() }
   set age (value: number) { this.ageProperty.setValue(value) }
}
```
But honestly trying to use TypeScript like Java sounds weird a bit.

**Comment by PavelKastornyy** [comment]
@Roms1383 Thank you for your help. It sounds strange only at the beginning, see my project [here](https://github.com/PavelKastornyy/script4j). Two questions about the code you provided:

1. @Expose() is used for both get and set or only for get?
2. You again changed my example, I don't have `get firstName()` but have `getFirstName()`. So, will your code work with my getters and setters?

**Comment by Roms1383** [comment]
I just provided some hints, I'll let you experiment from the documentation 😃

**Comment by PavelKastornyy** [comment]
So, the question is still open. Could anyone help?

**Comment by NoNameProvided** [comment]
You are talking about getters and setters but you don't actually use them. Here is an example using getters/setters to expose properties while keeping most of your original API.

```ts
import 'reflect-metadata';
import { plainToClass, classToPlain, Exclude, Expose } from './index';

export class Person {
  @Exclude()
  private _firstName!: string;

  @Exclude()
  private _age!: number;

  public set firstName(firstName: string) {
    this._firstName = firstName;
  }

  @Expose({ name: 'firstName' })
  public get firstName(): string {
    return this._firstName;
  }

  // this is a function, but if you add @Expose then it will be included in the plain object
  public firstNameProperty(): string {
    return '<something-you-dont-want-on-the-output>';
  }

  public set age(age: number) {
    this._age = age;
  }

  @Expose({ name: 'age' })
  public get age(): number {
    return this._age;
  }

  public ageProperty(): string {
    return '<something-you-dont-want-on-the-output>';
  }
}

const instance = plainToClass(Person, {"firstName": "Mike", "age": 35});

console.log(instance); // logs: Person { _firstName: 'Mike', _age: 35 }
console.log(instance.firstName); // logs Mike
console.log(instance.age);  // logs 35
console.log(classToPlain(instance)); // logs: { firstName: 'Mike', age: 35 }
```

The original example you used have functions as getters that will never be implicitly called unless marked explicitly with the `@Expose` decorator.
