### ISSUE TITLE
0.3.2 Release

### ISSUE THREAD

**Issue by godenji** [typestack/class-transformer#502]
#344 will be fixed in the next release, when will that be?

Issue was closed in early August, would be great to benefit from tree shakable builds for this library (In an Ionic 5/Angular 10 library with latest TypeScript source-map-explorer shows class-transformer weighing in at 105KB, which is on the large size)

**Comment by nino-vrijman** [comment]
Also waiting for the next version for the fix for https://github.com/typestack/class-transformer/issues/129

**Comment by abarreau** [comment]
I'm also waiting for #344 !

**Comment by bagage** [comment]
Same here @abarreau, amazing! You look gorgeous.

Has anyone a workaround for now?

**Comment by wlucha** [comment]
Also waiting for the next version for the fix for #309

**Comment by godenji** [comment]
Actually, far more pressing than tree shakeable builds is the merged fix for #309 -- that's a real show stopper, performance is terrible with latest published release :(

Is there anything the community can do to help get a release out the door??

**Comment by Rush** [comment]
Does this library need additional maintainers? Sounds like it ...

**Comment by godenji** [comment]
Since it's been many months now, I forked and published under `class-transformer-oss` -- just a stopgap measure to use 0.3.2 commits until the maintainers get around to publishing the new release.

You can also revert to 0.1.10 (where performance is excellent) if none of the added features/fixes since that release are important to you.

**Comment by Rush** [comment]
I actually started using https://www.npmjs.com/package/@deepkit/type which completely replaced `class-transformer` for me. It's still in alpha so documentation is lacking by the author is very dedicated to making it a solid product. 

It used to be called https://www.npmjs.com/package/@marcj/marshal https://marshal.marcj.dev/ so its docs kind of apply to @deepkit/type as well.

**Comment by NoNameProvided** [comment]
Released.
