### ISSUE TITLE
feature: Support type-safe object literals in plainToClass

### ISSUE THREAD

**Issue by imgx64** [typestack/class-transformer#503]
### Description
When creating a complex object, it's sometimes desirable to use plainToClass with an inline object literal. Unfortunately, the plain object will not be type checked:

```ts
class User {
  name: string;
  age: number;
  constructor(name: string, age: number) {
    this.name = name;
    this.age = age;
  }
}

// no error for missing age, bad
const user1 = plainToClass(User, {
  name: 'test',
});
```

One way to do type checking is to provide the type explicitly. But you have to type the class name 3 times to get this to work:
```ts
// error, good but verbose
const user2 = plainToClass<User, User>(User, {
  name: 'test',
});
```

### Proposed solution
In my projects, I added a helper function:
```ts
function plainToClassInline<T>(cls: ClassType<T>, plain: T, options?: ClassTransformOptions): T;
function plainToClassInline<T>(cls: ClassType<T>, plain: T[], options?: ClassTransformOptions): T[];
function plainToClassInline<T>(cls: ClassType<T>, plain: T | T[], options?: ClassTransformOptions): T | T[] {
  return plainToClass(cls, plain, options);
}
```
(I'm not sure about the name. It could be made clearer)

Now you get proper type checking without repeating the class name:
```ts
// error. good and concise
const user3 = plainToClassInline(User, {
  name: 'test',
});
```

**Comment by lazarljubenovic** [comment]
This would work only for trivial cases, with no renamed or excluded properties.

**Comment by NoNameProvided** [comment]
As @lazarljubenovic mentions, this only works until you are not renaming properties, in that case the two type would not match and you wouldn't be able to call `plainToClass`. What would be cool to infer the `classToPlain` return type but I am not aware of any way to do that with Typescript.

**Comment by NoNameProvided** [comment]
I will close this as this is not possible I believe, but I will keep my eyes open for any such thing in the future as I believe automatic type inferring is a very useful feature.
