### ISSUE TITLE
feature: set default option for plainToClass and others

### ISSUE THREAD

**Issue by skobaken7** [typestack/class-transformer#516]
### Description
Passing options such as excludeExtraneousValues to every plainToClass call is too tiring and leads to bug.
I want to set default options.
``` typescript
import { setClassTransformOptions, plainToClass }

setClassTransformOptions({excludeExtraneousValues: true})
const obj = plainToClass(User, userJson) // behaves as plainToClass(User, userJson, {excludeExtraneousValues: true})
```

https://github.com/typestack/class-transformer/blob/develop/src/ClassTransformer.ts#L20
In other words, I want to change this empty object  in some way. 

### Proposed solution
I have two idea to implement this.
1. Like above, setClassTransformOptions saves default options. it is passed to ClassTransformer.
2. create ClassTransformer field to store default options and uses it when creating ClassTransformer. Users need to create own TransformOperationExecutor to use default options.

I have no idea about behavior when both default options and options passed by method exist.
1. default options are entirely ignored
2. merge both options

**Comment by NoNameProvided** [comment]
The advice for this scenario to wrapp class-transformer in a custom function which does do that: 

```ts
import { plainToClass as originalPlainToClass } from 'class-transformer';
import { defaultOptions } from './your-custom-options.constant'

function plainToClass(obj, option) {
  return originalPlainToClass(User, userJson, { ...defaultOptions, ...options});
} 
```
