### ISSUE TITLE
question: classToClass of different types object with null value fails

### ISSUE THREAD

**Issue by kafkapre** [typestack/class-transformer#518]
Hello I tried example of _Providing more than one type option classes_ (https://github.com/typestack/class-transformer#providing-more-than-one-type-option). 

When I call eg. 

`    
classToClass(
   plainToClass(Album, JSON.parse(
       "{\n" +
       "  \"id\": 1,\n" +
         \"name\": \"foo\",\n" +
         "  \"topPhoto\": {\n" +
             "    \"id\": 9,\n" +
             "    \"filename\": \"cool_wale.jpg\",\n" +
             "    \"depth\": 1245,\n" +
             "    \"__type\": \"underwater\"\n" +
            "  }\n" +
         "}"
))
`

it works, but when topPhoto is null it fails. Eg.

`
classToClass(
      plainToClass(Album, JSON.parse(
      "{\n" +
      "  \"id\": 1,\n" +
      "  \"name\": \"foo\",\n" +
      "  \"topPhoto\": null" +
  "}")
))
`
In documentation is written that discriminator must be defined (which is not in this case). Is there any workaround to pass this code without error (I want to avoid any wrapper classes)? Thanks.

**Comment by NoNameProvided** [comment]
Cannot reproduce with latest release. Running the example with `topPhoto: null` property will simply result in having `null` as value in the transformed object.

```ts
import 'reflect-metadata';
import { plainToClass, Type } from './index';

export abstract class Photo {
  id: number;
  filename: string;
}

export class Landscape extends Photo {
  panorama: boolean;
}

export class Portrait extends Photo {
  person: string;
}

export class UnderWater extends Photo {
  depth: number;
}

export class Album {
  id: number;
  name: string;

  @Type(() => Photo, {
    discriminator: {
      property: '__type',
      subTypes: [
        { value: Landscape, name: 'landscape' },
        { value: Portrait, name: 'portrait' },
        { value: UnderWater, name: 'underwater' },
      ],
    },
  })
  topPhoto: Landscape | Portrait | UnderWater;
}

let album = plainToClass(Album, {
  id: 1,
  name: 'foo',
  topPhoto: null,
});

console.log(album)
// logs Album { id: 1, name: 'foo', topPhoto: null }
```
