### ISSUE TITLE
TypeError: Reflect.getMetadata is not a function

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [typestack/class-transformer#52]
The readme says that reflect-metadata should be imported once - "and make sure to import it in a global place, like app.ts". Perhaps I'm missing something here, but if I import it in the root of my React app (I'm using babel to transpile), the transformer complains with the error above. It works only if I move the import 'reflect-metadata' to the actual class that is being serialized. Is that expected behavior?

**Comment by 19majkel94** [comment]
`reflect-metadata` should be available at the global scope, so importing in entry file should work. If not, configure webpack to bundle this module in global scope.

**Comment by sebastian-zarzycki-es** [comment]
I'm not sure there is such thing as entry file and/or global scope in React app. The entry file is index.js, but all imports done within file are still scoped to that file and not globally.

**Comment by 19majkel94** [comment]
Of course there is an entry file - the file where you have `ReactDOM.render(<App />, document.(...))`.
And if you do `import "reflect-metadata"` at the top of this file, it will be available at global scope.

**Comment by sebastian-zarzycki-es** [comment]
Apologies, turns out you're right, after all. My mistake was the order of imports in index.html - obviously, it has to be imported before other things/components using it, so ideally - the closer to the beginning of imports, the better. Once moved there, it worked.

Can be closed.

**Comment by NoNameProvided** [comment]
Hi all!

I am closing this as answered/solved, please feel free to continue the discussion if it's not the case.
