### ISSUE TITLE
fix: classToClass throws RangeError: Maximum call stack size exceeded with Jest

### ISSUE THREAD

**Issue by edilson** [typestack/class-transformer#528]
### Description

I'm using classToClass function to convert data and save it on cache but when I use it on my test environment is it throwing the error described on the title. 

**Minimal code-snippet showcasing the problem**
```ts
const subscribedChallenges = await this.challengesRepository.listAllUserChallengesActive(
        { page, offset },
        user_id,
        profile_id
      );

      subscribedChallenges.map(challenge => {
        utcToZonedTime(challenge.start_date, time_zone);
        utcToZonedTime(challenge.end_date, time_zone);
        utcToZonedTime(challenge.start_date_registration, time_zone);
        utcToZonedTime(challenge.end_date_registration, time_zone);

        return challenge;
      });

      await this.cacheProvider.save(
        cacheKey,
        classToClass(subscribedChallenges)
      );

      return subscribedChallenges;
```

### Expected behavior

Parse the data and save it to cache on my test environment.

### Actual behavior

Throws the ```RangeError: Maximum call stack size exceeded when used on test environment.``` error

**Comment by NoNameProvided** [comment]
This is not a minimal reproducible example because I cannot run it. Please remove all extra function calls, etc, and only include your test setup, handmade class instance, and the `classToClass` call.
