### ISSUE TITLE
fix: `excludeExtraneousValues` options ignored when used with `ignoreDecorators`

### ISSUE THREAD

**Issue by kb05** [typestack/class-transformer#533]
This is probably a misunderstanding, but I will open the ticket in case someone thinks the same.

I try to use the function "plainToClass" with the  options "ignoreDecorators" and  "excludeExtraneousValues".
```
{ ignoreDecorators: true, excludePrefixes: ['_'],excludeExtraneousValues:true }
```

When I execute the transform method the extraneous values persists (understanding as strange values the values not defined in the class).

This is because in the file ```src/TransformOperationExecutor.ts``` line ```413``` we found a conditional that in case ignoreDecorators is false does not enter in the block where ```excludeExtraneousValues``` is analyzed.

![image](https://user-images.githubusercontent.com/9481422/103216842-58edff80-4917-11eb-8820-cc1dded33204.png)

According to the definition of the  ```ClassTransformOptions```:

![image](https://user-images.githubusercontent.com/9481422/103216902-78852800-4917-11eb-8cae-2bcb3f7b0e12.png)

![image](https://user-images.githubusercontent.com/9481422/103216913-8175f980-4917-11eb-8e21-e52d324f2298.png)

It would make sense for me to want to ignore the ```@include``` and ```@exclude``` decorators, but also to ignore those extraneous values.

then, is a bug or has an explanation?

**Comment by NoNameProvided** [comment]
Thanks for the report! This is a bug.

**Comment by NoNameProvided** [comment]
I will update the documentation of this option.

**Comment by NoNameProvided** [comment]
Wait, it's a bug. We can read the property definition, without using the decorators.

**Comment by NoNameProvided** [comment]
Fixed in https://github.com/typestack/class-transformer/commit/bcf7bf151f6f1ff151397f7eda67735dc10530d5. It will be included in the next version.
