### ISSUE TITLE
fix: bad Boolean conversion

### ISSUE THREAD

**Issue by Dabada** [typestack/class-transformer#534]
Converting boolean string 'false' with Boolean('false') always gives true. 

https://github.com/typestack/class-transformer/blob/7020a72bca9765d08a6e91f2fd1152c0012c426c/src/TransformOperationExecutor.ts#L121

I'm using class-transformer with nestjs. When converting this url "api/user-service/users?pageSize=10&current=1&deleted=false" class-transformer returns true for the deleted parameter !

**Comment by NoNameProvided** [comment]
This is the intended behavior. `!!'false'` is true, so you see the expected behavior.
