### ISSUE TITLE
question: Are there any plans to release an ES modularised version of class-transformer ?

### ISSUE THREAD

**Issue by ognamala** [typestack/class-transformer#536]
We have recently upgraded our project to Angular 11 and we have been observing the following warnings

**Warning depends on 'class-transformer'. CommonJS or AMD dependencies can cause optimization bailouts.**

We were wondering whether there are plans for an ES modularised version for class-transformer?

Thanks !

**Comment by NoNameProvided** [comment]
Hi! 

Yes, there is, in fact, all the tooling is already there, so the next version will be supporting all common package formats.
