### ISSUE TITLE
Issue converting array to es6 set

### ISSUE THREAD

**Issue by vigneshnrfs** [typestack/class-transformer#54]
Just confirming if array to es6 Set works as you have specified in  https://github.com/pleerock/class-transformer/blob/master/test/functional/es6-data-types.spec.ts 

In my angular project, I get this error "ERROR TypeError: newValue_1.push is not a function
". es6 Map works fine. 

To Reproduce: 
Any new angular project created with @angular/cli  and class-transformer will reproduce this.

**Comment by Petr0vi4** [comment]
I think problem is in the angular-compiler itself.

For example, if we have
```
class User {
    @Type(() => Set) weapons: Set<string> = new Set();
}
```
`tsc` output will be
```
var User = (function () {
    function User() {
        this.weapons = new Set();
    }
    __decorate([
        Type(function () { return Set; }),
        __metadata('design:type', Set)            <--- ok!
    ], User.prototype, "weapons", void 0);
    return User;
}());
```
`ng build` output will be
```
var User = (function () {
    function User() {
        this.weapons = new Set();
    }
    __decorate([
        class_transformer_1.Type(function () { return Set; }), 
        __metadata('design:type', Object)        <--- wrong!
    ], User.prototype, "weapons", void 0);
    return User;
}());
```

**Comment by Petr0vi4** [comment]
Workaround: add
```
declare class Set<T> {}
```
in each file containing transformable classes with Set type properties, for example
before `User` class declaration.

**Comment by vigneshnrfs** [comment]
@Petr0vi4 Trying your above solution, the IDEs and `ng build` throws `Property 'has' does not exist on type 'Set<string>'.`

Should this issue be raised with the @angular/cli team?

**Comment by Petr0vi4** [comment]
Step by step example:

`> ng --version`
> angular-cli: 1.0.0-beta.24
node: 6.7.0
os: linux x64
@angular/cli: 1.0.0

`> ng new PROJECT2`
`> cd PROJECT2`
`> npm install class-transformer --save`
> project2@0.0.0 /var/www/native/js/PROJECT2
└── class-transformer@0.1.6

`> nano src/app/app.component.ts`

replace whole content with
```
import { Component, OnInit } from '@angular/core';
import { Type, plainToClass } from 'class-transformer';
declare class Set<T> {}

class User {
    @Type(() => Set) weapons: Set<string> = new Set();
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app works!';

 ngOnInit(): void {
    let obj = plainToClass(User, {weapons: ['1', '2', '3']});
    console.log(obj);
  }
}
```
`> ng serve`

then open page and see object in console
```
User
  weapons: Set(3)
    size: (...)
    __proto__: Set
    [[Entries]]: Array(3)
      0: "1"
      1: "2"
      2: "3"
      length: 3
    __proto__: Object
```

**Comment by vigneshnrfs** [comment]
@Petr0vi4 Sorry for the miscommunication. I did not say that it did not  work. The above works. However, if I try to use any methods of the class Set, it throws an error..

For example:
`ngOnInit(): void {
    let obj = plainToClass(User, {weapons: ['1', '2', '3']});
    obj.weapons.has('1');
    console.log(obj);
  }`

`ERROR in .../src/client/app/app.component.ts (27,17): Property 'has' does not exist on type 'Set<string>'.

And this will again cause an issue in AoT. 
`

**Comment by vigneshnrfs** [comment]
Adding to my above reply, I could leverage @Transform such as 
`class User {
  @Transform((value) => new Set<string>(value), {toClassOnly: true})
  weapons: Set<string> = new Set();
}`

But It does not work when weapon is a generic. 

```
import { Component, OnInit } from '@angular/core';
import { AuthService } from './user-module/service/auth.service';
import { classToPlain, plainToClass, Transform, Type } from 'class-transformer';


class Weapon {
  type: string;
  id: number;
}

class User {
  @Transform((value) => new Set<Weapon>(plainToClass(Weapon, value)), {toClassOnly: true})
  weapons: Set<Weapon> = new Set();
}


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'app works!';

  constructor(public auth: AuthService) {

  }

  ngOnInit(): void {
    let obj = plainToClass(User, {weapons: [{type: 'gun', id: 1}, {type: 'tank', id: 2}]});
    console.log('Class',obj);
    console.log('Object',classToPlain(obj));
  }
}
```

I get this error:
`AppComponent_Host.html:1 ERROR TypeError: Cannot read property 'prototype' of undefined
    at http://localhost:4200/vendor.bundle.js:106483:84
    at Array.filter (native)
    at MetadataStorage.findMetadatas (http://localhost:4200/vendor.bundle.js:106483:46)
    at MetadataStorage.findTransformMetadatas (http://localhost:4200/vendor.bundle.js:106387:21)
    at TransformOperationExecutor.applyCustomTransformations (http://localhost:4200/vendor.bundle.js:106017:58)
    at _loop_1 (http://localhost:4200/vendor.bundle.js:105985:41)
    at TransformOperationExecutor.transform (http://localhost:4200/vendor.bundle.js:106007:17)
    at http://localhost:4200/vendor.bundle.js:105864:41
    at Array.forEach (native)
    at TransformOperationExecutor.transform (http://localhost:4200/vendor.bundle.js:105861:19)
    at _loop_1 (http://localhost:4200/vendor.bundle.js:105984:45)
    at TransformOperationExecutor.transform (http://localhost:4200/vendor.bundle.js:106007:17)
    at ClassTransformer.plainToClass (http://localhost:4200/vendor.bundle.js:47126:25)
    at plainToClass (http://localhost:4200/vendor.bundle.js:106274:29)
    at AppComponent.webpackJsonp.304.AppComponent.ngOnInit (http://localhost:4200/main.bundle.js:285:105)`

**Comment by Petr0vi4** [comment]
I'm afraid that the only way to avoid 
> ERROR: Property 'has' does not exist on type 'Set<string>'.

is to declare Set class with all necessary functions =(
```
declare class Set<T> {
    has(value: T): boolean;
}

class Weapon {
  type: string;
  id: number;
}

class User {
   @Type(() => Weapon) weapons: Set<Weapon> = new Set();
}
```

**Comment by markusu49** [comment]
related issue: angular/angular-cli#7559

**Comment by NoNameProvided** [comment]
Hi all! 

Closing this as it's not an issue related to us. Please feel free to continue the discussion if you think otherwise.

**Comment by johndoe2361289638163** [comment]
Is there any solution for this?

**Comment by MTschannett** [comment]
@johndoe2361289638163 It seems that the problem with angular was fixed with Angular 5+. If you still have this issue, please open a new Issue and reference to this one. This is easier for us to keep track of what is open and what not.
