### ISSUE TITLE
fix: transforming string to lowercase turns string object into [object object] on latest version 0.3.2

### ISSUE THREAD

**Issue by abbasogaji** [typestack/class-transformer#560]
### Description

**Minimal code-snippet showcasing the problem**
 

```ts

```

**Comment by uamanager** [comment]
Guys this is because breaking changes in patch version.
You can fix it like this:

```typescript
// instead of this
@Transform((value) => value.toString())

// use object destruction as decorator pass object instead of list of arguments
@Transform(({value}) => value.toString())
```

**Comment by abbasogaji** [comment]
@uamanager i thought breaking changes should roll out a major release, because this could affect a lot of projects

**Comment by uamanager** [comment]
@abbasogaji Contributors of this library thinking in another way) That's how they broke my production also))

**Comment by abbasogaji** [comment]
@uamanager ...this is really bad.. I have quite lot of projects (microservices) in production using class-transformer , this is going to be a mess, now I have to make sure new deployments doesn't pick this version to avoid this issue

**Comment by uamanager** [comment]
@abbasogaji just fix version to 0.3.1 for now. that's the quickest way. and then update version and refactor code of microservices one by one.

**Comment by AckerApple** [comment]
572,670 Downloads a week but this package is claiming since in version 0 it still can have a party and do whatever it wants. The MINOR version should have at least been changed.

**Comment by abbasogaji** [comment]
@AckerApple worst part is the breaking changes on the 0.3.2 does not throw error or exited with non-zero code on CI, so basically its going to be a white bug (not error or warning or exception is thrown)

VERSION 0.3.2 NEEDS TO BE DELETED

**Comment by NoNameProvided** [comment]
Working as intended, the signature has changed in 0.3.2. It has been deprecated and republished with some extra changes as 0.4.0.
