### ISSUE TITLE
question: transform class instead of field

### ISSUE THREAD

**Issue by cbuchacher** [typestack/class-transformer#568]
**I was trying to...**

I would like to apply transformations to classes instead of fields. I.e., instead of

```ts
class MyNumber {
  public raw: number = 0;
}

class MyClass {
  @Type(() => MyNumber)
  @Transform(transformMyNumber)
  public num: MyNumber = new MyNumber();
}
```

I would like to write:

```ts
@Transform(transformMyNumber)
class MyNumber {
  public raw: number = 0;
}

class MyClass {
  @Type(() => MyNumber)
  public num: MyNumber = new MyNumber();
}
```

**The problem:**

The problem is that I have many fields of type MyNumber if multiple classes such as MyClass. The `@Transform` declaration is duplicated across all fields of type MyNumber, because the transformation is the same for all fields of type MyNumber. It is not specific to MyClass.

However, if I apply @Transform to MyClass directly, then I get this error message:

```
error TS1238: Unable to resolve signature of class decorator when called as an expression.
```

What do you recommend to do in such a case?

**Working example**

```ts
import 'reflect-metadata';
import { Type, TransformationType, Transform, TransformFnParams, plainToClass, classToPlain } from 'class-transformer';

class MyNumber {
  public raw: number = 0;
}

function transformMyNumber(params: TransformFnParams): MyNumber {
  switch (params.type) {
    case TransformationType.PLAIN_TO_CLASS:
      return { raw: params.value };
    case TransformationType.CLASS_TO_PLAIN:
      return params.value.raw;
    case TransformationType.CLASS_TO_CLASS:
      throw new Error('not implemented');
  }
}

class MyClass {
  @Type(() => MyNumber)
  @Transform(transformMyNumber)
  public num: MyNumber = new MyNumber();
}

const aNumber = new MyNumber();
aNumber.raw = 5.5;
const aClass = new MyClass();
aClass.num = aNumber;
console.log('classToPlain', classToPlain(aClass));
console.log('plainToClass', plainToClass(MyClass, { num: 5.5 }));
```

**Comment by NoNameProvided** [comment]
You need to apply transforms to class fields, you can extract the transform function and re-use it across different classes.

**Comment by cbuchacher** [comment]
Thank you for your answer. Yes, I understand that this is how class-transformer currently works. I started my question with an example which applies transforms to class fields and uses the extracted transform function `transformMyNumber`:

```
class MyNumber {
  public raw: number = 0;
}

class MyClass {
  @Type(() => MyNumber)
  @Transform(transformMyNumber)
  public num: MyNumber = new MyNumber();
}
```

I noticed that the transform decorators needs to be duplicated across all instances of type MyNumber. My question is if you would consider adding this capability as a feature? Do you see value in this?
