### ISSUE TITLE
question: Can I use classToPlain method with an plain object instead of a created by a class construtor?

### ISSUE THREAD

**Issue by fredpolicarpo** [typestack/class-transformer#569]
**Lib version:*** `^0.3.1`

**My need:**
I was trying to use the `classToPlain` method to generate a JSON object changing the field names.

Like the class X above:
```
class X {
    Expose({name:"otherName"})
    prop: string
}
```

**The problem:**
So I created an object to test, but the output is not as I expect:
```
cons x:X = { prop: "foo" }
console.log(classToPlain(x)) //output:  { prop: 'foo' }
```

**The workaround:**
But if I create the object using the `new` keyword, the method works well:
```
const x = new X()
x.prop = "bar"
console.log(classToPlain(x)) // output: { ' otherName': 'bar' }
```

**Comment by fredpolicarpo** [comment]
I guess that exists some `instanceof` inside the `classToPlain` function that is causing this bypass behavior.

https://stackoverflow.com/questions/45964008/typescript-instanceof-not-working

**Comment by asomethings** [comment]
class-transformer can't find metadatas for plain object since it's prototype won't match any. The possible workaround could work like below. Below should work as expected since it transforms it to a `class`.
```typescript
classToPlain(plainToClass(X, { prop: 'foo' }))
```

**Comment by NoNameProvided** [comment]
@asomethings answer is correct. Closing this as solved.
