### ISSUE TITLE
Union typescript

### ISSUE THREAD

**Issue by xero88** [typestack/class-transformer#579]
I'm trying to use an union :

```
  @Type(() => (User | AppUser))
  payload!: User | AppUser;
```

But I got error :

> 
> Argument of type '() => number' is not assignable to parameter of type '(type?: TypeHelpOptions | undefined) => Function'.
>   Type 'number' is not assignable to type 'Function'.ts(2345)

**Comment by MickL** [comment]
A little bit of google would have helped: https://stackoverflow.com/questions/61443377/class-transformation-of-discriminated-unions

**Comment by NoNameProvided** [comment]
MickL is correct in both the answer and that you should read the documentation before opening issues. Closing this as solved.

**Comment by MickL** [comment]
@NoNameProvided maybe the readme should include the word "union type" tho, so it can be found more easily.
