### ISSUE TITLE
feature: ExcludeIf

### ISSUE THREAD

**Issue by GuilhermeCunha** [typestack/class-transformer#580]
### Description

I would love to use Exclude based on the values ​​contained in the instance's attributes, but I couldn't find any way to do that.

For me it is very important to have this functionality, as it will help many people to maintain consistency in their classes. In my case, I use NestJs in conjunction with the class-validator and the class-transformer, and with this feature I would be able to be completely sure what is or is not coming to my API.

### Proposed solution

Use an approach similar to "Transform", since there is the possibility to access the object of the instance, and if the function passed by parameter to ExcludeIf returns "true", apply the same logic as the decorator "Exclude"

`@ExcludeIf((obj: Product) => obj.type === 'ONLINE')`

```
export class Product {
    type: 'PHYSICAL' | 'ONLINE'

    @ExcludeIf((obj: Product) => obj.type === 'ONLINE')
    deliveryPrice?: number
}
```

In the case of the type is "ONLINE" the object after the class-transformer would be:

```
{
  "type": "ONLINE"
}
```

**Comment by NoNameProvided** [comment]
You can use the `@TransformDecorator` with `exposeUnsetFields: false` to achieve this: 

```ts
import 'reflect-metadata';
import { classToPlain, Transform, Exclude  } from './index';

class ExampleClass {
  @Exclude() // <-- This is not needed, just showcasing you can hide the control property. 
  public remove!: boolean;

  @Transform((({ value, obj }) => obj.remove ? undefined : value ))
  public testProp!: string;
}

const instanceOne = new ExampleClass();
const instanceTwo = new ExampleClass();

instanceOne.remove = true;
instanceOne.testProp = 'some-value-to-hide';

instanceTwo.remove = false;
instanceTwo.testProp = 'some-value-to-keep';

console.log(classToPlain(instanceOne, { exposeUnsetFields: false })); // logs: {}
console.log(classToPlain(instanceTwo, { exposeUnsetFields: false })); // logs: { testProp: 'some-value-to-keep' }

``` 

Is this working for you or is there any special reason you need the extra decorator?

**Comment by GuilhermeCunha** [comment]
Thanks for the answer ! That's exactly what I really need, but I'm not able to use this solution using NestJs

**Comment by GuilhermeCunha** [comment]
Thank you very much @NoNameProvided, it was exactly what I needed!

I leave [here](https://github.com/GuilhermeCunha/nestjs-class-transformer) a link to an example repository for the functionality I needed to implement.
