### ISSUE TITLE
@Expose decorator behaves differently in Jest

### ISSUE THREAD

**Issue by Semyonic** [typestack/class-transformer#583]
### Description
Using `@Expose` decorator in a DTO class to rename object property doesn't work properly in `Jest` testing environment.

**Minimal code-snippet showcasing the problem**
```ts
@Expose({ name: 'id', toPlainOnly: true })
  readonly _id: string;
````
Here's a  [ReproductionRepo](https://github.com/Semyonic/class-transformer-expose-deco-problem-repro)

### Expected behaviour
It should've transformed the `_id` to `id` correctly in a `testing` environment.

### Actual behavior

It returns untransformed value as `_id`

**Comment by NoNameProvided** [comment]
You need to import `reflect-metadata` in your tests.
