### ISSUE TITLE
deserialize Expose not working with inheritance in the typescript class.

### ISSUE THREAD

**Issue by AmitGera007** [typestack/class-transformer#59]
I am using the class-transformer  package to transform the JSON object to typescript class object which is working as expected. But when my typescript class in inherited/extends from some base class then the conversion of JSON to Typescript on base class property is not working.

Here is the sample code- 
export class UserBase {
    @Expose({ name: "payment" })
    salary: number;  
}

export class User extends UserBase {
    @Expose({ name: "MyName" })
    firstName: string;
    lastName: string;
    age: number;
}
let jsonuser = { "age": 123, "MyName": "TEST", "lastName": "TESTLastName","payment": 1000 },

if I do deserialize(User, JSON.stringify(jsonuser)); the salary property is not get set , is get as payment only.

Please let me know if I am missing anything here.

**Comment by NoNameProvided** [comment]
Hi all!

I am closing this as answered/solved, please feel free to continue the discussion if it's not the case.
