### ISSUE TITLE
fix: plainToClass still has broken functionality regarding functions and classes

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [typestack/class-transformer#596]
### Description
Previously described here: https://github.com/typestack/class-transformer/issues/276 and here: https://github.com/typestack/class-transformer/pull/374

The code in question happens around 
https://github.com/typestack/class-transformer/blob/develop/src/TransformOperationExecutor.ts#L189

Basically, whenever a property is a function or a class, during transformation, there is attempt to invoke it, which, in case of function, results in erratic, unexpected behavior and in case of classes, it triggers an error:

```
13:50:08.396 ERROR TypeError: class constructors must be invoked with 'new'
    transform TransformOperationExecutor.js:160
    plainToClass ClassTransformer.js:14
    plainToClass index.js:14
```

### Expected behavior
Transformation shouldn't instantiate classes or invoke functions.

### Actual behavior
Explained above.

Simple testcase: 
```
class SideBarItem {

  label: string;

  callback?: () => any;
  
  useClass: any;

}
```
```
init() {
   const item = plainToClass(SideBarItem, { label: 'Logout', callback: this.logout() });
}

logout() {
    // do something obviously dangerous here
}
```
(logout is executed during transformation)

or 
```
init() {
   const item = plainToClass(SideBarItem, { label: 'Logout', useClass: MyService });
}
```
(class error is being thrown)

I think, especially during plainToClass transformation, there's no point in executing a function or trying to instantiate a class that a property points to. It's clearly an attempt to change an anonymous plain object into a proper class, in a way, it's a shortcut, to avoid doing the mundane target class instantiation and then copying the necessary properties. 

I'm not sure what the intention here was, but I fail to see the usecase for it.

I think that part of the code in TransformationOperationExecutor should look like this:
```
// get a subvalue
let subValue: any = undefined;
if (this.transformationType === TransformationType.PLAIN_TO_CLASS) {
    subValue = value[valueKey];
}
else {
    if (value instanceof Map) {
        subValue = value.get(valueKey);
    }
    else if (value[valueKey] instanceof Function) {
        subValue = value[valueKey]();
    }
    else {
        subValue = value[valueKey];
    }
}
``` 

and this is, in fact, an autopatch, that I have to apply every install to class-transformer, unfortunately. Ideally, this should be incorporated into the package - or an explanation should be given, why there's an attempt to extract a "subvalue" (whatever that is) from a plain object at that stage, with suggestions how to work around this properly.

**Comment by NoNameProvided** [comment]
Well I am not sure about this change (class-transformer is messy and I never get to clean it up properly since I took it over) but tests are passing, so let's give it a go. Fixed in 90feca36d2b44b6c66428ccef9402b13b58f7e2e

**Comment by sebastian-zarzycki-es** [comment]
Thanks for looking into this. Will definitely test the new version.

**Comment by NoNameProvided** [comment]
> (edit: I see console.log in the referenced commit - should it be there?)

No, it will be removed before final release, thanks for the heads up.

**Comment by sebastian-zarzycki-es** [comment]
Any chance for a release containing this update?

**Comment by NoNameProvided** [comment]
I am planning on working on the TypesStack repos on the weekend, but no promises.

**Comment by sebastian-zarzycki-es** [comment]
Thank you!

**Comment by sebastian-zarzycki-es** [comment]
How about this weekend? :)

**Comment by lehno** [comment]
Hi guys, thanks for the effort, I really need this update
