### ISSUE TITLE
Nested keys don't work as expected

### ISSUE THREAD

**Issue by TheSamsterZA** [typestack/class-transformer#61]
Hi,

Here's a simple example that I expected to work:

```typescript
import { plainToClass, Expose } from 'class-transformer';

let personObj = {
    first_name: 'Joseph', 
    last_name: 'Maxwell',
    aka: {
        nick_name: 'Joe'
    }
}

export class Person {
    @Expose({ name: 'first_name' })
    firstname: string;

    @Expose({ name: 'last_name' })
    lastname: string;

    @Expose({ name: 'aka.nick_name' })
    nickname: string;
}

let person: Person = plainToClass(Person, personObj);
```
`person.firstname = 'Joseph'`&nbsp;&nbsp;&nbsp;&nbsp;:heavy_check_mark:
`person.lastname = 'Maxwell'`&nbsp;&nbsp;&nbsp;&nbsp;:heavy_check_mark:
`person.nickname = undefined`&nbsp;&nbsp;&nbsp;&nbsp;:x: `// Why? I want the value in personObj.aka.nick_name`
`person.aka.nick_name = 'Joe'`&nbsp;&nbsp;:x: `// Why is this here?`

What am I doing wrong?

**Comment by oferRounds** [comment]
@TheSamsterZA any luck with this? Same problem

**Comment by oferRounds** [comment]
Hi @pleerock, is this supported? Thanks!

**Comment by TheSamsterZA** [comment]
> @TheSamsterZA any luck with this? Same problem

@oferRounds Nope, I ended up dropping `class-transformer` and manually wiring up what I needed. Would absolutely love for this to be fixed! I hope @pleerock sees this and at least responds so we know if the scenario is supported or not.

**Comment by oferRounds** [comment]
@TheSamsterZA – yes! thanks for this response!

**Comment by NoNameProvided** [comment]
Nested objects are not supported in `@Expose` there was a conversation about it, I have added a tracking issue #195. You can track it there.
