### ISSUE TITLE
fix: ES5 variant isn't been used by browserify

### ISSUE THREAD

**Issue by YellowGarbageBag** [typestack/class-transformer#623]
### Description

I'm using class-transformer 0.4.0 in an environment in combination with AngularJS.
In the build pipeline i summarize all files to a single JS file with browserify/tsify, with TS target "es5".
But in the single JS file the class-transformer isn't available in ES5.

Thanks for your help.

**Minimal code-snippet showcasing the problem (1)**

Quick check with `are-you-es5`:

```bash
npm init -y
npm i class-transformer
npx are-you-es5 check .
```
Output:
```text
npx: installed 10 in 3.392s
❌ class-transformer is not ES5
Non-ES5 dependencies detected.
```

**Minimal code-snippet showcasing the problem (2)**

Check with an example project:

```bash
npm init -y
npm i class-transformer typescript@4.1 browserify tsify
./node_modules/.bin/tsc --init

echo "import { classToClass } from 'class-transformer'" >> example.ts
echo "console.log(classToClass(''))" >> example.ts
./node_modules/.bin/browserify example.ts -o browserified.js -p tsify
```
The generated code around line 1950 in `browserified.js` isn't the ES5 variant.

### Expected behavior

After building the application with browserify/tsify there is no valid ES5 code.

### Actual behavior

In the generated JS file should the ES5 variant be included.

**Comment by NoNameProvided** [comment]
We define them as the default require (`main`) so it should pick it up by default. We are explicitly defining the available formats for build tools in https://github.com/typestack/class-transformer/blob/develop/package.json#L8-L12. I am not familiar with browserify, can you tell me what browserify look for when deciding what to import?

**Comment by YellowGarbageBag** [comment]
According to the documentation I could find `browserify` always imports the code referenced in the `main` section. If this is not ES5 code, then it needs to be compiled with Babel.

My solution will be to switch to `rollup` (or `webpack`) as well, since this package takes into account the `package.json` settings.

So it is not a bug of `class-transformer` but of my development stack.
Thanks for your help.
