### ISSUE TITLE
fix: main, module entries are pointed to ./cjs , ./esm5 but builds files on ./build/ directory

### ISSUE THREAD

**Issue by vivekkj123** [typestack/class-transformer#634]
### Description

Hi there,

I was trying to package this module to Debian. While I'm packing, I experienced a problem because of entries of package.json. All build commands of this package builds on ./build directory, but the entries like main, module, esm5 are pointed to ./main, ./module, and ./esm5 respectively. I don't know is this a bug or not. Anyway waiting to hear from you.
**Minimal code-snippet showcasing the problem**
 

```ts
  "main": "./cjs/index.js",
  "module": "./esm5/index.js",
  "es2015": "./esm2015/index.js",
  "typings": "./types/index.d.ts",

```
```
    "build:es2015": "tsc --project tsconfig.prod.esm2015.json",
    "build:esm5": "tsc --project tsconfig.prod.esm5.json",
    "build:cjs": "tsc --project tsconfig.prod.cjs.json",
    "build:umd": "rollup --config rollup.config.js",
    "build:types": "tsc --project tsconfig.prod.types.json",
```

### Expected behavior
Builds the package without any errors.

### Actual behavior
```
+ tsc --project tsconfig.prod.types.json
   dh_auto_test --buildsystem=nodejs
	ln -s ../. node_modules/class-transformer
	/usr/bin/node -e require\(\"./.\"\)
internal/modules/cjs/loader.js:303
      throw err;
      ^

Error: Cannot find module '/home/vivek/Debian_Packaging/class-transformer/node-class-transformer/cjs/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:295:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:18)
    at Object.runInThisContext (vm.js:309:38)
    at Object.<anonymous> ([eval]-wrapper:10:26) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/vivek/Debian_Packaging/class-transformer/node-class-transformer/package.json',
  requestPath: './.'
}
dh_auto_test: error: /usr/bin/node -e require\(\"./.\"\) returned exit code 1
make: *** [debian/rules:8: build] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

```

**Comment by vivekkj123** [comment]
@NoNameProvided please have a look into it

**Comment by NoNameProvided** [comment]
Hi! It's pointed to eg `./cjs/index.js` because the `package.json` gets copied into the `build` folder so `build/package.json` references `build/cjs/index.js`.

This is the expected behavior, we ship multiple versions of the lib to allow build tools to pick the best option according to their own config.

**Comment by vivekkj123** [comment]
>package.json gets copied into the build folder so build/package.json references build/cjs/index.js.

I've tried building several times, but in my case, the pacakge.json file is not copied into build/ directory.

**Comment by NoNameProvided** [comment]
Here are the build steps: https://github.com/typestack/class-transformer/blob/develop/.github/workflows/continuous-deployment-workflow.yml
