### ISSUE TITLE
question: How to use TypeHelpOptions

### ISSUE THREAD

**Issue by btilford** [typestack/class-transformer#655]
**I was trying to...**
Understand how to use `TypeHelpOptions` and if it could help in this scenario.

```typescript
_links: Record<string, Link | Link[]>;
```

**The problem:**
Documentation is a TODO comment :) 
https://github.com/typestack/class-transformer/blob/9610f51ada01674dd575409b3bbbbdfa29fda79a/src/interfaces/type-help-options.interface.ts#L2

**Comment by HJ29** [comment]
I have a similar question,
``` typescript
enum TYPE {
  foo = 'foo',
  bar = 'bar'
}
class Base {
  type: TYPE;
}
class Foo extends Base {
  type: TYPE.foo;
  foo: string;
}
class Bar extends Base {
  type: TYPE.bar;
  bar: string;
}
class Random {
  value: Record<string, Foo | Bar>;
}
```
any idea how to declare this kind of type?
so that plainToClass transform value into `Foo` or `Bar` class instead of object

**Comment by diffy0712** [comment]
Although, I do not really understand your question, I think you need [type discriminators](https://github.com/typestack/class-transformer?tab=readme-ov-file#providing-more-than-one-type-option).
