### ISSUE TITLE
question: Expose all properties but reject every not defined in class structure

### ISSUE THREAD

**Issue by johny1614** [typestack/class-transformer#724]
Let's say we have class like this:
```
class Dog {
    @IsString()
    name: string;
}
```

And plain object:

```
const plainDoggie = {
      name: 'Azor',
      surname: 'dogs does not have surnames :('
    };
```
After transformation I would like to have only those properties that are declared in Dog class, so just "name".
I know I can achieve it by adding `@Expose()` to name property. However If Dog class has more properties (age, stamina, breed etc.) it will become unnecessary boilerplate I want to avoid. I've tried my best on [stackblitz](https://stackblitz.com/edit/class-transformer-expose-all?file=src/app/app.component.ts), but didn't found solution.

**Comment by cojack** [comment]
@johny1614 https://github.com/typestack/class-transformer#enforcing-type-safe-instance

**Comment by johny1614** [comment]
@cojack I've read docs, such syntax is not acceptable for me, so there is no other option? Did not find any recommendation about using stackoverflow.

**Comment by cojack** [comment]
`such syntax is not acceptable for me` I can't help here.

**Comment by sebastiangug** [comment]
@cojack  -- I'm not sure if he's explaining it right or if it's even the same issue. 

But: 

```


class StupidDTO {
  @IsOptional()
  media: string[];
}


    const public_raise: StupidDTO= plainToClass(
      StupidDTO,
      { created_by: "potato", media: [] },
      { excludeExtraneousValues: true, strategy: "exposeAll" },
    );
``` 

--- this will not work unless I explicitly add @Expose() decorator, even though the strategy is set to `exposeAll`.  

exposeAll does not seem to work with `excludeExtraneousValues:` -- but really it should.

**Comment by johny1614** [comment]
@sebastiangug I believe you've got my idea.
> exposeAll does not seem to work with excludeExtraneousValues: -- but really it should.

That would do the work, I could avoid @expose boilerplate for every property then. Should I make Bug issue/Feature Request for that and link in this topic?

**Comment by johny1614** [comment]
I've opened bug issue ([LINK](https://github.com/typestack/class-transformer/issues/740)) and close this topic.
