### ISSUE TITLE
classToPlain failed when there is array of objects

### ISSUE THREAD

**Issue by galloween** [typestack/class-transformer#73]
Hi, when I send request with array of object in the body and I get error, this is my request:
![image](https://user-images.githubusercontent.com/2077754/28249304-f32b286e-6a5b-11e7-8369-cf73e5e0da3e.png)

And this is the error I get
![image](https://user-images.githubusercontent.com/2077754/28249308-0bf44902-6a5c-11e7-92dd-94cb11b6def3.png)

I tried to debug like so:
![image](https://user-images.githubusercontent.com/2077754/28249312-1e133760-6a5c-11e7-9558-330e74834039.png)

And this is what I got
![image](https://user-images.githubusercontent.com/2077754/28249315-2a986726-6a5c-11e7-8d10-74ed02f908d5.png)

is it ok that it checks the inner of the object and not the outside "roles" ?

thanks in advanced !

**Comment by galloween** [comment]
After reading a lot of duplication, I found out that @Type solve it, for now it's good probably need to be fixed

**Comment by NoNameProvided** [comment]
Yes, you need to specify the received type if it's not a built-in primitive.
