### ISSUE TITLE
feature: Decorators in the constructor

### ISSUE THREAD

**Issue by ProMastersss** [typestack/class-transformer#808]
### Description
There is a class:
`class User {
   constructor(@Expose() public id: number) {}
}`

It would be nice to add support for decorators in the constructor if a shortened field declaration entry is used

### Proposed solution
Overloading of decorators is required

**Comment by LaysDragon** [comment]
typescript have an discussion related to this too
https://github.com/microsoft/TypeScript/issues/10777
