### ISSUE TITLE
using es6 Set

### ISSUE THREAD

**Issue by markusu49** [typestack/class-transformer#81]
Is there some special configuration needed when using es6 data structures? Just copied the code from this [test case](https://github.com/pleerock/class-transformer/blob/7343716b96f466d54e905fabc50371bbc71c56ea/test/functional/es6-data-types.spec.ts#L206) into my Angular Cli app and it fails at this line:

`const classedUser = plainToClass(User, plainUser);`

> TypeError: newValue_1.push is not a function

**Comment by Petr0vi4** [comment]
#54

**Comment by NoNameProvided** [comment]
Hi all!

I am closing this as in favor of #81, feel free to continue the discussion there.
