### ISSUE TITLE
Nested Type and castToPlain breaks imports

### ISSUE THREAD

**Issue by npoirey** [typestack/class-transformer#82]
This is rather peculiar, so I made what I believe to be a minimal reproducing project in angular.

It seems that as soon as I have more than 1 nested objects level, compilation breaks with
`Module not found: Error: Can't resolve ...` from my definition file.
This happens only when a call to `classToPlain` is made on a class with a nested element having itself another nested element.

You can reproduce with this project: 
https://github.com/npoirey/class-transformer-bug

The only additions from a standard angular-cli project is the content in `src/assets/schema` and the file `app.component.ts`

just run `ng serve` to see the error I'm talking about (I included package.json in git).

If you remove the call to `console.log(classToPlain(ConnectedUser, {}));` in `app.component.ts`, the app compile. 

Likewise, it will work if you remove wallet from ConnectedUser and IConnectedUser

The only way I made it work was by moving the @type annotation from the class to the interface, but this file is generated and it show other errors ("IWallet only refers to a type, but is being used as a value here") :(

Is there no way to use interfaces with this library ?

**Comment by NoNameProvided** [comment]
Closing this as out-of-date, if you are still experiencing difficulties please open a new issue.
