### ISSUE TITLE
question: Status of the project

### ISSUE THREAD

**Issue by yafanasiev** [typestack/class-transformer#824]
Hi!

First of all, thanks for a great concept and a great library. We are using it as a part of NestJS stack and as a separate library as well. However, it looks like it has been abandoned since the February 2021. Is someone still maintaining it? Also, it would be great to get a new release with some stuff already fixed but not included in 0.4.0 ( like https://github.com/typestack/class-transformer/commit/90feca36d2b44b6c66428ccef9402b13b58f7e2e). Thanks in advance!

**Comment by romgerman** [comment]
I agree. This lib is wonderful! But the bugs need to be fixed. I'd like to hear the status from the maintainers of this repo.

**Comment by Sti2nd** [comment]
@yafanasiev As far as I can see these typestack repositories have not been maintained the last few months. The licence is MIT, so someone could maintain a fork if they want.

**Comment by diffy0712** [comment]
See https://github.com/typestack/class-transformer/issues/1389.
