### ISSUE TITLE
@Exclude not working on class inside ES6 Map

### ISSUE THREAD

**Issue by markusu49** [typestack/class-transformer#86]
The workaround mentioned in #54 (declaring the Set interface inside each file file containing transformable classes) also applies to Map. Without it, there is no error, but the resulting Object is simply not an instance of Map.

There is still another problem, which I was able to reproduce based on this [test case](https://github.com/pleerock/class-transformer/blob/7343716b96f466d54e905fabc50371bbc71c56ea/test/functional/es6-data-types.spec.ts#L116):

The code as is works fine in my Angular 4 environment (`classedUser` is instanceof `User`, `classedUser.weapons` is instanceof `Map` and `classedUser.weapons.get("firstWeapon")` is instanceof `Weapon`).

But if I add `@Exclude()` to the `Weapon` class, `classedUser.weapons` is still instanceof `Map`, but does not contain any items. This is independent of adding `@Expose()` decorators or using class properties instead of constructor arguments. With `Set`, this works fine.

**Comment by NoNameProvided** [comment]
This has been fixed already.
