### ISSUE TITLE
Support for string enums

### ISSUE THREAD

**Issue by MTschannett** [typestack/class-transformer#90]
String enums are now supported in TypeScript (since V2.4).

Are there any plans that this will be supported?

**Comment by frozenex** [comment]
+1

**Comment by NoNameProvided** [comment]
Can you please detail your request with examples for what is not working now, and how should it work in your opinion?

**Comment by NoNameProvided** [comment]
Closing this as invalid. After thinking this through there is nothing to support with string enums. 

```ts
import 'reflect-metadata';
import { Type, plainToClass } from 'class-transformer';

enum StringEnum {
  ValueA = 'value-A',
  ValueB = 'value-B',
}

export class ExampleClass {
  public myEnum: StringEnum;
}

const instance = plainToClass(ExampleClass, { myEnum: StringEnum.ValueA });

console.log(instance); 
// prints: ExampleClass { myEnum: "value-A" }
console.log(StringEnum.ValueA); 
// this prints the string "value-A" 
```

The two value is the same so there is nothing to transform. 

If you would like to check the validity of the content of property, you can use [class-validator][cv].

[cv]: https://github.com/typestack/class-validator/
