### ISSUE TITLE
fix: use global scope for metadata storage

### ISSUE THREAD

**Issue by petrzjunior** [typestack/class-transformer#928]
### Description
Currently, the type metadata are cached in `MetadataStorage` which is created `src/storage.ts` and exported. As long as this file is imported once, it works as intended. When importing (requiring) file, Node.js looks it up in the import cache so that the every file is not imported only once. This however relies on consistent file names and has some caveats as covered in the [documentation](https://nodejs.org/api/modules.html#modules_module_caching_caveats). For instance file case sensitiveness or using symlinks inside node_modules. This behavior can lead to having more than one instance of `MetadataStorage` and failing to resolve the correct data types, consequently spitting up random errors.

### Expected behavior
I expect class-transformer not to rely on importing logic. And creating a singleton storage.

### Actual behavior
Singleton is not a true singleton and importing from symlinked locations causes it to create multiple instances.

**Comment by soloyal** [comment]
Simple fix in **storage.ts**

```ts
const globalRef = global as any
export const defaultMetadataStorage = global.classTransformerMetadataStorage 
  || (global.classTransformerMetadataStorage = new MetadataStorage());
```

We are all waiting your new release with the fix!)

**Comment by y0gzah** [comment]
This is still not fixed.
I'm using class-transformer class-validator class-sanitizier and routing-controllers in different packages of my project.
And decorators just don't exist at all from one package to the other.
