### ISSUE TITLE
fix: README.md wrong spelling

### ISSUE THREAD

**Issue by nobel6018** [typestack/class-transformer#983]
### Description

There is wrong spelling in README.md at line 459

```
  @Expose()
  get name() {
    return this.firstName + ' ' + this.lastName;
  }
```

**Minimal code-snippet showcasing the problem**
 

```ts

```

### Expected behavior

```
getName() {
```

### Actual behavior

```
get name() {
```

**Comment by diffy0712** [comment]
The documentation is correctly using a javascript getter. There is no problem with it.

Closing as invalid.
