### ISSUE TITLE
plainToClass @Rename annotation

### ISSUE THREAD

**Issue by Dunky13** [typestack/class-transformer#99]
It would be nice to have an annotator that is something like Rename, that will allow to rename certain properties.
Basically the opposite of 
```
@Expose({ name: "uid" })
    id: number;
```
||
V
```
@Rename({ name: "uid" })
    id: number;
```

**Comment by NoNameProvided** [comment]
`@Expose` works in both direction, you don't need the opposite of it.

**Comment by NoNameProvided** [comment]
Hi all!

I am closing this as answered/solved, please feel free to continue the discussion if it's not the case.

**Comment by rodrigopaixao** [comment]
Hello everyone. 

I am having the same issue. I want to expose a variable with a different name:

**plainToClass**
product_description => productDescription

**classToPlain**
productDescription => product_description

I was assuming the @Expose({name: 'product_description'}) would convert in all operations, but it doesn't. Any idea of how to set this alias?

Thanks!!
